bazel_registry.json
We can switch to `https://mirror.bazel.build` when we actually launch the BCR.
=> Add bazel_registry.json file

README.md, tools/add_module.py
The Bazel team should not be the default maintainer of a module, if not set, the field will just be empty in the generated json file.
=> Update README.md and fix add_modules.py about module maintainer 

modules/protobuf/3.19.0/patches/relative_repo_names.patch, modules/protobuf/3.19.0/presubmit.yml, modules/protobuf/3.19.0/source.json
Essentially a "cherrypick" of https://github.com/protocolbuffers/protobuf/pull/9187
=> Update protobuf with relative repo names patch

modules/rules_cc/0.0.1/patches/add_module_extension.patch, modules/rules_cc/0.0.1/source.json, modules/rules_python/0.4.0/MODULE.bazel
- rules_cc now also includes xcode_configure in the cc_configure module extension, which allows us to not appending xcode_configure.WORKSPACE.
- rules_python now registers default python toolchains, which allows us to not appending python.WORKSPACE.
=> Toolchain registration improvement for rules_cc and rules_python

modules/bazel_skylib/1.0.3/MODULE.bazel
The module definition of `bazel_skylib` lacks the equivalent of the
`bazel_skylib_workspace()` macro, which registers the unittest
toolchains.
=> bazel_skylib: Register unittest toolchains

modules/bazel_skylib/1.0.3/MODULE.bazel
The unittest toolchains offered by `bazel_skylib` use `@platforms`, which with `bzlmod` has to be declared as an explicit dependency.
Without this addition, I see failures such as:
```
ERROR: external/bazel_skylib.1.0.3/toolchains/unittest/BUILD:22:10: no such package '@platforms//os': The repository '@platforms' could not be resolved: Repository '@platforms' is not visible from repository '@bazel_skylib.1.0.3' and referenced by '@bazel_skylib.1.0.3//toolchains/unittest:cmd_toolchain'
```
=> bazel_skylib: Add missing toolchain dependency

modules/rules_sh/0.2.0/MODULE.bazel, modules/rules_sh/0.2.0/patches/add_module_extension.patch, modules/rules_sh/0.2.0/presubmit.yml, modules/rules_sh/0.2.0/source.json, modules/rules_sh/metadata.json
[rules_sh](https://github.com/tweag/rules_sh) provides a Bazel toolchain for standard shell tools. It is a dependency of rules_haskell and rules_nixpkgs.
=> Add rules_sh 0.2.0

modules/rules_nodejs/4.5.0/source.json
I made a mistake in yesterday's release and uploaded files that didn't match the release SHA.
As a result, usage of this module fails (the extensions.bzl file isn't
in that artifact).
=> Fix wrong SHA on rules_nodejs artifact.

modules/protobuf/3.19.2/MODULE.bazel, modules/protobuf/3.19.2/patches/relative_repo_names.patch, modules/protobuf/3.19.2/patches/remove_dependency_on_rules_jvm_external.patch, modules/protobuf/3.19.2/presubmit.yml, modules/protobuf/3.19.2/source.json, modules/protobuf/metadata.json
Also adds the java_library targets used by Bazel to the presubmit config.
=> Add protobuf 3.19.2

modules/protobuf/3.19.0/patches/add_module_dot_bazel_for_examples.patch, modules/protobuf/3.19.0/presubmit.yml, modules/protobuf/3.19.0/source.json, modules/protobuf/3.19.2/patches/add_module_dot_bazel_for_examples.patch, modules/protobuf/3.19.2/presubmit.yml, modules/protobuf/3.19.2/source.json
This PR updates the test config for protobuf to use the new matrix testing and bcr test module features.
This change adds more patch for already checked in modules, this should not happen when BCR officially launches, but it's fine for now because we're still in testing phase.
=> Update protobuf to have better test config

README.md, tools/add_module.py, tools/registry.py
With https://github.com/bazelbuild/continuous-integration/issues/1302, we now encourage module maintainer to check in a test module instead of the entire test suite of the project.
Also generating presubmit.yml in the new matrix testing format.
=> Improve presubmit.yml generation

modules/zlib/1.2.11/patches/add_build_file.patch, modules/zlib/1.2.11/presubmit.yml, modules/zlib/1.2.11/source.json
Use [the BUILD file](https://github.com/tensorflow/tensorflow/blob/80d2c8dfe24003804bb1921632bc0974be1569af/third_party/zlib.BUILD#L1) from TensorFlow, which makes `@zlib//:zlib.h` public.
=> Update BUILD file for zlib

tools/add_module.py, tools/migrate_to_bzlmod.py, tools/registry.py
The script does the following things:
1. Run the build without Bzlmod enabled to generate resolved external
dependencies with --experimental_repository_resolved_file
2. Run the build with Bzlmod enabled and identify recongnized error message
3. Use the resolved external deps info to give migration suggestions.
4. Repeat 2 and 3 until all external deps are available via Bzlmod (or WORKSPACE.bzlmod).
To start the migration, clone the Bazel central registry repo and run the following command from your project root:
```
<path to a local BCR repo>/tools/migrate_to_bzlmod.py <build flags> <build targets>
```
=> Adding a helper script for Bzlmod migration.

modules/c-ares/1.16.1/patches/add_build_file.patch, modules/c-ares/1.16.1/source.json
The file list of c-ares 1.15.0 is used for 1.16.1 since the following files are
the same:
1. modules/c-ares/1.16.1/patches/add_build_file.patch
2. modules/c-ares/1.15.0/patches/add_build_file.patch
And add_build_file.patch is adapted from
https://github.com/grpc/grpc/tree/master/third_party/cares. I have tried to find
c-ares version 1.16.1 in grpc project. A search of grpc project commit log shows
that the most relevant thing is commit bdb3f860649bb4c136ba36bad3d9363fccbd29fa
which mentions '-DgRPC_CARES_PROVIDER=package with c-ares 1.16.0 overrides'. My
guess is that grpc has upgraded c-ares from 1.15.0 to 1.17.2 directly.
I built c-ares 1.16.1 with `buildconf` on macOS. The resulted Makefile has
the following two file list:
1. CSOURCES: C++ source files.
2. HHEADERS: C++ header files.
A …
=> Update file list for c-ares 1.16.1

.github/workflows/verify_source_urls.yml, modules/aspect_bazel_lib/0.4.2/source.json, modules/aspect_rules_js/0.3.2/source.json, modules/aspect_rules_swc/0.3.0/source.json, modules/zlib/1.2.11/source.json, modules/zstd-jni/1.5.0-4/source.json, tools/registry.py, tools/verify_stable_archives.py
As suggested in https://github.com/bazelbuild/bazel-central-registry/issues/69#issuecomment-1090885327, this PR adds a tool and GH Action to verify that all the source URLs follow the format of stable URL as per https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300
There are two open questions for me:
- Should we also verify that the archive has a file ending of `.tar.gz`? There are currently some sources that utilize the `.zip` variant of archives.
- The lint fails right now, as I was unsure how to handle the preexisting unstable URLs. I started to manually migrate the URLs, but the first one I adjusted (of `rules_cc`), yielded an artifact that had a different checksum to the previous artifact, which would break the integrity hash. What's the best way to …
=> Set up GH Action to verify stable source URLs

modules/rules_cc/0.0.1/patches/add_module_extension.patch, modules/rules_cc/0.0.1/source.json
This is because Bazel currently uses the built-in cc toolchain configuring mechanism (in `@bazel_tools`), and *not* the one in rules_cc. In order to prevent the local cc toolchain from being discovered twice, this commit removes the automatic toolchain registration from rules_cc. In the rare case where someone wants to specifically use the toolchain from rules_cc, they can call `use_extension` on this extension themselves and add the relevant toolchain in their own MODULE.bazel file.
NB: We're directly updating the current version instead of creating a new version because the BCR is not officially launched yet.
=> Remove toolchain registration from rules_cc

modules/glog/0.5.0/patches/remove_only_the_first_leading_at.patch, modules/glog/0.5.0/source.json
Upstream PR: https://github.com/google/glog/pull/832
=> Patch glog to work with canonical label literals

modules/rules_go/0.33.0/MODULE.bazel, modules/rules_go/0.33.0/patches/bcr.patch, modules/rules_go/0.33.0/presubmit.yml, modules/rules_go/0.33.0/source.json, modules/rules_go/metadata.json
This is highly experimental and thus carries a `print` warning.
=> Add rules_go 0.33.0

modules/apple_support/1.0.0/MODULE.bazel, modules/apple_support/1.0.0/presubmit.yml, modules/apple_support/1.0.0/source.json
Adds the new 1.0.0 release: https://github.com/bazelbuild/apple_support/releases/tag/1.0.0
One question: we forgot to bump our checked-in `MODULE.bazel` version number before cutting the release in `apple_support`: https://github.com/bazelbuild/apple_support/releases/tag/1.0.0
Will this cause issues and is it something that we need to fix before merging this PR, or can it be postponed until the next release? Also, why does it matter if the `MODULE.bazel` is already checked-in here?
=> Add apple_support 1.0.0

bazel_registry.json
Previously we were using https://bcr.bazel.build/test-mirror as the mirror location in case something goes wrong, it turns out the setup is reliable enough, now we can switch to https://bcr.bazel.build/mirror
=> Change archive mirror location for the BCR

modules/zlib/1.2.12/MODULE.bazel, modules/zlib/1.2.12/patches/add_build_file.patch, modules/zlib/1.2.12/presubmit.yml, modules/zlib/1.2.12/source.json, modules/zlib/metadata.json
This yanks version 1.2.11 due to CVE-2018-25032
=> Add zlib 1.2.12

modules/rules_python/0.10.2/MODULE.bazel
These are needed when invoking `pip_repository`.
=> Expose missing repos for rules_python 0.10.2

modules/gazelle/0.26.0/source.json
Mutates an existing version as the BCR isn't immutable yet.
Lays the groundwork for `go_proto_library` support.
=> gazelle: Update 0.26.0 to more recent commit

modules/zstd-jni/1.5.2-3/MODULE.bazel, modules/zstd-jni/1.5.2-3/patches/Native.java.patch, modules/zstd-jni/1.5.2-3/patches/add_build_file.patch, modules/zstd-jni/1.5.2-3/presubmit.yml, modules/zstd-jni/1.5.2-3/source.json, modules/zstd-jni/metadata.json
Included small addition of assembly files during non-windows builds. The rest is identical to 1.5.0-4.
Aimed to support https://github.com/bazelbuild/bazel/pull/16394
=> zstd-jni: add v1.5.2-3

modules/protobuf/3.19.6/MODULE.bazel, modules/protobuf/3.19.6/patches/add_module_dot_bazel_for_examples.patch, modules/protobuf/3.19.6/patches/relative_repo_names.patch, modules/protobuf/3.19.6/patches/remove_dependency_on_rules_jvm_external.patch, modules/protobuf/3.19.6/presubmit.yml, modules/protobuf/3.19.6/source.json, modules/protobuf/metadata.json
Due to https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2, we'll need a newer protobuf version
=> Add protobuf 3.19.6

modules/protobuf/metadata.json
Context: https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2
=> Yank protobuf versions affected by security issue

.github/workflows/trigger_bcr_ui_rebuild.yml
Addresses https://github.com/bazel-contrib/bcr-ui/issues/20
For this to work a `BCR_UI_REPO_ACCESS_TOKEN` secret needs to be set by one of the repo maintainers.
I've included a comment describing what kind of access token needs to be generated (and the newly released fine-grained PATs seem great for it, but need to be enabled on the `bazel-contrib` org first).
=> Set up workflow trigger for bcr-ui rebuild

tools/registry.py
when adding modules with tools/add_module.py
My understanding is that a `.netrc` file is honored when bazel fetches repositories, so this should add the necessary symmetry for private registries. Probably not useful for the central registry, but useful for private forks.
=> Honor .netrc files when fetching module sources

.github/workflows/verify_source_urls.yml
Verifying the source url step is moved the bcr_validation.py and is integrated in the BCR presubmit on BuildKite, therefore we no longer need this.
=> Remove verify_source_urls.yml

tools/bcr_validation.py, tools/registry.py
This PR adds check for MODULE.bazel to make sure the checked in MODULE.bazel file is the same as the one in the extracted and patched source tree. Using `--fix` option to tell the script to fix the mismatch by applying a patch file for the MODULE.bazel file.
Also added check for patch files' integrity value.
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/120
=> bcr_validation.py: Validate MODULE.bazel

modules/rules_swift/1.2.0/MODULE.bazel, modules/rules_swift/1.2.0/patches/add-initial-bzlmod-support.patch, modules/rules_swift/1.2.0/presubmit.yml, modules/rules_swift/1.2.0/source.json, modules/rules_swift/metadata.json
This PR adds the current release of `rules_swift` to the central registry. The patch will be useless in the next version that we'll hopefully cut soon.
=> Add rules_swift 1.2.0

modules/rules_apple/2.0.0-rc1/MODULE.bazel, modules/rules_apple/2.0.0-rc1/patches/add-non-module-deps-via-bzlmod-module-extension.patch, modules/rules_apple/2.0.0-rc1/presubmit.yml, modules/rules_apple/2.0.0-rc1/source.json, modules/rules_apple/metadata.json
We recently cut a new release of `rules_apple` that supports Bazel 6.0.0rc1, so this version should build in the BCR as well now.
=> Add rules_apple 2.0.0-rc1

tools/add_module.py
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/283
=> Run BCR validations after adding new module with add_module.py

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/module_wanted.yaml
The immediate goal is to ensure more uniformity of the module wanted requests, and to collect links to upstream issues. Hopefully this automates a bit of the maintenance work for this repo.
=> chore: introduce simple issue templates

modules/rules_python/metadata.json
This module version is broken and no one can use it, yanking it will provide better error message for users. 
Closes https://github.com/bazelbuild/bazel-central-registry/issues/287
=> Yank rules_python 0.14.0

tools/bcr_validation.py
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/307
Example run:
```
$ ./tools/bcr_validation.py --check_all_metadata
+++ Validating all metadata.json files
BcrValidationResult.FAILED: rules_sh@0.1.0 doesn't exist, but it's recorded in rules_sh's metadata.json file.
BcrValidationResult.FAILED: Failed to load rules_python's metadata.json file: Expecting ':' delimiter: line 27 column 17 (char 611)
```
=> bcr_validation.py: add --check_all_metadata flag to check all metadata.json files

bazel_registry.json
Per legal review, we can't easily host a source archive mirror without triggering license issues. Given the reasonable reliability of GitHub CDN, this isn't really worth pursuing (and enterprise users can still use their own mirros if necessary).
=> Remove the default source archive mirror

modules/protobuf/21.7/MODULE.bazel, modules/protobuf/21.7/patches/add_missing_files.patch, modules/protobuf/21.7/patches/add_module_dot_bazel.patch, modules/protobuf/21.7/patches/add_module_dot_bazel_for_examples.patch, modules/protobuf/21.7/patches/relative_repo_names.patch, modules/protobuf/21.7/presubmit.yml, modules/protobuf/21.7/source.json, modules/protobuf/metadata.json
All the deps are handled except for rules_kotlin, which is still missing on BCR.
Adding protobuf without Kotlin, to make it possible to release `rules_proto` and then also `py_proto_library` in `rules_python`.
=> Add protobuf v21.7

modules/fmt/9.1.0/MODULE.bazel, modules/fmt/9.1.0/patches/add_build_file.patch, modules/fmt/9.1.0/patches/module_dot_bazel.patch, modules/fmt/9.1.0/presubmit.yml, modules/fmt/9.1.0/source.json, modules/fmt/metadata.json
I'm testing BCR on a separate project and wanted to work with [fmt-9.1.0](https://github.com/fmtlib/fmt/releases/tag/9.1.0).
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
=> Add fmt-9.1.0 module

tools/README.md, tools/migrate_to_bzlmod.py
- Removed obsolete code and require Bazel 6.0.0
- Added flags to control the scripts behaviours.
- Write module extensions to add non-Bazel-module dependencies. It guesses when to use a separate module extension.
- Added non-interactive mode and set it as default. The script tries to make a best guess on what to do.
- Added documentation for different scripts under tools directory.
=> Make migrate_to_bzlmod.py more usable and add more docs

README.md
After going through the internal launch review process, we have got the approval to officially launch the Bazel Central Registry.
Compared to the original design, the major difference is that we no longer have the default mirror for source archives due to legal concerns.
We should now fully respect the [BCR policies](https://github.com/bazelbuild/bazel-central-registry/blob/main/docs/bcr-policies.md#bazel-central-registry-bcr-contribution-policies), especially the "add-only" policy to ensure reproducibility.
=> BCR is now officially launched!

modules/spdlog/1.11.0/MODULE.bazel, modules/spdlog/1.11.0/patches/add_build_file.patch, modules/spdlog/1.11.0/patches/module_dot_bazel.patch, modules/spdlog/1.11.0/presubmit.yml, modules/spdlog/1.11.0/source.json, modules/spdlog/metadata.json
Just copied across the existing module definition and bumped the version of fmt as required by the newer version of spdlog.
=> Add spdlog 1.11.0

modules/rules_xcodeproj/0.12.0/MODULE.bazel, modules/rules_xcodeproj/0.12.0/patches/add_module.patch, modules/rules_xcodeproj/0.12.0/presubmit.yml, modules/rules_xcodeproj/0.12.0/source.json, modules/rules_xcodeproj/metadata.json
First release [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) that supports bzlmod. After this we'll be switching to automatic releases once https://github.com/buildbuddy-io/rules_xcodeproj/pull/1585 is merged.
=> Add rules_xcodeproj 0.12.0

modules/bazel_skylib/1.4.0/MODULE.bazel, modules/bazel_skylib/1.4.0/presubmit.yml, modules/bazel_skylib/1.4.0/source.json, modules/bazel_skylib_gazelle_plugin/1.4.0/MODULE.bazel, modules/bazel_skylib_gazelle_plugin/1.4.0/presubmit.yml, modules/bazel_skylib_gazelle_plugin/1.4.0/source.json, modules/bazel_skylib_gazelle_plugin/metadata.json
See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.4.0
=> Bump bazel_skylib to 1.4.0 and add bazel_skylib_gazelle_plugin-1.4.0

modules/rules_kustomize/0.2.0/MODULE.bazel, modules/rules_kustomize/0.2.0/presubmit.yml, modules/rules_kustomize/0.2.0/source.json, modules/rules_kustomize/metadata.json
Impound Bazel rules for [the Kubernetes-related _kustomize_ tool](https://kubectl.docs.kubernetes.io/references/kustomize/) defined in [the _bisontrails/rules_kustomize_ GitHub repository](https://github.com/bisontrails/rules_kustomize).
=> Add rules_kustomize@0.2.0

modules/catch2/3.3.0/MODULE.bazel, modules/catch2/3.3.0/patches/module_dot_bazel.patch, modules/catch2/3.3.0/presubmit.yml, modules/catch2/3.3.0/source.json, modules/catch2/metadata.json
Simply add the newest catch2 version available right now.
=> Add catch2 v3.3.0

modules/rules_poetry/0.1.0/MODULE.bazel, modules/rules_poetry/0.1.0/presubmit.yml, modules/rules_poetry/0.1.0/source.json, modules/rules_poetry/metadata.json
The PR publishes the initial version of rules_poetry module that can use poetry.lock files to set up Python dependencies.
=> Publish oxidase/rules_poetry@v0.1.0

modules/rules_testing/metadata.json
The rules_testing 0.0.5 release is mostly broken because it requires users to register a specific repo name. A new release is being made that doesn't have this problem.
See https://github.com/bazelbuild/rules_testing/issues/33 for details.
=> Yank rules_testing 0.0.5 because it's mostly broken.

modules/rules_flex/0.2.1/MODULE.bazel, modules/rules_flex/0.2.1/presubmit.yml, modules/rules_flex/0.2.1/source.json, modules/rules_flex/metadata.json
As requested in https://github.com/bazelbuild/bazel-central-registry/issues/204
I edited the `presubmit.yml` to remove `windows`, because Flex does not build on that platform (https://github.com/westes/flex/issues/367).
cc @aaronmondal
=> Add rules_flex v0.2.1

modules/abseil-py/1.4.0/MODULE.bazel, modules/abseil-py/1.4.0/patches/module_dot_bazel.patch, modules/abseil-py/1.4.0/presubmit.yml, modules/abseil-py/1.4.0/source.json, modules/abseil-py/metadata.json
Add abseil.py as a module to the BCR.
This is required to migrate android_rules to bzlmod.
=> Add abseil.py 1.4.0

modules/jsonnet/0.20.0/MODULE.bazel, modules/jsonnet/0.20.0/patches/extensions_dot_bzl.patch, modules/jsonnet/0.20.0/patches/module_dot_bazel.patch, modules/jsonnet/0.20.0/presubmit.yml, modules/jsonnet/0.20.0/source.json, modules/jsonnet/metadata.json
This adds Jsonnet v0.20.0 to BCR.
Jsonnet recently accepted a patch to add a MODULE.bazel (+ an extension) to the project. As there hasn't been a release yet that includes this, this PR also adds these files using patches.
There are some interdependencies between jsonnet, go-jsonnet and rules_jsonnet, and it would be very nice not to have to wait until jsonnet cuts a release before moving forward with introducing go-jsonnet and rules_jsonnet to BCR.
I've tested this by building/testing jsonnet itself, as well as building/testing go-jsonnet while depending on this module using a BCR fork.
=> Publish google/jsonnet@0.20.0

modules/jsonnet_go/0.20.0/MODULE.bazel, modules/jsonnet_go/0.20.0/patches/module_dot_bazel.patch, modules/jsonnet_go/0.20.0/presubmit.yml, modules/jsonnet_go/0.20.0/source.json, modules/jsonnet_go/metadata.json
Related to https://github.com/bazelbuild/bazel-central-registry/pull/667 which added jsonnet to BCR, and https://github.com/google/go-jsonnet/pull/698 which will add a MODULE.bazel (with the same contents as the patch in this PR) to the upstream project.
This will add go-jsonnet to BCR, which is used among others by rules_jsonnet. There is no source archive added to their release process today, but I will try to make that happen.
=> Publish google/go-jsonnet@0.20.0

modules/re2/2023-06-02/MODULE.bazel, modules/re2/2023-06-02/patches/module_dot_bazel.patch, modules/re2/2023-06-02/presubmit.yml, modules/re2/2023-06-02/source.json, modules/re2/metadata.json
=> Add RE2 release `2023-06-02`.

modules/sqlite3/3.42.0.bcr.1/MODULE.bazel, modules/sqlite3/3.42.0.bcr.1/patches/add_build_file.patch, modules/sqlite3/3.42.0.bcr.1/patches/module_dot_bazel.patch, modules/sqlite3/3.42.0.bcr.1/presubmit.yml, modules/sqlite3/3.42.0.bcr.1/source.json, modules/sqlite3/metadata.json
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/697
Side note regarding BCR testing: currently it supports testing an "example" sub-module, but this is fairly inconvenient when the package doesn't natively use Bazel as its build system -- the patches become quite large. It would be nice if it were possible to have the test module in the BCR repo instead.
=> Add sqlite3 v3.42.0.bcr.1

modules/gazelle/metadata.json, modules/rules_go/metadata.json
These version were marked as experimental, which resulted in print warnings whenever their module files are evaluated. As they are still discovered starting from modern versions of these rulesets, the warnings ended up affecting all users. 
By yanking these versions, Bazel 6.3.0 and later will no longer emit the warnings.
=> Yank obsolete rules_go and gazelle versions

modules/eigen/3.4.0/MODULE.bazel, modules/eigen/3.4.0/patches/add_build_file.patch, modules/eigen/3.4.0/patches/module_dot_bazel.patch, modules/eigen/3.4.0/presubmit.yml, modules/eigen/3.4.0/source.json, modules/eigen/metadata.json
Note that this project from GoogleVR adds some exclusions to the headers (not sure why), as well as a couple of preprocessor defines:
https://github.com/googlevr/seurat/blob/master/third_party/eigen.BUILD
Let me know if I should add these to the BUILD file patch.
=> Add Eigen 3.4.0 to Bazel Central Registry

modules/libdeflate/metadata.json
https://github.com/bazelbuild/bazel-central-registry/pull/835 introduced a `metadata.json` without a `maintainers` field, breaking build of bcr-ui (see https://github.com/bazel-contrib/bcr-ui/issues/77).
To me it also seems that according to BCR policy, the PR shouldn't have been accepted without a maintainer for the module specified.
Optimally this PR would be amended with the contact info of @Vertexwahn as a module maintainer.
=> Fix missing maintainers field for libdeflate

modules/re2/metadata.json
As discussed on https://github.com/bazelbuild/bazel-central-registry/pull/806, setting `compatibility_level = 11` to match the `SONAME` doesn't make sense in the Bazel model.
Neither version of RE2 is used by anything in BCR. All versions of gRPC so far have specified `2021-09-01`.
=> Yank RE2 releases `2023-06-02` and `2023-08-01`.

modules/swift-syntax/509.0.0.1/MODULE.bazel, modules/swift-syntax/509.0.0.1/patches/deps.patch, modules/swift-syntax/509.0.0.1/patches/module_dot_bazel.patch, modules/swift-syntax/509.0.0.1/presubmit.yml, modules/swift-syntax/509.0.0.1/source.json, modules/swift-syntax/metadata.json
The upstream tag was created before a BUILD file patch to make sure everything built.
=> Add swift-syntax patched version

modules/rules_java/6.5.1/MODULE.bazel, modules/rules_java/6.5.1/patches/module_dot_bazel_incompatibility.patch, modules/rules_java/6.5.1/source.json
This release requires `@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type`, which is only available as of https://github.com/bazelbuild/bazel/commit/783a50e6489f6a212ac01cfaa6f6576b51ae1c93.
=> [rules_java] Mark v6.5.1 as compatible with `>=6.4.0`

modules/llvm-project/17.0.3/MODULE.bazel, modules/llvm-project/17.0.3/patches/0001-Add-Bazel-files-to-.gitignore.patch, modules/llvm-project/17.0.3/patches/0002-Add-LLVM-Bazel-overlay-files.patch, modules/llvm-project/17.0.3/patches/0003-Add-MODULE.bazel.patch, modules/llvm-project/17.0.3/patches/0004-Add-BUILD.bazel.patch, modules/llvm-project/17.0.3/patches/0005-Add-Bazel-LLVM-targets.patch, modules/llvm-project/17.0.3/patches/0006-Add-LLVM-version-vars.patch, modules/llvm-project/17.0.3/patches/0007-Guard-against-empty-workspace-root.patch, modules/llvm-project/17.0.3/patches/0008-Correct-builtin-headers-prefix.patch, modules/llvm-project/17.0.3/patches/0009-Fix-an-operator-overload-for-GCC-8.3.patch, modules/llvm-project/17.0.3/patches/0010-Use-TEST_TMPDIR-on-Unix-when-it-is-set.patch, modules/llvm-project/17.0.3/patches/0011-Use-Windows-assembly-files-for-BLAKE3-on-Windows.patch, modules/llvm-project/17.0.3/patches/0012-Add-scope-resolution-operators-for-MSVC-2019.patch, modules/llvm-project/17.0.3/patches/0013-Disable-zlib-zstd-mpfr-and-pfm.patch, modules/llvm-project/17.0.3/presubmit.yml, modules/llvm-project/17.0.3/source.json, modules/llvm-project/TODO.md, modules/llvm-project/metadata.json
Related issue: #206 
This PR adds LLVM (https://github.com/llvm/llvm-project) to BCR. While we could wait for LLVM to get Bzlmod support, I think adding it to BCR without waiting for that would be beneficial.
Optional dependencies (`zlib-ng`, `zstd`, `pfm`, `mpfr`) are currently disabled in the patches. I am not sure if the BCR module should have those enabled or not. I've done some experimenting locally and adding `zlib-ng` to BCR appears to be relatively straightforward. It is also possible to just use `zlib` that is already in BCR instead of `zlib-ng`, since `zlib-ng` has `zlib` compatibility enabled in the LLVM Bazel overlay. 
In terms of testing, `presubmit.yml` currently runs `@llvm-project//llvm/unittests:all`, i.e. the unit tests for the LLVM Core component. If this is not good …
=> Add llvm-project 17.0.3

.gitignore, BUILD, MODULE.bazel, metadata.schema.json, modules/rules_nixpkgs_core/metadata.json, tools/BUILD, tools/package.json, tools/pnpm-lock.yaml
This gives nice developer ergonomics in the editor, which can now provide autocomplete and error highlighting in metadata.json files. That requires a `$schema` attribute be added, which I'll do in a separate PR.
It also adds a layer of validation for things like datatypes and required fields in these json documents, using <https://ajv.js.org/>
Fixes #1148
=> feat: introduce JSON schema for metadata format

modules/debian_dependency_bazelizer/0.5.0/MODULE.bazel, modules/debian_dependency_bazelizer/0.5.0/presubmit.yml, modules/debian_dependency_bazelizer/0.5.0/source.json, modules/debian_dependency_bazelizer/metadata.json
This PR attempts to add the [debian_dependency_bazelizer](https://github.com/shabanzd/debian_dependency_bazelizer) to the BCR.
=> add debian dependency bazelizer to the bazel central registry

modules/yaml-cpp/0.8.0/MODULE.bazel, modules/yaml-cpp/0.8.0/patches/module_dot_bazel.patch, modules/yaml-cpp/0.8.0/presubmit.yml, modules/yaml-cpp/0.8.0/source.json, modules/yaml-cpp/metadata.json
This is currently:
* Patching bzlmod functionality in for the 0.8.0 release
* Pointing at a release asset on a fork. This is exactly the download tarball provided on the unstable URL's at https://github.com/jbeder/yaml-cpp/releases/tag/0.8.0
NB:
1. Bzlmod functionality went in upstream with https://github.com/jbeder/yaml-cpp/pull/1224. We should be able to drop the patches in future releases.
2. Discussing getting a stable release asset url in https://github.com/jbeder/yaml-cpp/issues/1229 so we don't have to use the fork.
=> Add yaml-cpp-0.8.0

modules/debian_dependency_bazelizer/metadata.json
fix https://github.com/bazelbuild/bazel-central-registry/issues/1254
=> add yanked_versions field for debian_dependency_bazelizer/metadata.json

tools/bcr_validation.py, tools/registry.py
Adds validation of `https` protocol source tarballs. Previously, we only supported `github` URI protocols.
Adds support for integrity algorithms other than `sha256`. Uses the same algorithm as the expected integrity for validation.
=> Validate HTTP respositories and non-sha256 integrity source tarballs

modules/glm/0.9.9.8.bcr.1/MODULE.bazel, modules/glm/0.9.9.8.bcr.1/patches/add_build_file.patch, modules/glm/0.9.9.8.bcr.1/patches/add_module_dot_bazel.patch, modules/glm/0.9.9.8.bcr.1/presubmit.yml, modules/glm/0.9.9.8.bcr.1/source.json, modules/glm/metadata.json
Fix include issue in glm.
Code such as 
```
#include <glm/vec3.hpp> // glm::vec3
#include <glm/vec4.hpp> // glm::vec4
#include <glm/mat4x4.hpp> // glm::mat4
#include <glm/ext/matrix_transform.hpp> // glm::translate, glm::rotate, glm::scale
#include <glm/ext/matrix_clip_space.hpp> // glm::perspective
#include <glm/ext/scalar_constants.hpp> // glm::pi
glm::mat4 camera(float Translate, glm::vec2 const& Rotate)
{
glm::mat4 Projection = glm::perspective(glm::pi<float>() * 0.25f, 4.0f / 3.0f, 0.1f, 100.f);
glm::mat4 View = glm::translate(glm::mat4(1.0f), glm::vec3(0.0f, 0.0f, -Translate));
View = glm::rotate(View, Rotate.y, glm::vec3(-1.0f, 0.0f, 0.0f));
View = glm::rotate(View, Rotate.x, glm::vec3(0.0f, 1.0f, 0.0f));
glm::mat4 Model = glm::scale(glm::mat4(1.0f), glm::vec3(0.5f));
return …
```
=> Fix include issue in glm

tools/registry.py
User agent added to module downloading to prevent failures on sites that check and 403 against requests that don't have a user agent. For example, https://developer.x-plane.com/wp-content/plugins/code-sample-generation/sample_templates/XPSDK401.zip
Also requested in CI/CD pipeline [here](https://github.com/bazelbuild/continuous-integration/pull/1851) to fix failing PR #1304
=> User agent added to module downloading

tools/registry.py
This was missing from https://github.com/bazelbuild/bazel-central-registry/pull/1373
=> Add missing entry for bazel version for test module

modules/toolchain_utils/1.0.0-beta.1/MODULE.bazel, modules/toolchain_utils/1.0.0-beta.1/presubmit.yml, modules/toolchain_utils/1.0.0-beta.1/source.json, modules/toolchain_utils/metadata.json
The upstream repository has moved from https://gitlab.arm.com/bazel/rules_toolchain to https://gitlab.arm.com/bazel/toolchain_utils. This keeps the naming consistency for the module. No renaming patches are needed anymore.
Moving to beta as we feel the module has the functionality to satisfy the constrainted scope of reducing the boilerplate to define a toolchain. Looking to get a stable once we have wider usage/testing.
=> feat: add `toolchain_utils@1.0.0-beta.1`

.github/workflows/bcr_pr_review_notifier.yml
Following up https://github.com/bazelbuild/continuous-integration/pull/1865
The next step is to auto-approve and merge PRs that passes presubmit and received module maintainer approval.
Working towards: https://github.com/bazelbuild/bazel-central-registry/issues/130
=> Add GitHub Action for automatically notifying module maintainers for PR review

.github/workflows/bcr_pr_review_notifier.yml
Allow the github secret to be passed for PRs from a forked repo. This is safe for the PR review notifier github action since we don't "check out, build, or run untrusted code from the pull request with this event."
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
=> Switch to pull_request_target event

modules/sophus/1.22.10/MODULE.bazel, modules/sophus/1.22.10/patches/add_build_file.patch, modules/sophus/1.22.10/patches/module_dot_bazel.patch, modules/sophus/1.22.10/presubmit.yml, modules/sophus/1.22.10/source.json, modules/sophus/metadata.json
This adds sophus (wrapper around Eigen providing Lie algebra) in version 1.22.10. 
Unfortunately again, there is no link in the desired format.
=> Add Sophus version 1.22.10

tools/print_all_src_urls.py, tools/registry.py
The documented method for listing artifacts to mirror is `bazel run //tools:print_all_src_urls`. This should not include yanked modules.
=> Exclude yanked modules from print all

modules/rules_python_gazelle_plugin/0.30.0/MODULE.bazel, modules/rules_python_gazelle_plugin/0.30.0/patches/module_dot_bazel_version.patch, modules/rules_python_gazelle_plugin/0.30.0/presubmit.yml, modules/rules_python_gazelle_plugin/0.30.0/source.json, modules/rules_python_gazelle_plugin/0.31.0/MODULE.bazel, modules/rules_python_gazelle_plugin/0.31.0/patches/module_dot_bazel_version.patch, modules/rules_python_gazelle_plugin/0.31.0/presubmit.yml, modules/rules_python_gazelle_plugin/0.31.0/source.json, modules/rules_python_gazelle_plugin/metadata.json
The BCR publishing app failed with the latest releases.
=> chore(rules_python_gazelle_plugin): add latest releases

modules/download_utils/1.0.0-beta.1/MODULE.bazel, modules/download_utils/1.0.0-beta.1/presubmit.yml, modules/download_utils/1.0.0-beta.1/source.json, modules/download_utils/metadata.json
This module implements repository rules that are helpful for downloading remote resources hermetically.
It currently has three repository rules for use in `MODULE.bazel`:
- `download_file`: download a single file
- `download_archive`: download a optionally compressed archive/tarball
- `download_deb`: download a debian package and unpack the contained data tarball
The rules add two novel things:
- Allow setting up (sym|hard)links after the artifact has been downloaded
- Run hermetic commands provided via `tools` and using `$(location )` replacement
Running for post download hermetic commands is a cruicial feature to make sure we depend on nothing in the host.
See the [readme](https://gitlab.arm.com/bazel/rules_download#getting-started) for example usage.
=> feat: add `download_utils@1.0.0-beta.1`

modules/rules_coreutils/1.0.0-alpha.7/MODULE.bazel, modules/rules_coreutils/1.0.0-alpha.7/presubmit.yml, modules/rules_coreutils/1.0.0-alpha.7/source.json, modules/rules_coreutils/metadata.json
Each core utility has it's own toolchain definition. These toolchains are backed by `uutils/coreutils` for all machines and statically compiled `busybox` on Linux machines.
It is important to register them as separate toolchains so rules can selectively decide which core utilities they depend on. It may be the case that a rule needs a specific feature for a particular core utility. This can be then handled with constraints and toolchain resolution for that particular core utility. The other benefit is that we can register the individual GNU core utilities to each toolchain, if one has a hermetic build of GNU coreutils. We will be upstreaming a separate PR for a module that provides some of those.
In general, rules should only rely on POSIX specified functionality of core utilities as it …
=> feat: add `rules_coreutils@1.0.0-alpha.7`

modules/rules_curl/1.0.0-alpha.6/MODULE.bazel, modules/rules_curl/1.0.0-alpha.6/presubmit.yml, modules/rules_curl/1.0.0-alpha.6/source.json, modules/rules_curl/metadata.json
This uses the pre-built `curl` executable provided by the `ape` BCR module to be hermetic.
It only implements *one* (!) rule: `curl_upload_file` at this time.
We expect to add more `curl` rules in the future, plus Windows support.
=> feat: add `rules_curl@1.0.0-alpha.6`

modules/sophus/1.22.10.bcr.1/MODULE.bazel, modules/sophus/1.22.10.bcr.1/patches/add_build_file.patch, modules/sophus/1.22.10.bcr.1/patches/module_dot_bazel.patch, modules/sophus/1.22.10.bcr.1/presubmit.yml, modules/sophus/1.22.10.bcr.1/source.json, modules/sophus/metadata.json
Modifications in this patch:
- Adds `includes = ["."],`
- Adds `"@fmt"` to `deps`
=> Add bcr.1 patch for Sophus 1.22.10

tools/bcr_validation.py
Prevent the step from hanging like https://buildkite.com/bazel/bcr-presubmit/builds/3750#018db8e0-114e-44c1-9757-3c600d83af3b
=> Fail the bcr validation step when the patch file doesn't apply

modules/liburing/2.5/patches/add_build_file.patch, modules/liburing/2.5/source.json
The default `./configure` invocation sets up the build for static linking (skipping any std library dependencies). That causes this module to be broken as is. It builds, but it can't be linked against as the built-in libc replacement functionality from src/nolibc.c is not compiled along. Fix this by following distributions like Debian and Fedora, and build the package against the supplied libc by specifying `--use-libc`.
It is unlikely that somebody already used this module as it was broken and only merged a few days ago.
=> liburing@2.5: build against (default) libc

modules/ape/1.0.0-alpha.2/MODULE.bazel, modules/ape/1.0.0-alpha.2/presubmit.yml, modules/ape/1.0.0-alpha.2/source.json, modules/ape/1.0.0-alpha.3/MODULE.bazel, modules/ape/1.0.0-alpha.3/presubmit.yml, modules/ape/1.0.0-alpha.3/source.json, modules/ape/metadata.json
Brings:
- `@ape//:diff`
- `@ape//:diff3`
- `@ape//:cmp`
- `@ape//:sdiff`
- `@ape//:patch`
Plus a patch for Windows support.
=> feat: add `ape@1.0.0-alpha.3`

modules/rules_diff/1.0.0-alpha.3/MODULE.bazel, modules/rules_diff/1.0.0-alpha.3/presubmit.yml, modules/rules_diff/1.0.0-alpha.3/source.json, modules/rules_diff/metadata.json
Brings two rules:
- `diff_file_test`
- `diff_directory_test`
Uses `diff` from `ape` so is hermetic and consistent across operating systems, even Windows.
Negates the non-hermetic-ness of `bazel_skylib#diff_test` that uses `diff` from the system.
A new module for `diff` related rules makes sense, in the future we may want to enable a three file comparison rule with `diff3`, byte-by-byte comparison with `cmp` or other possible differencing rules.
This module also exposes the hermetic toolchains for use in other modules:
- `@rules_diff//diff/toolchain/diff:type`
- `@rules_diff//diff/toolchain/diff3:type`
- `@rules_diff//diff/toolchain/sdiff:type`
- `@rules_diff//diff/toolchain/cmp:type`
At this time, we're in alpha as the rules need to be fleshed out and tested in more situations. For …
=> feat: add `rules_diff@1.0.0-alpha.3`

modules/rules_squashfs/1.0.0-alpha.1/MODULE.bazel, modules/rules_squashfs/1.0.0-alpha.1/presubmit.yml, modules/rules_squashfs/1.0.0-alpha.1/source.json, modules/rules_squashfs/metadata.json
Brings two main rules:
- `squashfs_tar`: build a SquashFS from a collection of tar archives
- `squashfs_unpack`: unpackages a SquashFS into a declared directory (`TreeArtifact`)
Provides toolchains for usage in other rules:
- `@rules_squashfs//squashfs/toolchain/mksquashfs`
- `@rules_squashfs//squashfs/toolchain/sqfstar`
- `@rules_squashfs//squashfs/toolchain/unsquashfs`
Is hermetic if the user provides a hermetic C/C++ toolchain, otherwise everything else is hermetically provided via `rules_coreutils`.
=> feat: add `rules_squashfs@1.0.0-alpha.1`

modules/ape/1.0.0-alpha.5/MODULE.bazel, modules/ape/1.0.0-alpha.5/presubmit.yml, modules/ape/1.0.0-alpha.5/source.json, modules/ape/metadata.json
Brings:
- Mirroring of upstream binaries into GitLab Package Registry
- Mirroring of `superconfigure` source code into GitLab `superconfigure/main`
- A new `ape_toolchain` macro for registering toolchains for the supported platforms
- Document that Apple silicon is currently unsupported in the ruleset in the `README.md`
Apple silicon support is being tracked in upstream [bazel/ape#1]
[bazel/ape#1]: https://gitlab.arm.com/bazel/ape/-/issues/1
=> feat: add `ape@1.0.0-beta.5`

.github/workflows/dismiss_approvals.yml, .github/workflows/notify_maintainers.yml, .github/workflows/review_prs.yml
The GitHub Action was implemented in https://github.com/bazelbuild/continuous-integration/pull/1887
This PR updated/created three workflows from the same GitHub Action, distinguished by `action-type`:
- `notify_maintainers`: Notify module maintainers whenever a PR is opened, updated or re-opened for the main branch with changes under "modules" directory.
- `dismiss_approvals`: Dismisses stale approvals whenever a PR is updated. We need this because the `Dismiss stale pull request approvals when new commits are pushed` branch protection from GitHub doesn't work for reviewers who is not a repo maintainer.
- `review_prs`: 
-  Review all open PRs every 10 mins. 
- Approve a PR if the latest change is approved by at least one module maintainer for each modified module. (Not yet) 
- Merge the …
=> Update GitHub Actions for automating PR review

modules/toolchains_llvm/1.0.0/MODULE.bazel, modules/toolchains_llvm/1.0.0/presubmit.yml, modules/toolchains_llvm/1.0.0/source.json, modules/toolchains_llvm/metadata.json
Release: https://github.com/bazel-contrib/toolchains_llvm/releases/tag/1.0.0
=> toolchains_llvm@1.0.0

.github/workflows/dismiss_approvals.yml, .github/workflows/notify_maintainers.yml, .github/workflows/review_prs.yml
- Getting the fix from https://github.com/bazelbuild/continuous-integration/pull/1920
- Also removed `paths` filter for `dismiss_approvals` workflow since it'll be a presubmit check for all PRs.
=> Update BCR review github actions

.github/workflows/review_prs.yml
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/1630
**Problem**
The scheduled workflow gets triggered on forked repos, and fail.
**Solution**
This filters the workflow steps so they won't run on forks. Not sure if there's a way so it won't be triggered at all.
=> Limit scheduled workflow to bazelbuild org

modules/io_opentracing_cpp/1.6.0/MODULE.bazel, modules/io_opentracing_cpp/1.6.0/patches/module_dot_bazel.patch, modules/io_opentracing_cpp/1.6.0/presubmit.yml, modules/io_opentracing_cpp/1.6.0/source.json, modules/io_opentracing_cpp/metadata.json
opentracing-cpp is archived but it is still used by several projects
Add opentracing-cpp v1.6.0
=> opentracing-cpp@1.6.0

modules/prometheus-cpp/1.2.4/MODULE.bazel, modules/prometheus-cpp/1.2.4/presubmit.yml, modules/prometheus-cpp/1.2.4/source.json, modules/prometheus-cpp/metadata.json
Release: https://github.com/jupp0r/prometheus-cpp/releases/tag/v1.2.4
=> prometheus-cpp@1.2.4

modules/tclap/1.2.5/MODULE.bazel, modules/tclap/1.2.5/patches/add_build_file.patch, modules/tclap/1.2.5/patches/module_dot_bazel.patch, modules/tclap/1.2.5/presubmit.yml, modules/tclap/1.2.5/source.json, modules/tclap/metadata.json
Release: https://github.com/mirror/tclap/releases/tag/v1.2.5
=> tclap@1.2.5

modules/rpmpack/0.6.0/MODULE.bazel, modules/rpmpack/0.6.0/presubmit.yml, modules/rpmpack/0.6.0/source.json, modules/rpmpack/metadata.json
Forked from https://github.com/bazelbuild/bazel-central-registry/pull/1484
=> Add rpmpack

modules/jsoncpp/1.9.5/MODULE.bazel, modules/jsoncpp/1.9.5/patches/build_dot_bazel.patch, modules/jsoncpp/1.9.5/patches/module_dot_bazel.patch, modules/jsoncpp/1.9.5/presubmit.yml, modules/jsoncpp/1.9.5/source.json, modules/jsoncpp/metadata.json
Release: https://github.com/open-source-parsers/jsoncpp/releases/tag/1.9.5
Used by:
* https://github.com/protocolbuffers/protobuf
=> jsoncpp@1.9.5

modules/cel-spec/0.14.0/MODULE.bazel, modules/cel-spec/0.14.0/patches/extensions_dot_bzl.patch, modules/cel-spec/0.14.0/patches/googleapis_ext_dot_blz.patch, modules/cel-spec/0.14.0/patches/module_dot_bazel.patch, modules/cel-spec/0.14.0/presubmit.yml, modules/cel-spec/0.14.0/source.json, modules/cel-spec/metadata.json
Release: https://github.com/google/cel-spec/releases/tag/v0.14.0
=> cel-spec@0.14.0

modules/hdrhistogram_c/0.11.2/MODULE.bazel, modules/hdrhistogram_c/0.11.2/patches/add_build_file.patch, modules/hdrhistogram_c/0.11.2/patches/module_dot_bazel.patch, modules/hdrhistogram_c/0.11.2/presubmit.yml, modules/hdrhistogram_c/0.11.2/source.json, modules/hdrhistogram_c/metadata.json
Release: https://github.com/HdrHistogram/HdrHistogram_c/releases/tag/0.11.2
Used by:
* https://github.com/envoyproxy/nighthawk
=> hdrhistogram_c@0.11.2

modules/msgpack-c/6.1.0/MODULE.bazel, modules/msgpack-c/6.1.0/patches/add_build_file.patch, modules/msgpack-c/6.1.0/patches/module_dot_bazel.patch, modules/msgpack-c/6.1.0/presubmit.yml, modules/msgpack-c/6.1.0/source.json, modules/msgpack-c/metadata.json
Release: https://github.com/msgpack/msgpack-c/releases/tag/cpp-6.1.0
=> msgpack-c@6.1.0

modules/skywalking-data-collect-protocol/9.7.0/MODULE.bazel, modules/skywalking-data-collect-protocol/9.7.0/patches/build_dot_bzl.patch, modules/skywalking-data-collect-protocol/9.7.0/patches/module_dot_bazel.patch, modules/skywalking-data-collect-protocol/9.7.0/presubmit.yml, modules/skywalking-data-collect-protocol/9.7.0/source.json, modules/skywalking-data-collect-protocol/metadata.json
Release: https://github.com/apache/skywalking-data-collect-protocol/releases/tag/v9.7.0
Used by:
=> skywalking-data-collect-protocol@9.7.0

modules/rules_jsonnet/0.5.0/MODULE.bazel, modules/rules_jsonnet/0.5.0/patches/add_examples_module_dot_bazel.patch, modules/rules_jsonnet/0.5.0/patches/add_module_dot_bazel.patch, modules/rules_jsonnet/0.5.0/presubmit.yml, modules/rules_jsonnet/0.5.0/source.json, modules/rules_jsonnet/metadata.json
Even though we haven't performed a release of rules_jsonnet in ages, it's still seeing some active use. Adding it to BCR is relatively easy, because it mostly just depends on jsonnet and jsonnet_go. The documentation parts depend on skydoc and rules_sass, but those aren't necessary to use the rules themselves.
=> Add rules_jsonnet

modules/snappy/1.1.8/MODULE.bazel, modules/snappy/1.1.8/patches/add_build_file.patch, modules/snappy/1.1.8/patches/module_dot_bazel.patch, modules/snappy/1.1.8/presubmit.yml, modules/snappy/1.1.8/source.json, modules/snappy/metadata.json
Release: https://github.com/google/snappy/releases/tag/1.1.8
Use by:
=> snappy@1.1.8

modules/rules_jsonnet/0.6.0/MODULE.bazel, modules/rules_jsonnet/0.6.0/presubmit.yml, modules/rules_jsonnet/0.6.0/source.json, modules/rules_jsonnet/metadata.json
This release no longer needs any local patching on the BCR side, as upstream includes a MODULE.bazel. Furthermore, this release addresses some known issues in the area of import path handling.
=> Add rules_jsonnet 0.6.0

modules/opencensus-proto/0.4.1/MODULE.bazel, modules/opencensus-proto/0.4.1/patches/build_dot_bazel.patch, modules/opencensus-proto/0.4.1/patches/module_dot_bazel.patch, modules/opencensus-proto/0.4.1/presubmit.yml, modules/opencensus-proto/0.4.1/source.json, modules/opencensus-proto/metadata.json
Release: https://github.com/census-instrumentation/opencensus-proto/releases/tag/v0.4.1
=> opencensus-proto@0.4.1

modules/libcircllhist/0.3.2/MODULE.bazel, modules/libcircllhist/0.3.2/patches/add_build_file.patch, modules/libcircllhist/0.3.2/patches/module_dot_bazel.patch, modules/libcircllhist/0.3.2/presubmit.yml, modules/libcircllhist/0.3.2/source.json, modules/libcircllhist/metadata.json
Release: https://github.com/openhistogram/libcircllhist/releases/tag/py-0.3.2
Used by:
=> libcircllhist@0.3.2

modules/nanobind_bazel/1.0.0/MODULE.bazel, modules/nanobind_bazel/1.0.0/presubmit.yml, modules/nanobind_bazel/1.0.0/source.json, modules/nanobind_bazel/metadata.json
Adds the nanobind_bazel repo, which is designed to create fast and compact Python bindings for C++ code with nanobind using Bazel.
This release gives the possibility of creating bindings with nanobind@v1 (currently: v1.9.2).
=> Add nanobind_bazel repo @v1

modules/argparse/3.0.0/MODULE.bazel, modules/argparse/3.0.0/patches/add_build_file.patch, modules/argparse/3.0.0/patches/module_dot_bazel.patch, modules/argparse/3.0.0/presubmit.yml, modules/argparse/3.0.0/source.json, modules/argparse/metadata.json
Adding the lightweight header only library [argparse](https://github.com/p-ranav/argparse) to the BCR
[ closes #1796 ]
=> Add argparse 3.0

modules/rules_fuzzing/0.5.1/MODULE.bazel, modules/rules_fuzzing/0.5.1/patches/module_dot_bazel.patch, modules/rules_fuzzing/0.5.1/presubmit.yml, modules/rules_fuzzing/0.5.1/source.json, modules/rules_fuzzing/metadata.json
Release: https://github.com/bazelbuild/rules_fuzzing/releases/tag/v0.5.1
Closes #1728
=> rules_fuzzing@0.5.1

modules/protobuf/26.0.bcr.1/MODULE.bazel, modules/protobuf/26.0.bcr.1/patches/0001-Add-MODULE.bazel.patch, modules/protobuf/26.0.bcr.1/patches/0002-relative-labels.patch, modules/protobuf/26.0.bcr.1/presubmit.yml, modules/protobuf/26.0.bcr.1/source.json, modules/protobuf/metadata.json
My 26.0 PR didn't have the repo_name attribute set which causes some
failures when built outside of this repo. This new version fixes that
and introduces a test for it in the presubmit config.
=> Fix protobuf release issue

modules/snappy/1.2.0/MODULE.bazel, modules/snappy/1.2.0/patches/build_dot_bazel.patch, modules/snappy/1.2.0/patches/module_dot_bazel.patch, modules/snappy/1.2.0/presubmit.yml, modules/snappy/1.2.0/source.json, modules/snappy/metadata.json
Release: https://github.com/google/snappy/releases/tag/1.2.0
Used by:
=> snappy@1.2.0

modules/antlr4-cpp-runtime/4.12.0/MODULE.bazel, modules/antlr4-cpp-runtime/4.12.0/patches/add_build_file.patch, modules/antlr4-cpp-runtime/4.12.0/patches/module_dot_bazel.patch, modules/antlr4-cpp-runtime/4.12.0/presubmit.yml, modules/antlr4-cpp-runtime/4.12.0/source.json, modules/antlr4-cpp-runtime/metadata.json
Release: https://github.com/antlr/antlr4/releases/tag/4.12.0
Used by:
* https://github.com/google/fuzztest
=> antlr4-cpp-runtime@4.12.0

modules/blake3/1.5.1/MODULE.bazel, modules/blake3/1.5.1/patches/add_build_file.patch, modules/blake3/1.5.1/patches/module_dot_bazel.patch, modules/blake3/1.5.1/presubmit.yml, modules/blake3/1.5.1/source.json, modules/blake3/metadata.json
Adds AVX-512 support for Linux x86_64 and tests more platforms compared to previous BCR versions.
=> Add blake3@1.5.1

modules/tree-sitter-bazel/0.22.5/MODULE.bazel, modules/tree-sitter-bazel/0.22.5/presubmit.yml, modules/tree-sitter-bazel/0.22.5/source.json, modules/tree-sitter-bazel/metadata.json
Add tree-sitter-bazel 0.22.5.
See [`tree-sitter-bazel`] and [`tree-sitter-bazel` v0.22.5].
I attempted to integrate Bazel into the original repo (see https://github.com/tree-sitter/tree-sitter/pull/3312),
but tree-sitter maintainers are not willing to do so, so I decided to create
my own repo for this purpose.
[`tree-sitter-bazel`]: https://github.com/zadlg/tree-sitter-bazel
[`tree-sitter-bazel` v0.22.5]: https://github.com/zadlg/tree-sitter-bazel/releases/tag/v0.22.5
=> Add tree-sitter-bazel 0.22.5.

modules/bzip2/1.0.8.bcr.1/MODULE.bazel, modules/bzip2/1.0.8.bcr.1/patches/add_build_file.patch, modules/bzip2/1.0.8.bcr.1/patches/module_dot_bazel.patch, modules/bzip2/1.0.8.bcr.1/presubmit.yml, modules/bzip2/1.0.8.bcr.1/source.json, modules/bzip2/1.0.8/presubmit.yml, modules/bzip2/metadata.json
it is expected that including bzip2 header included with angle brackets
```cpp
#include <bzlib.h>
```
without this change and more modules get added to the bcr there will be a lot of theses kinds of patches https://github.com/bazelbuild/bazel-central-registry/pull/1846/files#diff-3d0ec8cf226f2e480a40e8c6126f6ed456555c147c2f4e1b3557fd81f4db4ab5
unfortunately I think this breaks `libarchive` with clang/gcc due to the patch linked above
=> fix bzlib header include

modules/tree-sitter-c-bazel/0.20.7/MODULE.bazel, modules/tree-sitter-c-bazel/0.20.7/presubmit.yml, modules/tree-sitter-c-bazel/0.20.7/source.json, modules/tree-sitter-c-bazel/metadata.json
Add tree-sitter-c-bazel 0.20.7.
See [`tree-sitter-c-bazel`] and [`tree-sitter-c-bazel` v0.20.7].
This module allows Bazel users to use the [tree-sitter C parser] in their
Bazel project.
[`tree-sitter-c-bazel`]: https://github.com/zadlg/tree-sitter-c-bazel
[`tree-sitter-c-bazel` v0.20.7]:
https://github.com/zadlg/tree-sitter-c-bazel/releases/tag/v0.20.7
[tree-sitter C parser]: https://github.com/tree-sitter/tree-sitter-c
=> Add tree-sitter-c-bazel 0.20.7.

modules/xz/5.4.5.bcr.2/MODULE.bazel, modules/xz/5.4.5.bcr.2/patches/patch.diff, modules/xz/5.4.5.bcr.2/presubmit.yml, modules/xz/5.4.5.bcr.2/source.json, modules/xz/metadata.json
This fixes compatibility with incompatible_disallow_empty_glob
=> Add xz 5.4.5.bcr.2

modules/cel-spec/0.15.0/MODULE.bazel, modules/cel-spec/0.15.0/patches/cel-spec.patch, modules/cel-spec/0.15.0/patches/module_dot_bazel.patch, modules/cel-spec/0.15.0/presubmit.yml, modules/cel-spec/0.15.0/source.json, modules/cel-spec/metadata.json
Release: https://github.com/google/cel-spec/releases/tag/v0.15.0
Used by:
* https://github.com/cncf/xds
=> cel-spec@0.15.0

modules/boringssl/0.0.0-20240530-2db0eb3/MODULE.bazel, modules/boringssl/0.0.0-20240530-2db0eb3/patches/module_dot_bazel.patch, modules/boringssl/0.0.0-20240530-2db0eb3/presubmit.yml, modules/boringssl/0.0.0-20240530-2db0eb3/source.json, modules/boringssl/metadata.json
Release: https://github.com/google/boringssl/archive/1b6fe250a3b8b66aa4990a6ec59f20f5bf52df5d.tar.gz
Used by:
=> boringssl@0.0.0-20240530-2db0eb3

modules/highs/1.7.0/MODULE.bazel, modules/highs/1.7.0/patches/highs.patch, modules/highs/1.7.0/patches/module_dot_bazel.patch, modules/highs/1.7.0/presubmit.yml, modules/highs/1.7.0/source.json, modules/highs/metadata.json
Release: https://github.com/ERGO-Code/HiGHS/tree/v1.7.0
Used by:
* https://github.com/google/or-tools
=> highs@1.7.0

.github/dependabot.yml
This will allow to check weekly if there are updates for github-actions, npm and pip dependencies for the BCR. It will then create one PR for each dependency to update and will need to be validated individually.
This will help reduce the risk of vulnerabilities and technical debt.
=> enable dependabot for github-actions, npm and pip

modules/libprotobuf-mutator/1.3/MODULE.bazel, modules/libprotobuf-mutator/1.3/patches/add_build_file.patch, modules/libprotobuf-mutator/1.3/patches/module_dot_bazel.patch, modules/libprotobuf-mutator/1.3/presubmit.yml, modules/libprotobuf-mutator/1.3/source.json, modules/libprotobuf-mutator/metadata.json
Release: https://github.com/google/libprotobuf-mutator/releases/tag/v1.3
Used by:
* https://github.com/google/jwt_verify_lib
=> libprotobuf-mutator@1.3

modules/cpp-httplib/0.7.15/MODULE.bazel, modules/cpp-httplib/0.7.15/patches/add_build_file.patch, modules/cpp-httplib/0.7.15/patches/module_dot_bazel.patch, modules/cpp-httplib/0.7.15/presubmit.yml, modules/cpp-httplib/0.7.15/source.json, modules/cpp-httplib/metadata.json
Release: https://github.com/yhirose/cpp-httplib/releases/tag/v0.7.15
Used by:
* https://github.com/SkyAPM/cpp2sky
=> cpp-httplib@0.7.15

modules/rules_zstd/1.0.0-beta.1/MODULE.bazel, modules/rules_zstd/1.0.0-beta.1/presubmit.yml, modules/rules_zstd/1.0.0-beta.1/source.json, modules/rules_zstd/metadata.json
Uses `@ape//:zstd` to get hermetic compress/decompress:
```py
load("@rules_zstd//zstd/compress:defs.bzl", "zstd_compress")
load("@rules_zstd//zstd/decompress:defs.bzl", "zstd_decompress")
zstd_compress(
name = "compress",
src = "//fixture:hello-world.txt",
)
zstd_decompress(
name = "decompress",
src = ":compress",
)
```
=> feat: add `rules_zstd@1.0.0-beta.1`

modules/rules_fuzzing/0.5.2/MODULE.bazel, modules/rules_fuzzing/0.5.2/patches/module_dot_bazel.patch, modules/rules_fuzzing/0.5.2/presubmit.yml, modules/rules_fuzzing/0.5.2/source.json, modules/rules_fuzzing/metadata.json
Release: https://github.com/bazelbuild/rules_fuzzing/releases/tag/v0.5.2
Used by:
* https://github.com/google/jwt_verify_lib
=> rules_fuzzing@0.5.2

modules/rules_contest/0.9.0/MODULE.bazel, modules/rules_contest/0.9.0/presubmit.yml, modules/rules_contest/0.9.0/source.json, modules/rules_contest/metadata.json
`rules_contest` is a collection of Bazel rules for maintaining programming contest problems. `rules_contest` helps you automate tasks to prepare programming contest problems, such as:
- Building and testing datasets
- Building and testing reference solutions
- Building problem statements
- Building a progress tracker
Repository: https://github.com/nya3jp/rules_contest
=> Add rules_contest module

modules/grpc-httpjson-transcoding/0.0.0-20230607-ff41eb3/MODULE.bazel, modules/grpc-httpjson-transcoding/0.0.0-20230607-ff41eb3/patches/grpc-httpjson-transcoding.patch, modules/grpc-httpjson-transcoding/0.0.0-20230607-ff41eb3/patches/module_dot_bazel.patch, modules/grpc-httpjson-transcoding/0.0.0-20230607-ff41eb3/presubmit.yml, modules/grpc-httpjson-transcoding/0.0.0-20230607-ff41eb3/source.json, modules/grpc-httpjson-transcoding/metadata.json
Used by:
* https://github.com/grpc-ecosystem/proto-field-extraction
Related to https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/pull/97
=> grpc-httpjson-transcoding@0.0.0-20230607-ff41eb3

modules/rules_curl/1.0.0-alpha.7/MODULE.bazel, modules/rules_curl/1.0.0-alpha.7/presubmit.yml, modules/rules_curl/1.0.0-alpha.7/source.json, modules/rules_curl/metadata.json
Brings Apple Silicon and remote execution support.
=> feat: add `rules_curl@1.0.0-beta.7`

modules/rules_gzip/1.0.0-beta.1/MODULE.bazel, modules/rules_gzip/1.0.0-beta.1/presubmit.yml, modules/rules_gzip/1.0.0-beta.1/source.json, modules/rules_gzip/metadata.json
Brings simple compression and decompression rules:
```py
load("@rules_gzip//gzip/compress:defs.bzl", "gzip_compress")
load("@rules_gzip//gzip/decompress:defs.bzl", "gzip_decompress")
gzip_compress(
name = "compress",
src = "//fixture:hello-world.txt",
)
gzip_decompress(
name = "decompress",
src = ":compress",
)
```
=> feat: add `rules_gzip@1.0.0-beta.1`

modules/tinyformat/metadata.json
`homepage` attribute in metadata is incorrect - maybe a URL check in the CI could fetch such errors
=> tinyformat: Fix homepage attribute

modules/nanobind_bazel/2.0.0/MODULE.bazel, modules/nanobind_bazel/2.0.0/presubmit.yml, modules/nanobind_bazel/2.0.0/source.json, modules/nanobind_bazel/metadata.json
Provides capabilities for building Python bindings with Bazel using nanobind v2.0.0, which was released recently.
=> Add nanobind-bazel v2.0.0

modules/rules_directory/metadata.json
The code has been moved into bazel_skylib, so this is no longer being maintained.
=> Yank rules_directory.

modules/pybind11_protobuf/0.0.0-20240524-1d7a729/MODULE.bazel, modules/pybind11_protobuf/0.0.0-20240524-1d7a729/patches/module-dot-bazel-dev-dependency.patch, modules/pybind11_protobuf/0.0.0-20240524-1d7a729/patches/module-dot-bazel-pypi-hub-name.patch, modules/pybind11_protobuf/0.0.0-20240524-1d7a729/patches/module-dot-bazel-version.patch, modules/pybind11_protobuf/0.0.0-20240524-1d7a729/presubmit.yml, modules/pybind11_protobuf/0.0.0-20240524-1d7a729/source.json, modules/pybind11_protobuf/metadata.json
This is using the same patches as in #2031.
As there is no release process, we are using a version string including the commit sha like it's done for `boringssl` as well.
=> Add pybind11_protobuf

tools/BUILD
This allows execution via `bazel run`.
It is still possible to depend on it from other `py_binary()` like `:add_module`.
=> Mark bcr_validation as py_bianary()

modules/bazel_ci_rules/1.0.0/MODULE.bazel, modules/bazel_ci_rules/1.0.0/patches/module_dot_bazel.patch, modules/bazel_ci_rules/1.0.0/presubmit.yml, modules/bazel_ci_rules/1.0.0/source.json, modules/bazel_ci_rules/metadata.json
Release: https://github.com/bazelbuild/continuous-integration/releases/tag/rules-1.0.0
Used by:
* https://github.com/bazelbuild/rules_rust
=> bazel_ci_rules@1.0.0

modules/versor/0.1.0/MODULE.bazel, modules/versor/0.1.0/patches/add_build_file.patch, modules/versor/0.1.0/patches/module_dot_bazel.patch, modules/versor/0.1.0/presubmit.yml, modules/versor/0.1.0/source.json, modules/versor/metadata.json
The BUILD file of the old version assumed different file paths like `include`, `include/vsr` and `include/vsr/detail`. They are not present in the old version.
This PR updates to a new version of versor and yanks the old. There are no dependents yet. So, this should be safe.
=> Update to new versor version - old version unusable (yanked)

modules/rules_curl/1.0.0-alpha.8/MODULE.bazel, modules/rules_curl/1.0.0-alpha.8/presubmit.yml, modules/rules_curl/1.0.0-alpha.8/source.json, modules/rules_curl/metadata.json
Fixes runfile propagation to correct remote execution support.
=> feat: add `rules_curl@1.0.0-alpha.8`

modules/grpc-java/1.64.0/MODULE.bazel, modules/grpc-java/1.64.0/patches/module_dot_bazel_version.patch, modules/grpc-java/1.64.0/presubmit.yml, modules/grpc-java/1.64.0/source.json, modules/grpc-java/metadata.json
Add grpc-java@1.64.0
Less patching is necessary than v1.62.2 since Bzlmod support was integrated upstream (https://github.com/grpc/grpc-java/pull/11046).
=> grpc-java@1.64.0

modules/protobuf/26.0.bcr.2/MODULE.bazel, modules/protobuf/26.0.bcr.2/patches/0003-Update-rules_python-to-0.28.0.patch, modules/protobuf/26.0.bcr.2/patches/0004-Add-minimal-Python-support-to-MODULE.bazel.patch, modules/protobuf/26.0.bcr.2/patches/0005-Update-MODULE.bazel.patch, modules/protobuf/26.0.bcr.2/presubmit.yml, modules/protobuf/26.0.bcr.2/source.json, modules/protobuf/27.0.bcr.1/MODULE.bazel, modules/protobuf/27.0.bcr.1/patches/0001-Update-rules_python-to-0.28.0.patch, modules/protobuf/27.0.bcr.1/patches/0002-Add-minimal-Python-support-to-MODULE.bazel.patch, modules/protobuf/27.0.bcr.1/patches/0003-Update-MODULE.bazel.patch, modules/protobuf/27.0.bcr.1/presubmit.yml, modules/protobuf/27.0.bcr.1/source.json, modules/protobuf/27.1.bcr.1/MODULE.bazel, modules/protobuf/27.1.bcr.1/patches/0001-Update-rules_python-to-0.28.0.patch, modules/protobuf/27.1.bcr.1/patches/0002-Add-minimal-Python-support-to-MODULE.bazel.patch, modules/protobuf/27.1.bcr.1/patches/0003-Update-MODULE.bazel.patch, modules/protobuf/27.1.bcr.1/presubmit.yml, modules/protobuf/27.1.bcr.1/source.json, modules/protobuf/metadata.json
In Protobuf v25 Python support with Bzlmod broke with the introduction of `system_python`. This is a regression compared to previous versions.
This re-adds minimal Python support and adds a target to the presubmit check in order to avoid backsliding in the future.
This backports the following patches:
1. https://github.com/protocolbuffers/protobuf/commit/e1bf1f048e783578bcbdaa4572ce3c93908b6494
2. https://github.com/protocolbuffers/protobuf/commit/2eb4d69ed51c475a77ecd62742ef5064557b531f
=> Restore minimal Python support in Protobuf v25+

modules/rules_squashfs/1.0.0-alpha.2/presubmit.yml, modules/rules_squashfs/metadata.json
Bumps to remote execution compatible `toolchain_utils`.
=> feat: add `rules_squashfs@1.0.0-alpha.2`

tools/bcr_validation.py
Strips query strings from the source archive of a module to support modules hosted in GCS buckets.
=> Strip archive query strings in bcr_validation.py

tools/bcr_validation.py, tools/registry.py
Allow using the new overlay format (https://github.com/bazelbuild/bazel-central-registry/issues/1566)
Tested with https://github.com/bazelbuild/bazel-central-registry/pull/2240
This is an alternative to https://github.com/bazelbuild/bazel-central-registry/pull/2046 (which I hadn't seen previously :see_no_evil: )
=> Update bcr_validation.py to handle overlay files

.bazelignore
With the addition of overlays (#1566) it now can make sense to have BUILD and .bzl files inside the module version directories. However they don't necessarily make sense on their own. They are only supposed to work in the context of the source archive they overlay.
To prevent issues like not being able to load() from a //:def.bzl that does not exist in the registry repo, let's just .bazelignore the modules/ dir.
=> .bazelignore the modules/ dir.

modules/opentelemetry-cpp/1.14.2.bcr.1/MODULE.bazel, modules/opentelemetry-cpp/1.14.2.bcr.1/patches/0001-Add-MODULE.bazel.patch, modules/opentelemetry-cpp/1.14.2.bcr.1/presubmit.yml, modules/opentelemetry-cpp/1.14.2.bcr.1/source.json, modules/opentelemetry-cpp/metadata.json
- Remove `single_version_override()` which has no effect for foreign modules
- Remove transitive dependencies `upb` and `zlib`
=> Improve opentelemetry-cpp

tools/bcr_validation.py, tools/registry.py, tools/update_integrity_test.sh
To enable using the new overlay format (https://github.com/bazelbuild/bazel-central-registry/issues/1566) with the Bazel 7.2.1 fix that requires the overlay files to be in an `overlay` dir (https://github.com/bazelbuild/bazel/pull/22811)
Tested locally on https://github.com/bazelbuild/bazel-central-registry/pull/2240
=> Update BCR tooling to support 7.2.1 style overlay

tools/add_module.py, tools/bcr_validation.py, tools/calc_integrity.py, tools/migrate_to_bzlmod.py, tools/print_all_src_urls.py, tools/registry.py, tools/update_integrity.py, tools/verify_stable_archives.py, tools/version_test.py
Step 1 of https://github.com/bazelbuild/bazel-central-registry/discussions/2317.
This is `ruff format --line-length 120` plus some manual line reflowing in the second commit.
This changes the indent to 4 spaces in all files and line length to 120 cols.
After this lands we can take the hash of the squashed and rebased commit and add it to [.git-blame-ignore-revs](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)
=> Ruff format the BCR tooling

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, .ruff.toml
Step 2 of https://github.com/bazelbuild/bazel-central-registry/discussions/2317
Adds a GitHub Actions workflow that runs on each PR as well as on main.
Note that depending on repo settings an admin may have to configure this to become "required".
Uses https://github.com/pre-commit/action to run [pre-commit](https://pre-commit.com/).
pre-commit is configured to run the [official ruff-format hook](https://github.com/astral-sh/ruff-pre-commit)
I will add the lint hook in a follow-up PR as the lint is still failing.
Added a [ruff config file](https://docs.astral.sh/ruff/configuration/) as well to configure the line length to the same number the current formatting was done with.
The workflow already ran on this PR :) https://github.com/bazelbuild/bazel-central-registry/actions/runs/9717570688/j …
=> Add pre-commit workflow with ruff format

modules/wheelos_common_msgs/0.1.2/MODULE.bazel, modules/wheelos_common_msgs/0.1.2/presubmit.yml, modules/wheelos_common_msgs/0.1.2/source.json, modules/wheelos_common_msgs/metadata.json
Added the common_msg library, which mainly uses protobuf to define the message format of the autonomous driving system.
=> add wheelos_common_msgs

docs/README.md
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/2364
=> Update presubmit doc about requiring bazel version

modules/rules_python/metadata.json
I've been doing about half the maintenance on rules_python, including
initiating releases and following up on BCR PRs for it.
=> chore: add aignas to rules_python maintainer list

modules/websocketpp/0.8.2.bcr.1/MODULE.bazel, modules/websocketpp/0.8.2.bcr.1/patches/add_build_file.patch, modules/websocketpp/0.8.2.bcr.1/patches/module_dot_bazel.patch, modules/websocketpp/0.8.2.bcr.1/presubmit.yml, modules/websocketpp/0.8.2.bcr.1/source.json, modules/websocketpp/metadata.json
This change fixes the build on Mac OS X. According to the original CMakeLists.txt, "rt" is not linked on Mac OS X.
if (NOT APPLE)
set (WEBSOCKETPP_PLATFORM_LIBS pthread rt)
else()
set (WEBSOCKETPP_PLATFORM_LIBS pthread)
endif()
=> Fix "websocketpp" on Mac OS X.

modules/rules_nixpkgs_nodejs/0.12.0/MODULE.bazel, modules/rules_nixpkgs_nodejs/0.12.0/presubmit.yml, modules/rules_nixpkgs_nodejs/0.12.0/source.json, modules/rules_nixpkgs_nodejs/metadata.json
This is the first toolchain that we added a proper module extension for. More to come in the future.
Unfortunately, there's no testing module yet since this depends on the cc and java rules_nixpkgs modules which are still being worked on.
=> Add rules_nixpkgs_nodejs version 0.12.0

modules/foonathan_memory/0.7.3.bcr.1/MODULE.bazel, modules/foonathan_memory/0.7.3.bcr.1/patches/add_build_file.patch, modules/foonathan_memory/0.7.3.bcr.1/patches/module_dot_bazel.patch, modules/foonathan_memory/0.7.3.bcr.1/presubmit.yml, modules/foonathan_memory/0.7.3.bcr.1/source.json, modules/foonathan_memory/metadata.json
add "include/foonathan_memory" include path instead of "include"
In Fast-DDS which use below include path
```c++
#include <foonathan/memory/container.hpp>
#include <foonathan/memory/memory_pool.hpp>
```
If so, then we need to add `out_include_dir = "include/foonathan_memory",`, I don't know why bazel add `foonathan_memory` in external path?
- source path `include/foonathan/memory`
- bazel external path `include/foonathan_memory/foonathan/memory`
=> fix: fix foonathan_memory include path

modules/rules_platform/0.1.0/MODULE.bazel, modules/rules_platform/0.1.0/presubmit.yml, modules/rules_platform/0.1.0/source.json, modules/rules_platform/metadata.json
Created using `bazel run //tools:add_module`.
Fixes https://github.com/bazelbuild/rules_platform/issues/13
=> Add rules_platform

tools/verify_stable_archives.py
a source URL like "https://github.com/foo/bar" will just make the script crash.
=> Fix crash in verify_stable_archive if source URL has too few path segments

modules/osqp-cpp/metadata.json
I yanked the previous version by mistake. That broke our internal CI systems. As that version didn't have any security vulnerabilities, and just was broken, unyanking to recover our CI.
=> Unyank older version of osqp-cpp

tools/registry.py
The source of truth should be the `overlay` directory, not the JSON.
=> Automatically add overlay files to `sources.json`

tools/registry.py
These files can be created by editors and IDEs and aren't checked in to the BCR.
=> Do not include `MODULE.bazel.lock` files in overlay source list

modules/rules_tar/1.0.0-beta.1/MODULE.bazel, modules/rules_tar/1.0.0-beta.1/presubmit.yml, modules/rules_tar/1.0.0-beta.1/source.json, modules/rules_tar/metadata.json
```py
load("@rules_tar//tar/unpack:defs.bzl", "tar_unpack")
load("@rules_tar//tar/extract:defs.bzl", "tar_extract")
tar_unpack(
name = "unpack",
src = "some.tar.bz2",
)
tar_extract(
name = "extract",
src = "some.tar.zst",
outs = [
"a/specific/member.txt",
"another/member.txt",
]
)
```
Does not perform any ceation: `rules_pkg` for that (at least for the foreseeable future)
=> feat: add `rules_tar@1.0.0-beta.1`

modules/libmaxminddb/1.10.0/MODULE.bazel, modules/libmaxminddb/1.10.0/patches/add_build_file.patch, modules/libmaxminddb/1.10.0/patches/module_dot_bazel.patch, modules/libmaxminddb/1.10.0/presubmit.yml, modules/libmaxminddb/1.10.0/source.json, modules/libmaxminddb/metadata.json
PR for #2446
Release: https://github.com/maxmind/libmaxminddb/releases/tag/1.10.0
Used by:
=> libmaxminddb@1.10.0 (#2446)

modules/freertos/10.5.1.bcr.1/MODULE.bazel, modules/freertos/10.5.1.bcr.1/patches/bazel.patch, modules/freertos/10.5.1.bcr.1/presubmit.yml, modules/freertos/10.5.1.bcr.1/source.json, modules/freertos/metadata.json
Fix the patch file for FreeRTOS. The main difference is the change to BUILD.bazel shown in
https://github.com/bazelbuild/bazel-central-registry/pull/2481.
Tested this using `--registry=`.
=> freertos@10.5.1.bcr.1

modules/nanobind_bazel/2.1.0/MODULE.bazel, modules/nanobind_bazel/2.1.0/presubmit.yml, modules/nanobind_bazel/2.1.0/source.json, modules/nanobind_bazel/metadata.json
Contains new `nanobind_shared_library` and `nanobind_stubgen` rules to leverage nanobind v2's full capabilities.
Sorry about the `metadata.json` reformat, I think my editor screwed it up the last time - this one is taken exactly as it came out of `//tools:add_module`.
=> Add nanobind_bazel v2.1.0

modules/xz/5.4.5.bcr.4/MODULE.bazel, modules/xz/5.4.5.bcr.4/overlay/MODULE.bazel
After upgrading to `bazel_dep(name = "xz", version = "5.4.5.bcr.4")` (https://github.com/bazelbuild/bazel-central-registry/pull/2508) I get:
```
❯ bazel build @rules_boost//...
INFO: Invocation ID: f34d950c-698f-4f51-841f-15e1d26b36cb
ERROR: https:/raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/modules/xz/5.4.5.bcr.4/MODULE.bazel:1:1: name 'overlay' is not defined
ERROR: https:/raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/modules/xz/5.4.5.bcr.4/MODULE.bazel:1:9: name 'MODULE' is not defined (did you mean 'module'?)
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> xz@5.4.5.bcr.4: syntax error in MODULE.bazel file for xz@5.4.5.bcr.4
Computing main repo mapping:
```
... woops. Looks like the MODULE.bazel symlink …
=> Fix `xz 5.4.5.bcr.4`'s MODULE.bazel symlink

tools/bcr_validation.py
Testing `❯ bazel run //tools:bcr_validation -- --check xz` on this branch which includes the oopsie fixed in https://github.com/bazelbuild/bazel-central-registry/pull/2533:
```
(...)
BcrValidationResult.GOOD: The presubmit.yml file is valid.
BcrValidationResult.FAILED: modules/xz/5.4.5.bcr.4/MODULE.bazel must not be a symlink.
patching file tests/test_bcj_exact_size.c
patching file tests/test_check.c
patching file tests/test_lzip_decoder.c
patching file tests/test_memlimit.c
BcrValidationResult.FAILED: modules/xz/5.4.5.bcr.4/overlay/MODULE.bazel should be a symlink to `../MODULE.bazel`.
BcrValidationResult.GOOD: Checked in MODULE.bazel matches the sources.
(...)
```
There isn't currently a requirement for overlay/MODULE.bazel files to be ../MODULE.bazel symlinks but I think it would make …
=> Fail BcrValidator on incorrect overlay MODULE.bazel symlinks

modules/rules_android/0.5.1/MODULE.bazel, modules/rules_android/0.5.1/patches/module_dot_bazel_version.patch, modules/rules_android/0.5.1/presubmit.yml, modules/rules_android/0.5.1/source.json, modules/rules_android/metadata.json
Also fixes the version ordering in metadata so that more recent versions appear first in the BCR web UI.
=> Add rules_android v0.5.1

tools/bcr_validation.py
- Pathlib readlink() was introduced  since Python3.9.
- I guess validation ci runs on ubuntu2004, so python version is 3.8.
- use os readlink() for python3.8 compatibility
- This PR may fix validation to [PRs](https://github.com/bazelbuild/bazel-central-registry/pull/2578) which use overlay functionality.
=> fix: use os readlink for python 3.8 compatibility

modules/boost.detail/1.83.0/MODULE.bazel, modules/boost.detail/1.83.0/overlay/BUILD.bazel, modules/boost.detail/1.83.0/overlay/MODULE.bazel, modules/boost.detail/1.83.0/overlay/test/BUILD.bazel, modules/boost.detail/1.83.0/overlay/test/MODULE.bazel, modules/boost.detail/1.83.0/presubmit.yml, modules/boost.detail/1.83.0/source.json, modules/boost.detail/metadata.json
- add [boost.detail](http://boost.org/libs/detail)
=> feat: add boost.detail

modules/libarmgpuinfo/1.1.0+11140bec96/MODULE.bazel, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0001-chore-ignore-Bazel-build-symlinks.patch, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0002-build-add-bzlmod-files.patch, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0003-build-add-source-Bazel-build.patch, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0004-build-add-top-level-Bazel-aliases.patch, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0005-test-add-Bazel-build-tests.patch, modules/libarmgpuinfo/1.1.0+11140bec96/patches/0006-build-update-module-version.patch, modules/libarmgpuinfo/1.1.0+11140bec96/presubmit.yml, modules/libarmgpuinfo/1.1.0+11140bec96/source.json, modules/libarmgpuinfo/metadata.json
Uses an unstable archive at the moment. Will work with upstream to publish a stable archive for the next release.
=> feat: add `libarmgpuinfo@1.1.0+11140bec96`

modules/boost.describe/1.83.0/MODULE.bazel, modules/boost.describe/1.83.0/overlay/BUILD.bazel, modules/boost.describe/1.83.0/overlay/MODULE.bazel, modules/boost.describe/1.83.0/presubmit.yml, modules/boost.describe/1.83.0/source.json, modules/boost.describe/metadata.json, modules/boost.utility/1.83.0/MODULE.bazel, modules/boost.utility/1.83.0/overlay/BUILD.bazel, modules/boost.utility/1.83.0/overlay/MODULE.bazel, modules/boost.utility/1.83.0/presubmit.yml, modules/boost.utility/1.83.0/source.json, modules/boost.utility/metadata.json, modules/boost.variant2/1.83.0/MODULE.bazel, modules/boost.variant2/1.83.0/overlay/BUILD.bazel, modules/boost.variant2/1.83.0/overlay/MODULE.bazel, modules/boost.variant2/1.83.0/presubmit.yml, modules/boost.variant2/1.83.0/source.json, modules/boost.variant2/metadata.json
- add boost describe and utility
=> feat: add boost describe, utility, variant2

.bazelci/presubmit.yml, .bazelignore, modules/libcpuid/metadata.json, modules/marisa-trie/metadata.json
They were accidentally disabled by #2270
Also fix the two broken metadata files which were added during the lapse.
Alternative to #2691
=> fix: run schema validation tests again

modules/boost.exception/1.83.0/MODULE.bazel, modules/boost.exception/1.83.0/overlay/BUILD.bazel, modules/boost.exception/1.83.0/overlay/MODULE.bazel, modules/boost.exception/1.83.0/overlay/test/BUILD.bazel, modules/boost.exception/1.83.0/overlay/test/MODULE.bazel, modules/boost.exception/1.83.0/presubmit.yml, modules/boost.exception/1.83.0/source.json, modules/boost.exception/metadata.json
Boost.exeception@1.83.0
Could not add all test since boost.threads is currently missing, which is a dev dependency for the test. There for only two tests - but this is more testing that most of the boost modules have currently
=> Boost.exeception@1.83.0

modules/protobuf/28.0/MODULE.bazel, modules/protobuf/28.0/presubmit.yml, modules/protobuf/28.0/source.json, modules/protobuf/metadata.json
Release: https://github.com/protocolbuffers/protobuf/releases/tag/v28.0
*Manual BCR release **NOT** automated by [Publish to BCR](https://github.com/apps/publish-to-bcr) due to misconfiguration at time of v28.0 release.*
=> protobuf@28.0

modules/rules_jvm_external/metadata.json
The old domain redirects to the new one, so I think it's okay to leave it in place.
=> Add "github:bazel-contrib/rules_jvm_external" as a source repo to `rules_jvm_external`'s metadata

.github/workflows/dismiss_approvals.yml, .github/workflows/notify_maintainers.yml, .github/workflows/review_prs.yml, metadata.schema.json
See https://github.com/bazelbuild/continuous-integration/pull/2037. This PR updates the workflows to include that change, and the schema of metadata.json to add the new "do_not_notify" field.
cc @zhangskz
=> BCR PR reviewer: Add support for a "do_not_notify" field

modules/ncurses/6.4.20221231.bcr.1/MODULE.bazel, modules/ncurses/6.4.20221231.bcr.1/patches/add_bazel_tools.patch, modules/ncurses/6.4.20221231.bcr.1/patches/add_build_file.patch, modules/ncurses/6.4.20221231.bcr.1/patches/change_mode.patch, modules/ncurses/6.4.20221231.bcr.1/patches/module_dot_bazel.patch, modules/ncurses/6.4.20221231.bcr.1/presubmit.yml, modules/ncurses/6.4.20221231.bcr.1/source.json, modules/ncurses/metadata.json
* Remove unnecessary globs to make the module compatible with --incompatible_disallow_empty_glob.
I am a bit unsure about the naming convention of the version number here. Let me know if I should change anything.
=> ncurses@6.4.20221231.bcr.1

modules/boost.detail/1.83.0.bcr.1/MODULE.bazel, modules/boost.detail/1.83.0.bcr.1/overlay/BUILD.bazel, modules/boost.detail/1.83.0.bcr.1/overlay/MODULE.bazel, modules/boost.detail/1.83.0.bcr.1/overlay/test/BUILD.bazel, modules/boost.detail/1.83.0.bcr.1/overlay/test/MODULE.bazel, modules/boost.detail/1.83.0.bcr.1/presubmit.yml, modules/boost.detail/1.83.0.bcr.1/source.json, modules/boost.detail/metadata.json
- add missing textual hdrs
- boost.serialization needs this header
```
~/workspace/serialization tags/boost-1.77.0* 11s
❯ bazelisk build //... --process_headers_in_dependencies
INFO: Analyzed target //:boost.serialization (0 packages loaded, 0 targets configured).
ERROR: /Users/daisuke/workspace/serialization/BUILD.bazel:5:11: Compiling src/utf8_codecvt_facet.cpp failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //:boost.serialization) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 483 arguments skipped)
Use --sandbox_debug to see verbose messages from the …
```
=> fix: update boost.detail

modules/robin-map/1.3.0/MODULE.bazel, modules/robin-map/1.3.0/patches/add_build_file.patch, modules/robin-map/1.3.0/patches/module_dot_bazel.patch, modules/robin-map/1.3.0/presubmit.yml, modules/robin-map/1.3.0/source.json, modules/robin-map/metadata.json
Add the newest version of robin-map, which is required by nanobind@2.
This validation fails:
```
BcrValidationResult.FAILED: robin-map@1.3.0 is using an unstable source url: `https://github.com/Tessil/robin-map/archive/refs/tags/v1.3.0.tar.gz`.
You should use a release archive URL in the format of `https://github.com/<ORGANIZATION>/<REPO>/releases/download/<version>/<name>.tar.gz` to ensure the archive checksum stability.
See https://blog.bazel.build/2023/02/15/github-archive-checksum.html for more context.
```
I'm using the same URL format as the existing version, and robin-map doesn't seem to publish the sort of archive expected here. Compare e.g. the [rules_helm release assets](https://github.com/abrisco/rules_helm/releases/tag/0.4.0), which include a tarball artifact, to the …
=> robin-map@1.3.0

modules/nanobind/2.1.0/MODULE.bazel, modules/nanobind/2.1.0/patches/add_build_file.patch, modules/nanobind/2.1.0/patches/module_dot_bazel.patch, modules/nanobind/2.1.0/presubmit.yml, modules/nanobind/2.1.0/source.json, modules/nanobind/metadata.json
This builds on top of #2847 and adds nanobind@2.1.0.
It has the same issues as that PR as far as lacking a stable URL (nanobind only has tags, and no releases) and including changes to the presubmit config. Let me know if any changes are needed here.
Thanks!
=> nanobind@2.1.0

modules/protobuf-matchers/0.1.0/MODULE.bazel, modules/protobuf-matchers/0.1.0/presubmit.yml, modules/protobuf-matchers/0.1.0/source.json, modules/protobuf-matchers/metadata.json
No changes to functionality. Fixes a few missing includes.
=> Update protobuf-matchers to v0.1.0 to fix missing includes.

modules/sqlite3/metadata.json
I originally added this module in https://github.com/bazelbuild/bazel-central-registry/pull/641, so I figure I might as well set myself as the maintainer now that it's used enough to require some level of ownership.
Note: diff appears to be due to CRLF line endings accidentally introduced in <https://github.com/bazelbuild/bazel-central-registry/pull/2132>.
=> Set maintainers for sqlite3

tools/registry.py
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/3036
=> Use consistent line endings when writing JSON from tools

tools/migrate_to_bzlmod.py
Improvements:
- Polished some error messages.
- Find BCR modules by looking at the urls (`http_archive`) or git source repo (`git_repository`)
- Prefer to use `use_repo_rule` to introduce non-native deps
- Deal with invalid workspace resolved file caused by (`_action_listener`) (Fixes https://github.com/bazelbuild/bazel-central-registry/issues/2789)
=> Update migrate_to_bzlmod.py script

modules/protobuf/29.0-rc2.bcr.1/MODULE.bazel, modules/protobuf/29.0-rc2.bcr.1/patches/java_library_load.patch, modules/protobuf/29.0-rc2.bcr.1/presubmit.yml, modules/protobuf/29.0-rc2.bcr.1/source.json, modules/protobuf/metadata.json
Just adds a missing java_library load statement. This unblocks rule repositories supporting Bazel 8 who depend on protobuf.
=> Create protobuf 29.0-rc2.bcr.1

tools/bcr_validation.py
@meteorcloudy / @Wyverald this adds a check to avoid what happened in #3025 and which was resolved in #3047.
The `module#version` within the `MODULE.bazel` is validated to be what the module directory has.
=> Validate `MODULE.bazel` version equals module directory version

tools/bcr_validation.py
On mac, it's possible that:
```
$ ll /var
lrwxr-xr-x@ 1 root  wheel  11 Oct 15 13:22 /var@ -> private/var
```
If we only resolve overlay_dst but not source_root, it'll fail the check
=> Resolve source_root when checking overlay file path

modules/websocketpp/0.8.2.bcr.2/MODULE.bazel, modules/websocketpp/0.8.2.bcr.2/overlay/BUILD.bazel, modules/websocketpp/0.8.2.bcr.2/overlay/MODULE.bazel, modules/websocketpp/0.8.2.bcr.2/presubmit.yml, modules/websocketpp/0.8.2.bcr.2/source.json, modules/websocketpp/metadata.json
Closes #3045
---
Please note that with `boost.asio`, only Bazel 7.x is supported. With Bazel 6, I ran into [this error](https://buildkite.com/bazel/bcr-presubmit/builds/8436#0192dd4c-016a-4d23-8724-30cdc578f223): `Error computing the main repository mapping: in module dependency chain <root> -> websocketpp@0.8.2.bcr.2 -> boost.asio@1.83.0 -> boringssl@0.20240913.0 -> googletest@1.15.2: error executing MODULE.bazel file for googletest@1.15.2`. [The googletest version](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/googletest/1.15.2/presubmit.yml) only supports Bazel 7.x in CI, so I do the same.
=> Add websocket with configurable boost

tools/bcr_validation.py
=> fix(tools/bcr_validation): parse `MODULE.bazel` AST correctly

tools/README.md, tools/module_analyzer.py
- Fixed a bug that `direct_deps` wasn't actually returned.
- Added `--exclude-dev-deps` to support calculating without dev dependencies
- Added `--name-only` flag to only print out module names without scores.
- Filtered out potential modules parsed that actually don't exist in BCR. (bazel_dep with override)
=> Improve module_analyzer

docs/README.md
Because of https://github.com/bazelbuild/bazel/issues/20477#issuecomment-1883711827, it's not intuitive to just change BCR locally, and run using `--registry=file://` and therefore we need to do, `shutdown` and `--lockfile_mode=off` which isn't documented in BCR contribution docs.
=> Update README to include intructions for developing with BCR locally

.github/workflows/comment_bot.yml, .github/workflows/skip_check.yml, tools/bcr_validation.py
by adding a comment saying `@bazel-io skip_check unstable_url`.
=> Allow users to skip the URL stability check themselves

.github/workflows/skip_check.yml
Fix https://github.com/bazelbuild/bazel-central-registry/actions/runs/11701797060
=> Fix typo in skip_check.yml

modules/rules_perl/0.2.4/MODULE.bazel, modules/rules_perl/0.2.4/patches/module_dot_bazel_version.patch, modules/rules_perl/0.2.4/presubmit.yml, modules/rules_perl/0.2.4/source.json, modules/rules_perl/metadata.json
Add https://github.com/bazel-contrib/rules_perl/releases/tag/0.2.4
Also updates the source url, as rules_perl was moved from bazelbuild to bazel-contrib
Work towards https://github.com/bazelbuild/bazel-central-registry/issues/3056
Vis @skeletonkey
Needs `skip-url-stability-check` label
=> Add rules_perl@0.2.4

tools/bcr_validation.py
Adds workarounds in the BCR validation script to properly support `git_repository` sources as a step forwards toward https://github.com/bazelbuild/bazel/issues/23461.
=> Support git_repository sources in BCR

modules/jsonnet/0.20.0/presubmit.yml
jsonnet 0.20.0 doesn't build on macOS
=> Update presubmit.yml for jsonnet 0.20.0

modules/rules_python/0.39.0/MODULE.bazel, modules/rules_python/0.39.0/patches/module_dot_bazel_version.patch, modules/rules_python/0.39.0/presubmit.yml, modules/rules_python/0.39.0/source.json, modules/rules_python/metadata.json, modules/rules_python_gazelle_plugin/0.39.0/MODULE.bazel, modules/rules_python_gazelle_plugin/0.39.0/patches/module_dot_bazel_version.patch, modules/rules_python_gazelle_plugin/0.39.0/presubmit.yml, modules/rules_python_gazelle_plugin/0.39.0/source.json, modules/rules_python_gazelle_plugin/metadata.json
BCR config for rules_python and rules_python_gazelle_plugin 0.39.0 
This is https://github.com/bazelbuild/bazel-central-registry/pull/3171, but with
presubmit changes to remove Bazel 6 from the test matrix.
=> rules_python@0.39.0, rules_python_gazelle_plugin@0.39.0

modules/universal-robots-client-library/1.4.0.bcr.1/MODULE.bazel, modules/universal-robots-client-library/1.4.0.bcr.1/patches/add_build_file.patch, modules/universal-robots-client-library/1.4.0.bcr.1/patches/add_module_file.patch, modules/universal-robots-client-library/1.4.0.bcr.1/presubmit.yml, modules/universal-robots-client-library/1.4.0.bcr.1/source.json, modules/universal-robots-client-library/metadata.json
I forgot the visibility spec in https://github.com/bazelbuild/bazel-central-registry/pull/3229.
@bazel-io skip_check unstable_url upstream doesn't publish stable release.
=> Add default visibility public for universal_robots_client_library.

modules/eigen/4.0.0-20241125/MODULE.bazel, modules/eigen/4.0.0-20241125/patches/add_build_file.patch, modules/eigen/4.0.0-20241125/patches/module_dot_bazel.patch, modules/eigen/4.0.0-20241125/presubmit.yml, modules/eigen/4.0.0-20241125/source.json, modules/eigen/metadata.json
Version 3.4.0 is 3 years old. This version pulls
in all the functionality added throughout the last years.
=> Add eigen version from main.

modules/libjpeg_turbo/2.1.4/MODULE.bazel, modules/libjpeg_turbo/2.1.4/patches/add_build_file.patch, modules/libjpeg_turbo/2.1.4/patches/add_module_dot_bazel.patch, modules/libjpeg_turbo/2.1.4/presubmit.yml, modules/libjpeg_turbo/2.1.4/source.json, modules/libjpeg_turbo/metadata.json
Add libjpeg_turbo@2.1.4.
Used this successfully on Windows, Ubuntu, and macOS for the past year - in contrast to the newer version 2.1.91 this one uses also [NASM](https://www.nasm.us/) to build some (hopefully optimized) assembly files.
Copy with some modifications from my personal Bazel registry:
https://github.com/Vertexwahn/bazel-registry/tree/main/modules/libjpeg_turbo
=> libjpeg_turbo@2.1.4

modules/rules_pkl/metadata.json
Leaving Phil as the first maintainer, and then ordering the remaining names by their surnames.
=> [rules_pkl] Add Kushal and Romain as maintainers

modules/libxml2/2.13.5/MODULE.bazel, modules/libxml2/2.13.5/patches/add_build_file.patch, modules/libxml2/2.13.5/patches/module_dot_bazel.patch, modules/libxml2/2.13.5/presubmit.yml, modules/libxml2/2.13.5/source.json, modules/libxml2/metadata.json
Closes #2511
Release: https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.5
Previous stale PR #282
=> libxml2@2.13.5 (#2511)

modules/rules_android/0.6.0-alpha1.bcr.1/MODULE.bazel, modules/rules_android/0.6.0-alpha1.bcr.1/patches/bcr.patch, modules/rules_android/0.6.0-alpha1.bcr.1/presubmit.yml, modules/rules_android/0.6.0-alpha1.bcr.1/source.json, modules/rules_android/metadata.json
Fixes the issue with 0.6.0-alpha1, where the lack of a newline at the end of README.md caused bzlmod repo patching to fail.
See https://github.com/bazelbuild/bazel/issues/17376
=> rules_android 0.6.0-alpha1.bcr.1

modules/swig/4.3.0/MODULE.bazel, modules/swig/4.3.0/patches/add_build.patch, modules/swig/4.3.0/patches/add_parser_c.patch, modules/swig/4.3.0/patches/add_parser_h.patch, modules/swig/4.3.0/patches/add_swigconfig_h.patch, modules/swig/4.3.0/patches/add_swigwarn_swg.patch, modules/swig/4.3.0/patches/configure.patch, modules/swig/4.3.0/patches/module_dot_bazel.patch, modules/swig/4.3.0/presubmit.yml, modules/swig/4.3.0/source.json, modules/swig/metadata.json
This PR has been tested with a git override in OR-Tools.
bump swig to 4.3.0
remove 'path' field in the filegroup BUILD entries
Split configure.patch into one patch per file
Add presubmit test for bazel 8
Please add: 
=> add swig 4.3.0; fix invalid filegroup field in BUILD file, support bazel 8.0

modules/jsonnet/0.20.0.bcr.1/MODULE.bazel, modules/jsonnet/0.20.0.bcr.1/patches/module_dot_bazel.patch, modules/jsonnet/0.20.0.bcr.1/presubmit.yml, modules/jsonnet/0.20.0.bcr.1/source.json, modules/jsonnet/metadata.json
The previous patch used a custom toolchain from [`@bazel_tools`](https://github.com/google/jsonnet/blob/913281d203578bb394995bacc792f2576371e06c/platform_defs/BUILD#L1) which is incompatible with Bazel 8
=> Use hermetic Python from rules_python for jsonnet

modules/rules_helm/0.6.0.bcr.1/MODULE.bazel, modules/rules_helm/0.6.0.bcr.1/patches/deps-rules-oci.patch, modules/rules_helm/0.6.0.bcr.1/patches/version.patch, modules/rules_helm/0.6.0.bcr.1/presubmit.yml, modules/rules_helm/0.6.0.bcr.1/source.json, modules/rules_helm/metadata.json
rules_oci is loaded by a non dev_dependencies module extension and therefore musn't be a dev_dependency itself.
Proposed an upstream fix for future versions in https://github.com/abrisco/rules_helm/pull/107.
=> Fix rules_helm dependencies

modules/opencensus-cpp/0.0.0-20230502-50eb5de/MODULE.bazel, modules/opencensus-cpp/0.0.0-20230502-50eb5de/patches/module_dot_bazel.patch, modules/opencensus-cpp/0.0.0-20230502-50eb5de/presubmit.yml, modules/opencensus-cpp/0.0.0-20230502-50eb5de/source.json, modules/opencensus-cpp/metadata.json
Even though this repository is already archived, there are still many consumers which fall back to module extensions. Uploading this to allow at least using a module dependency until consumers are migrated.
Using the latest commit as it contains several unreleased fixes (for example adding compatibility for newer abseil-cpp versions).
=> Add opencensus-cpp

docs/README.md
2 Open questions:
1. Coming from [this comment](https://github.com/bazelbuild/bazel-central-registry/pull/3453#discussion_r1890437999): Is there an automated validation check from the versioning pattern?
2. Is there a version pattern for projects that have not a single tagged release? Should I use the date pattern here?
=> docs: Document skip URL check

modules/iceoryx/2.95.3/MODULE.bazel, modules/iceoryx/2.95.3/overlay/MODULE.bazel, modules/iceoryx/2.95.3/presubmit.yml, modules/iceoryx/2.95.3/source.json, modules/iceoryx/metadata.json
- add [iceoryx](https://github.com/eclipse-iceoryx/iceoryx)
=> feat: add iceoryx

modules/cmake_configure_file/0.1.1/MODULE.bazel, modules/cmake_configure_file/0.1.1/presubmit.yml, modules/cmake_configure_file/0.1.1/source.json, modules/cmake_configure_file/metadata.json, modules/geographiclib/2.4.0.bcr.1/MODULE.bazel, modules/geographiclib/2.4.0.bcr.1/overlay/BUILD.bazel, modules/geographiclib/2.4.0.bcr.1/overlay/MODULE.bazel, modules/geographiclib/2.4.0.bcr.1/presubmit.yml, modules/geographiclib/2.4.0.bcr.1/source.json, modules/geographiclib/metadata.json
=> fix: remove empty glob from geographiclib

modules/rules_spring/2.6.0/MODULE.bazel, modules/rules_spring/2.6.0/presubmit.yml, modules/rules_spring/2.6.0/source.json, modules/rules_spring/metadata.json
Adding rules_spring to the BCR.
Cleaned up the python config since the last submission.
=> rules_spring 2.6.0

modules/jsoncons/1.0.0/MODULE.bazel, modules/jsoncons/1.0.0/overlay/BUILD.bazel, modules/jsoncons/1.0.0/overlay/MODULE.bazel, modules/jsoncons/1.0.0/presubmit.yml, modules/jsoncons/1.0.0/source.json, modules/jsoncons/metadata.json
=> jsoncons@1.0.0

modules/soplex/7.1.2.bcr.1/MODULE.bazel, modules/soplex/7.1.2.bcr.1/overlay/BUILD.bazel, modules/soplex/7.1.2.bcr.1/overlay/MODULE.bazel, modules/soplex/7.1.2.bcr.1/patches/add_config_dot_h.patch, modules/soplex/7.1.2.bcr.1/patches/add_git_hash_dot_cpp.patch, modules/soplex/7.1.2.bcr.1/patches/fmt_dot_hpp.patch, modules/soplex/7.1.2.bcr.1/patches/spxfileio_dot_h.patch, modules/soplex/7.1.2.bcr.1/presubmit.yml, modules/soplex/7.1.2.bcr.1/source.json, modules/soplex/metadata.json
Fix soplex:
- move zstr as a deps as it leaks on the client build file otherwise (not an issue as it is a header only library)
- add missing multiprecision option
- add cc_binary rule to build the soplex binary (and verify the compilation went well)
=> fix soplex deps; add boost dependency; add cc_binary target

modules/rules_docker_compose_test/1.1.0/MODULE.bazel, modules/rules_docker_compose_test/1.1.0/presubmit.yml, modules/rules_docker_compose_test/1.1.0/source.json, modules/rules_docker_compose_test/metadata.json
Adding https://github.com/salesforce/rules_docker_compose_test.
=> add rules_docker_compose_test 1.1.0 to bazel-central-registry

.github/workflows/dismiss_approvals.yml, .github/workflows/generate_module_diff.yml, .github/workflows/notify_maintainers.yml, .github/workflows/review_prs.yml, .github/workflows/skip_check.yml
This action will diff new module versions in a BCR PR against its previous version. Making it much easier to review changes between module versions.
Test run: https://github.com/meteorcloudy/bazel-central-registry/actions/runs/12805364325/job/35765475520
=> Add generate module diff check

modules/rules_cc/metadata.json
Yanking a module version with no higher version available is highly disruptive as users can't rely on `bazel_dep` to fix the breakage, but have to resort to `single_version_override`.
Related to #3596
=> Unyank `rules_cc@0.1.0`

modules/engflowapis-go/2025.01.17-16.55.05/MODULE.bazel, modules/engflowapis-go/2025.01.17-16.55.05/presubmit.yml, modules/engflowapis-go/2025.01.17-16.55.05/source.json, modules/engflowapis-go/metadata.json, modules/engflowapis-java/2025.01.17-16.55.05/MODULE.bazel, modules/engflowapis-java/2025.01.17-16.55.05/presubmit.yml, modules/engflowapis-java/2025.01.17-16.55.05/source.json, modules/engflowapis/2025.01.17-16.55.05/MODULE.bazel, modules/engflowapis/2025.01.17-16.55.05/presubmit.yml, modules/engflowapis/2025.01.17-16.55.05/source.json, modules/engflowapis/metadata.json
This change updates `@engflowapis` and `@engflowapis-java` and adds `@engflowapis-go`.
Also, updates maintainers.
=> Publish `@engflowapis` `2025.01.17-16.55.05` (+ language bindings)

docs/README.md, metadata.schema.json, modules/io_opentracing_cpp/metadata.json, modules/rules_directory/metadata.json, tools/bcr_validation.py
- The latest version of a module should not be yanked.
- Unless the module is marked as deprecated via `"deprecated": "<reason>"`.
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/3604
=> Add check for yanked version

tools/BUILD, tools/bcr_validation.py
A source archive URL in the form of `https//github.com/OWNER/REPO/archive/<commit>.zip` isn't guaranteed to point source code from the original repository because `<commit>` can be a fork and GitHub will happily generate the source archive under this URL. An attacker can use such an URL to confuse BCR maintainer that the URL is from the source repo.
This PR adds a check to make sure the commit is actually coming from the original repository via a GitHub API (unofficial).
=> bcr_validation: check if a commit/reference in the github url is from the original repo

modules/asio-grpc/2.6.0/MODULE.bazel, modules/asio-grpc/2.6.0/overlay/BUILD.bazel, modules/asio-grpc/2.6.0/overlay/MODULE.bazel, modules/asio-grpc/2.6.0/patches/bazel_test_fixes.patch, modules/asio-grpc/2.6.0/patches/disable_gpr_assert.patch, modules/asio-grpc/2.6.0/patches/include_asio_error.patch, modules/asio-grpc/2.6.0/presubmit.yml, modules/asio-grpc/2.6.0/source.json, modules/asio-grpc/metadata.json
This is possible to add now that the issues with rules_cc and protobuf have been resolved. Previously you could not have both boost and grpc as dependencies because boost would pull rules_cc up to 0.1.0 and grpc has a transitive dep (protoc-gen-validate) that was not comptible with rules_cc 0.1.0.
=> Add asio-grpc@2.6.0

tools/setup_presubmit_repos.py
Otherwise, the script would consider there is no task specified for the module..
=> setup_presubmit_repos.py: use task_id as name in case task name isn't available

tools/print_all_src_urls.py
Check "url" or "urls" attribute actually exists since BCR also supports `git_repository` now in source.json
=> Fix print_all_src_urls.py

modules/bzip2/1.0.8.bcr.2/MODULE.bazel, modules/bzip2/1.0.8.bcr.2/patches/add_build_file.patch, modules/bzip2/1.0.8.bcr.2/patches/module_dot_bazel.patch, modules/bzip2/1.0.8.bcr.2/presubmit.yml, modules/bzip2/1.0.8.bcr.2/source.json, modules/bzip2/metadata.json
The sourceware HTTP repo is pretty consistently giving us 500s in our
CI environment. Use a mirror to prevent flakes.
=> bzip2: use mirror archive

.gitignore
This folder is generated by `//tools:setup_presubmit_repos` when doing local testing, so we should ignore it.
=> Git ignored `temp_test_repos`.

MODULE.bazel
Avoid the root user error in Docker container
=> Set `ignore_root_user_error = True` for python toolchain

modules/xacro/2.0.12/MODULE.bazel, modules/xacro/2.0.12/patches/module_dot_bazel.patch, modules/xacro/2.0.12/presubmit.yml, modules/xacro/2.0.12/source.json, modules/xacro/metadata.json
Adds a module for https://github.com/ros/xacro, a tool to expand xacro files (xml macros).
Upstream accepted patches for bzlmod support as well as rules for expanding these macro files at build-time with bazel.
=> Add new module xacro

MODULE.bazel
Getting https://github.com/bazelbuild/continuous-integration/commit/3c2bc5dc463e7d35b0d14faca4e1aa0b2c04bfa9
=> Bump Bazel CI commit for setup_presubmit_repos

MODULE.bazel
Fixes `//tools:setup_presubmit_repos`.
Bumped in https://github.com/bazelbuild/bazel-central-registry/pull/3848, but forgot to update integrity.
=> Updated integrity of `setup_presubmit_repos` files after `BAZEL_CI_COMMIT` was bumped.

modules/azure-core-cpp/1.14.1.bcr.1/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.1/overlay/BUILD.bazel, modules/azure-core-cpp/1.14.1.bcr.1/overlay/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.1/overlay/test/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.1/presubmit.yml, modules/azure-core-cpp/1.14.1.bcr.1/source.json, modules/azure-core-cpp/metadata.json
*   Updated `azure_core_cpp_test` to enable some more tests.
*   Added a presubmit for Windows.
=> Updated `azure-core-cpp` `1.14.1` to only add OpenSSL as a dep if not on Windows.

modules/helly25_mbo/0.4.0-rc.1/MODULE.bazel, modules/helly25_mbo/0.4.0-rc.1/patches/bazelmod.patch, modules/helly25_mbo/0.4.0-rc.1/patches/bcr.bazelmod-version.patch, modules/helly25_mbo/0.4.0-rc.1/presubmit.yml, modules/helly25_mbo/0.4.0-rc.1/source.json, modules/helly25_mbo/metadata.json
Add helly25_mbo@0.4.0-rc.1
Version 0.3.0 failed in https://github.com/bazelbuild/bazel-central-registry/pull/3813
This version addresses the fundamental problem of the toolchains_llvm dependency in two ways:
* It is used as a dev dependency only
* That dependency occurs in includes which are commented out through a patch for the bcr release
* The `presubmit.yml`:
* tests are limited (only actual binaries that do not use clang-format)
* though technically the project should now work without that as well
* windows platform is not present (some code & tooling won't work there)
* c++20 compilation flag is set
=> Add helly25_mbo@0.4.0-rc.1

modules/libarmgpuinfo/1.2.0/MODULE.bazel, modules/libarmgpuinfo/1.2.0/patches/0001-chore-ignore-Bazel-build-symlinks.patch, modules/libarmgpuinfo/1.2.0/patches/0002-build-add-bzlmod-files.patch, modules/libarmgpuinfo/1.2.0/patches/0003-build-add-source-Bazel-build.patch, modules/libarmgpuinfo/1.2.0/patches/0004-build-add-top-level-Bazel-aliases.patch, modules/libarmgpuinfo/1.2.0/patches/0005-test-add-Bazel-build-tests.patch, modules/libarmgpuinfo/1.2.0/patches/0006-build-update-module-version.patch, modules/libarmgpuinfo/1.2.0/presubmit.yml, modules/libarmgpuinfo/1.2.0/source.json, modules/libarmgpuinfo/metadata.json
Yank `1.1.0+11140bec96` as the version is not parsed by `bazel_dep`.
=> Add `libarmgpuinfo@1.2.0`

docs/README.md
since the script will depend on certain Python libraries like `requests`
being installed.
=> docs: suggest bazel target for running bcr_validation locally

modules/llvm-project/17.0.3.bcr.2/MODULE.bazel, modules/llvm-project/17.0.3.bcr.2/patches/0001-Add-Bazel-files-to-.gitignore.patch, modules/llvm-project/17.0.3.bcr.2/patches/0002-Add-LLVM-Bazel-overlay-files.patch, modules/llvm-project/17.0.3.bcr.2/patches/0003-Add-MODULE.bazel.patch, modules/llvm-project/17.0.3.bcr.2/patches/0004-Add-BUILD.bazel.patch, modules/llvm-project/17.0.3.bcr.2/patches/0005-Add-Bazel-LLVM-targets.patch, modules/llvm-project/17.0.3.bcr.2/patches/0006-Add-LLVM-version-vars.patch, modules/llvm-project/17.0.3.bcr.2/patches/0007-Guard-against-empty-workspace-root.patch, modules/llvm-project/17.0.3.bcr.2/patches/0008-Correct-builtin-headers-prefix.patch, modules/llvm-project/17.0.3.bcr.2/patches/0009-Fix-an-operator-overload-for-GCC-8.3.patch, modules/llvm-project/17.0.3.bcr.2/patches/0010-Use-TEST_TMPDIR-on-Unix-when-it-is-set.patch, modules/llvm-project/17.0.3.bcr.2/patches/0011-Use-Windows-assembly-files-for-BLAKE3-on-Windows.patch, modules/llvm-project/17.0.3.bcr.2/patches/0012-Add-scope-resolution-operators-for-MSVC-2019.patch, modules/llvm-project/17.0.3.bcr.2/patches/0013-Disable-zlib-zstd-mpfr-and-pfm.patch, modules/llvm-project/17.0.3.bcr.2/patches/0014-Incompatible-Disable-Empty-Glob.patch, modules/llvm-project/17.0.3.bcr.2/patches/0015-incompatible_autoload_externally.patch, modules/llvm-project/17.0.3.bcr.2/presubmit.yml, modules/llvm-project/17.0.3.bcr.2/source.json, modules/llvm-project/metadata.json
This change updates bzlmod bazel_deps and updates load statements using `buildifier` to ensure symbols such as `cc_library` and `py_library` are loaded from external modules and don't use the `native` package. This should address any errors in consumers which use [`--incompatible_autoload_externally=`](https://github.com/bazelbuild/bazel/issues/23043) (such as `rules_rust_bindgen`).
=> llvm-project@17.0.3.bcr.2

tools/attestations.py
Prefixes need to be included if a GitHub release contains multiple BCR modules.
Progress towards https://github.com/bazelbuild/bazel-central-registry/issues/3829.
=> Allow attestation URLs with file prefixes.

modules/librdkafka/2.8.0.bcr.1/MODULE.bazel, modules/librdkafka/2.8.0.bcr.1/overlay/BUILD.bazel, modules/librdkafka/2.8.0.bcr.1/overlay/MODULE.bazel, modules/librdkafka/2.8.0.bcr.1/overlay/test/MODULE.bazel, modules/librdkafka/2.8.0.bcr.1/patches/src-cpp_rdkafkacpp_int.h.patch, modules/librdkafka/2.8.0.bcr.1/patches/src_rd.h.patch, modules/librdkafka/2.8.0.bcr.1/patches/src_tinycthread.h.patch, modules/librdkafka/2.8.0.bcr.1/patches/tests_testcpp.h.patch, modules/librdkafka/2.8.0.bcr.1/presubmit.yml, modules/librdkafka/2.8.0.bcr.1/source.json, modules/librdkafka/metadata.json
Fixed `librdkafka` so it can be included as either:
```c
#include <rdkafka.h>
```
or
```c
#include <librdkafka/rdkafka.h>
```
In order to do this I needed to add `strip_include_prefix` and add an `include_prefix` to the `librdkafka` lib. Also needed to split the lib into a `cpp` version and a `c` version due to it having two different source directories.
=> Fixed how `librdkafka` files can be included in other C/C++ files.

modules/ng-log/0.8.0-rc1/MODULE.bazel, modules/ng-log/0.8.0-rc1/patches/module_dot_bazel.patch, modules/ng-log/0.8.0-rc1/presubmit.yml, modules/ng-log/0.8.0-rc1/source.json, modules/ng-log/metadata.json
This is the new name for "glog", as that project is no longer maintained
by Google.
=> Add ng-log 0.8.0-rc1

modules/patchelf/0.16.1/MODULE.bazel, modules/patchelf/0.16.1/patches/0001-Add-MODULE.bazel.patch, modules/patchelf/0.16.1/patches/0002-Add-BUILD.bazel.patch, modules/patchelf/0.16.1/presubmit.yml, modules/patchelf/0.16.1/source.json, modules/patchelf/0.18.0/presubmit.yml, modules/patchelf/metadata.json
The 0.18.0 version has a known bug. https://github.com/NixOS/patchelf/issues/492. Until the fixed version is released, 0.16.1 is a working alternative.
=> add patchelf 0.16.1

modules/exprtk/0.0.3.bcr.1/MODULE.bazel, modules/exprtk/0.0.3.bcr.1/overlay/BUILD.bazel, modules/exprtk/0.0.3.bcr.1/overlay/MODULE.bazel, modules/exprtk/0.0.3.bcr.1/presubmit.yml, modules/exprtk/0.0.3.bcr.1/source.json, modules/exprtk/metadata.json, modules/fasttext/0.10.0-bcr.20240313-1142dc4.bcr.1/MODULE.bazel, modules/fasttext/0.10.0-bcr.20240313-1142dc4.bcr.1/overlay/BUILD.bazel, modules/fasttext/0.10.0-bcr.20240313-1142dc4.bcr.1/overlay/MODULE.bazel, modules/fasttext/0.10.0-bcr.20240313-1142dc4.bcr.1/presubmit.yml, modules/fasttext/0.10.0-bcr.20240313-1142dc4.bcr.1/source.json, modules/fasttext/metadata.json
Similar to https://github.com/bazelbuild/bazel-central-registry/pull/3954.
Both these projects don't have a typical `include/<lib_name>` directory, so we have to use `strip_include_prefix` and/or `include_prefix` to make their include paths match what users expect.
This allows these deps to be included using angle brackets and with or without the lib name prefix. E.g.,
```c++
#include <fasttext/fasttext.h>
#include <exprtk/exprtk.hpp>
```
or
```c++
#include <fasttext.h>
#include <exprtk.hpp>
```
=> Fixed include paths for `fasttext` and `exprtk`.

modules/opencensus-proto/0.4.1.bcr.2/MODULE.bazel, modules/opencensus-proto/0.4.1.bcr.2/overlay/MODULE.bazel, modules/opencensus-proto/0.4.1.bcr.2/patches/py-proto-library.patch, modules/opencensus-proto/0.4.1.bcr.2/presubmit.yml, modules/opencensus-proto/0.4.1.bcr.2/source.json, modules/opencensus-proto/metadata.json
This fixes compatibility with newer versions of protobuf by using the new implementation of py_proto_library.
=> Add opencensus-proto 0.4.1.bcr.2

modules/portaudio/19.7.0.bcr.1/MODULE.bazel, modules/portaudio/19.7.0.bcr.1/overlay/BUILD.bazel, modules/portaudio/19.7.0.bcr.1/overlay/MODULE.bazel, modules/portaudio/19.7.0.bcr.1/presubmit.yml, modules/portaudio/19.7.0.bcr.1/source.json, modules/portaudio/metadata.json
With `asound` now available (https://github.com/bazelbuild/bazel-central-registry/pull/4121) this flag can be enabled for linux.
=> portaudio@19.7.0.bcr.1

modules/aspect_rules_js/metadata.json
rules_js 2.3.2 is faulty version that breaks the public api for js_image_layer and therefore should not be used.
https://github.com/aspect-build/rules_js/pull/2145
https://github.com/aspect-build/rules_js/pull/2143
https://github.com/aspect-build/rules_js/pull/2142
https://github.com/aspect-build/rules_js/pull/2141
=> chore: yank rules_js 2.3.2

modules/pegtl/3.2.8/MODULE.bazel, modules/pegtl/3.2.8/overlay/BUILD.bazel, modules/pegtl/3.2.8/overlay/src/example/pegtl/BUILD.bazel, modules/pegtl/3.2.8/patches/module_dot_bazel.patch, modules/pegtl/3.2.8/presubmit.yml, modules/pegtl/3.2.8/source.json, modules/pegtl/metadata.json
PEGTL is a header-only library for parsing expression grammars.
This bzlmod entry adds a target for the header-only pegtl library, as well as cc_binary targets for the examples subdirectory, some of which are useful in their own right.
=> PEGTL bzlmod entry

modules/bazelpods/metadata.json, modules/com_github_rabbitmq_looking_glass/metadata.json, modules/lz4-erlang/metadata.json, modules/protobuf/metadata.json, modules/rabbitmq_osiris/metadata.json, modules/rabbitmq_ra/metadata.json, modules/rabbitmq_seshat/metadata.json, modules/rules_elixir/metadata.json, modules/rules_erlang/metadata.json
Those maintainers have their github account deleted or moved to a new user name.
=> Update module maintainer username

tools/bcr_validation.py
Because
```
curl -s https://github.com/<org>/<repo>/latest-commit/refs/pull/N/head -H "Accept: application/json" | jq .isSpoofed
```
will return False, which is wrong.
=> Check github repo reference is not a PR

modules/rules_ytt/0.4.0/patches/module_dot_bazel.patch, modules/rules_ytt/0.4.0/source.json
Without the last line patching fails during the build with the following error:
```
Error in patch: Error applying patch
.../external/rules_ytt~/.tmp_remote_patches/module_dot_bazel.patch: Expecting more chunk line at line 10
```
=> Fix rules_ytt@0.4.0 patch.

modules/libxml2-go/0.0.0-20250331-c934e3f/MODULE.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/MODULE.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/clib/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/dom/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/internal/cmd/genwrapnode/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/internal/debug/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/internal/option/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/parser/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/types/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/xpath/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/overlay/xsd/BUILD.bazel, modules/libxml2-go/0.0.0-20250331-c934e3f/presubmit.yml, modules/libxml2-go/0.0.0-20250331-c934e3f/source.json, modules/libxml2-go/metadata.json
Using peudo-version 0.0.0-20250331-c934e3f (0.0.0-<date>-<latest commit id>) since the original repo doesn't have any official versioning.
Also using overlay, since the original repo has been set read-only.
=> add libxml2-go module

docs/README.md, metadata.schema.json, modules/aspect_rules_js/metadata.json, modules/cel-spec/metadata.json, modules/cjson/metadata.json, modules/cudd/metadata.json, modules/fastjson/metadata.json, modules/gason/metadata.json, modules/jsmn/metadata.json, modules/json11/metadata.json, modules/libcap/metadata.json, modules/prodrive_technologies_bazel_latex/metadata.json, modules/rules_uv/metadata.json, modules/sajson/metadata.json, modules/saru/metadata.json, modules/ultrajson/metadata.json, modules/unittest-cpp/metadata.json, tools/bcr_validation.py
Whenever a module is added or its metadata is changed, verify the github handle of the module maintainer matches the previously recorded github user id. This is to prevent security risk in case of module maintainer's github username change or deletion which will make the previous username available for take over.
=> Verify github user id in metadata.json

tools/bcr_validation.py
Following up https://github.com/bazelbuild/bazel-central-registry/pull/4191
This is to reduce the risk of hitting github api limit in presubmit.
=> Cache github user id in memory

tools/bcr_validation.py
Using symlinks in module overlay dirs is problematic because GitHub doesn't follow them.
For example https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/refs/heads/main/modules/boost.asio/1.87.0/overlay/BUILD.bazel
is a symlink and indeed this causes issues like `Java.io.IOException: Error downloading [https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/modules/boost.asio/1.87.0/overlay/BUILD.bazel] to /home/laltenmueller/.cache/bazel/_bazel_laltenmueller/5f48ff965103b174f3c248651ebad24d/external/boost.asio~/BUILD.bazel: Checksum was sha256-vBvC/W9TQ9vRetDZWdnElvq8fuVlhV+T0Lkv9mw/lJk= but wanted sha256-7dsPuPevCutp/EdPRxhW0dlbB1wNJFseGx4b35TS2WA=` (see https://github.com/bazelbuild/bazel-central-registry/pull/3991, …
=> Don't allow symlinks in module overlay

modules/ncurses/6.4.20221231.bcr.6/MODULE.bazel, modules/ncurses/6.4.20221231.bcr.6/overlay/BUILD.bazel, modules/ncurses/6.4.20221231.bcr.6/overlay/MODULE.bazel, modules/ncurses/6.4.20221231.bcr.6/overlay/bazel/BUILD.bazel, modules/ncurses/6.4.20221231.bcr.6/overlay/bazel/automake_substitution.bzl, modules/ncurses/6.4.20221231.bcr.6/overlay/bazel/pseudo_configure.bzl, modules/ncurses/6.4.20221231.bcr.6/patches/change_mode.patch, modules/ncurses/6.4.20221231.bcr.6/patches/fail_on_error.patch, modules/ncurses/6.4.20221231.bcr.6/presubmit.yml, modules/ncurses/6.4.20221231.bcr.6/source.json, modules/ncurses/metadata.json
Changes:
- Convert `automake_substitution` and `pseudo_configure` to rules.
- Adds support for armv7.
=> ncurses@6.4.20221231.bcr.6

modules/nanobind_bazel/2.6.1/MODULE.bazel, modules/nanobind_bazel/2.6.1/presubmit.yml, modules/nanobind_bazel/2.6.1/source.json, modules/nanobind_bazel/metadata.json
No new functionality, just an update to nanobind v2.6.1. Please note that nanobind v2.6.0 was yanked due to a regression, hence, there will be no nanobind_bazel v2.6.0 tag.
=> Add nanobind_bazel v2.6.1

docs/README.md, incompatible_flags.yml
To actually enable this feature, we'll need https://github.com/bazelbuild/continuous-integration/pull/2222
=> Add incompatible_flags.yml and documentation

.github/workflows/dismiss_approvals.yml, .github/workflows/generate_module_diff.yml, .github/workflows/notify_maintainers.yml, .github/workflows/review_prs.yml, .github/workflows/skip_check.yml
Update to https://github.com/bazelbuild/continuous-integration/pull/2222 to support `@bazel-io skip_check incompatible_flags`
=> Update BCR PR Reviewer commit

tools/slsa.py
Currently "slsa-verifier verify-github-attestation" requires experimental mode (https://github.com/slsa-framework/slsa-verifier/pull/840/files)
=> Set required SLSA_VERIFIER_EXPERIMENTAL env var

tools/bcr_validation.py, tools/slsa.py
We need https://github.com/slsa-framework/slsa-verifier/pull/840 for slsa-verifier to work, and this RC is the only version that contains it.
Progress towards https://github.com/bazelbuild/bazel-central-registry/issues/3829
=> Upgrade slsa-verifier to v2.7.1-rc.1

docs/README.md, tools/bcr_validation.py, tools/registry.py
To prevent accidentally bumping compatibility_level of a module: https://github.com/bazelbuild/bazel-central-registry/pull/4145#discussion_r2044252199
To bypass this check, assign `skip-compatibility-level-check` label to the PR, which can be done by commenting `@bazel-io skip_check compatibility_level`
=> Implement compatibility_level check

modules/boost.test/1.87.0.bcr.1/MODULE.bazel, modules/boost.test/1.87.0.bcr.1/overlay/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/overlay/MODULE.bazel, modules/boost.test/1.87.0.bcr.1/overlay/test/baseline-outputs/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/overlay/test/execution_monitor-ts/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/overlay/test/framework-ts/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/overlay/test/multithreading-ts/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/overlay/test/smoke-ts/BUILD.bazel, modules/boost.test/1.87.0.bcr.1/presubmit.yml, modules/boost.test/1.87.0.bcr.1/source.json, modules/boost.test/metadata.json
Boost.Test is meant to provide a header-only version and a source version of the library (https://sourcegraph.com/github.com/boostorg/test/-/blob/test/CMakeLists.txt).
When including Boost.Test with `#include <boost/test/included/unit_test.hpp>` you do not want to link in the `.cpp` sources, you want to link in the headers only, otherwise you get an `odr-violation` if compiling with ASan ([example](https://gist.github.com/vtsao-openai/2515a13f96989b4279b87219bea9e3c3)).
Normally this is fine as most people don't compile with ASan, but the BCR CI tests seem to run with some form of ASan, so BCR CI tests will fail due to this. This PR provides a `@boost.test//:hdrs` target so anybody including with `#include <boost/test/included/unit_test.hpp>` can use that target to avoid getting …
=> [boost.test] Split the library targets into a header-only version and a sources version.

modules/rules_abs/0.1.0/MODULE.bazel, modules/rules_abs/0.1.0/presubmit.yml, modules/rules_abs/0.1.0/source.json, modules/rules_abs/metadata.json
This adds rules_abs which is heavily based on rules_gcs and rules_s3 but supports using the azure blob store.
=> Add release 0.1.0 of rules_abs

modules/rules_oci/2.2.6/MODULE.bazel, modules/rules_oci/2.2.6/attestations.json, modules/rules_oci/2.2.6/patches/module_dot_bazel_version.patch, modules/rules_oci/2.2.6/presubmit.yml, modules/rules_oci/2.2.6/source.json, modules/rules_oci/metadata.json
Release: https://github.com/bazel-contrib/rules_oci/releases/tag/v2.2.6
=> Publish rules_oci@2.2.6

modules/eigen/3.4.0.bcr.3/MODULE.bazel, modules/eigen/3.4.0.bcr.3/overlay/BUILD.bazel, modules/eigen/3.4.0.bcr.3/overlay/MODULE.bazel, modules/eigen/3.4.0.bcr.3/presubmit.yml, modules/eigen/3.4.0.bcr.3/source.json, modules/eigen/metadata.json
Fixes #4355.
Closes #4361.
I have [pinged Eigen upstream](https://gitlab.com/libeigen/eigen/-/issues/2919) about providing stable source archives, but for now at least GitHub's promises to for git archives to remain stable seem more truthful that GitLab's.
=> eigen@3.4.0.bcr.3

modules/grpc_ecosystem_grpc_gateway/2.26.1/MODULE.bazel, modules/grpc_ecosystem_grpc_gateway/2.26.1/patches/module_dot_bazel.patch, modules/grpc_ecosystem_grpc_gateway/2.26.1/presubmit.yml, modules/grpc_ecosystem_grpc_gateway/2.26.1/source.json, modules/grpc_ecosystem_grpc_gateway/metadata.json
We also need the older version since we are not yet ready to update some transitive dependencies on our side.
=> Add grpc-gateway 2.26.1

modules/libdwarf/0.12.0.bcr.1/MODULE.bazel, modules/libdwarf/0.12.0.bcr.1/overlay/BUILD.bazel, modules/libdwarf/0.12.0.bcr.1/overlay/MODULE.bazel, modules/libdwarf/0.12.0.bcr.1/overlay/gen_test_targets.bzl, modules/libdwarf/0.12.0.bcr.1/presubmit.yml, modules/libdwarf/0.12.0.bcr.1/source.json, modules/libdwarf/metadata.json
For example:
```c++
#include <libdwarf/dwarf.h>
```
=> [libdwarf] Add the ability to include this library using the `libdwarf` prefix

modules/spirv_headers/1.4.313/MODULE.bazel, modules/spirv_headers/1.4.313/patches/version.patch, modules/spirv_headers/1.4.313/presubmit.yml, modules/spirv_headers/1.4.313/source.json, modules/spirv_headers/README.md, modules/spirv_headers/metadata.json
Note that this is off of the [vulkan-sdk-1.4.313](https://github.com/KhronosGroup/SPIRV-Headers/tree/vulkan-sdk-1.4.313) branch but includes BCR patches to bring in https://github.com/KhronosGroup/SPIRV-Headers/pull/511 (the BCR support).
=> spirv_headers@1.4.313-aa6cef1

modules/rules_cc_hdrs_map/0.1.0/MODULE.bazel, modules/rules_cc_hdrs_map/0.1.0/presubmit.yml, modules/rules_cc_hdrs_map/0.1.0/source.json, modules/rules_cc_hdrs_map/metadata.json
Introduce rules extending the CC compilation capabilities with headers map and exposing cc_common compilation functionality in form of Bazel subrules.
=> add rules_cc_hdrs_map@0.1.0

modules/tar.bzl/0.2.0/MODULE.bazel, modules/tar.bzl/0.2.0/attestations.json, modules/tar.bzl/0.2.0/patches/module_dot_bazel_version.patch, modules/tar.bzl/0.2.0/presubmit.yml, modules/tar.bzl/0.2.0/source.json, modules/tar.bzl/metadata.json
Release: https://github.com/alexeagle/tar.bzl/releases/tag/v0.2.0
=> Publish tar.bzl@0.2.0

modules/jemalloc/5.3.0-bcr.alpha.4/MODULE.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/MODULE.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/examples/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/examples/MODULE.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/examples/test_api.c, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/examples/test_basic.c, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/include/jemalloc/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/include/jemalloc/internal/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/include/jemalloc/internal/private_namespace.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/include/jemalloc/internal/public_symbols.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/settings/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/settings/compiler/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/settings/config.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/settings/flags/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/settings/platform/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/test/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/test/integration/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/test/unit/BUILD.bazel, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/tools/autoconf.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/tools/cc.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/tools/test.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/tools/transition.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/overlay/tools/version.bzl, modules/jemalloc/5.3.0-bcr.alpha.4/patches/skipped-tests-exit-0.patch, modules/jemalloc/5.3.0-bcr.alpha.4/presubmit.yml, modules/jemalloc/5.3.0-bcr.alpha.4/scripts/jemalloc_to_bcr.sh, modules/jemalloc/5.3.0-bcr.alpha.4/source.json, modules/jemalloc/metadata.json
The build is updated to handle setting a private namespace and conf during the build. Minor refactoring and fixes to prof tests.
=> jemalloc: Update to handle additional build flags

modules/tar.bzl/0.2.1/MODULE.bazel, modules/tar.bzl/0.2.1/attestations.json, modules/tar.bzl/0.2.1/patches/module_dot_bazel_version.patch, modules/tar.bzl/0.2.1/presubmit.yml, modules/tar.bzl/0.2.1/source.json, modules/tar.bzl/metadata.json
Release: https://github.com/bazel-contrib/tar.bzl/releases/tag/v0.2.1
=> Publish tar.bzl@0.2.1

modules/gz-math/8.1.0/source.json, modules/gz-math/metadata.json
Upstream shasum changed for github generated tar.
I ran
```
$ bazel run tools:update_integrity -- gz-math
```
=> Updated integrity for gz-math

modules/libzmq/4.3.5.bcr.2/MODULE.bazel, modules/libzmq/4.3.5.bcr.2/patches/add_build_file.patch, modules/libzmq/4.3.5.bcr.2/patches/module_dot_bazel.patch, modules/libzmq/4.3.5.bcr.2/presubmit.yml, modules/libzmq/4.3.5.bcr.2/source.json, modules/libzmq/metadata.json
lib-zmq fails to compile and link correctly on some Linux distributions with the default Cmake options. This change adds a new package version that strips out a few non-essential components from the build (shared lib, tests and GnuTLS dependency) to compile successfully.
=> Add 4.3.5.bcr.2 version for libzmq with updated cmake options

modules/rules_scala/7.0.0/MODULE.bazel, modules/rules_scala/7.0.0/attestations.json, modules/rules_scala/7.0.0/presubmit.yml, modules/rules_scala/7.0.0/source.json, modules/rules_scala/metadata.json
Release: https://github.com/bazel-contrib/rules_scala/releases/tag/v7.0.0
=> Publish rules_scala@7.0.0

modules/cppzmq/4.10.0.bcr.1/MODULE.bazel, modules/cppzmq/4.10.0.bcr.1/patches/add_build_file.patch, modules/cppzmq/4.10.0.bcr.1/patches/module_dot_bazel.patch, modules/cppzmq/4.10.0.bcr.1/presubmit.yml, modules/cppzmq/4.10.0.bcr.1/source.json, modules/cppzmq/metadata.json
Build fails for version 4.10.0 on Ubuntu 24.04 (Noble) for depending packages with
```
src/Discovery.cc:18:10: fatal error: zmq.hpp: No such file or directory
18 | #include <zmq.hpp>
```
This is because the `cppzmq` target does not declare any `includes`. I have added a new version `4.10.0.bcr.1` to address this issue.
=> Add cppzmq version 4.10.0.bcr.1 to fix build on Ubuntu Noble

modules/gz-math/8.1.1/MODULE.bazel, modules/gz-math/8.1.1/patches/fix_clang_build.patch, modules/gz-math/8.1.1/patches/module_dot_bazel.patch, modules/gz-math/8.1.1/presubmit.yml, modules/gz-math/8.1.1/source.json, modules/gz-math/metadata.json
Clang build fails layering check. This will be fixed upstream in v8.1.2, but I pulled in the fix with a patch here to unblock adding downstream packages that depend on v8.1.1 to BCR (e.g. https://github.com/bazelbuild/bazel-central-registry/pull/4557).
Also bumped eigen dep version from `3.4.0` to `3.4.0.bcr.3` which sources an archive with more stable integrity (https://github.com/bazelbuild/bazel-central-registry/issues/4355)
=> Add gz-math module version 8.1.1

modules/openconfig_bootz/0.5.0/MODULE.bazel, modules/openconfig_bootz/0.5.0/patches/module_dot_bazel.patch, modules/openconfig_bootz/0.5.0/presubmit.yml, modules/openconfig_bootz/0.5.0/source.json, modules/openconfig_bootz/metadata.json
Add BCR package for github.com/openconfig/bootz.
I think incompatible_flags will fail because of the GRPC dep - I don't see any version of GRPC that has the issue fixed though. I confirmed if I explicitly pin a newer grpc/rules_foreign_cc it passes.
=> Add openconfig_bootz@0.5.0

tools/registry.py
Debian 10 has an old gcc compiler which often breaks some modules.
=> Upgrade the default platforms

tools/bcr_validation.py, tools/registry.py
GitHub has started to throttle unauthenticated traffic, which has caused the attestation presubmit check to fail: https://buildkite.com/bazel/bcr-presubmit/builds/14065#0196d96c-b03d-472d-9b36-2083763d1db0/257
=> Read upstream registry data from GCS mirror

modules/sdformat/15.3.0/MODULE.bazel, modules/sdformat/15.3.0/patches/fix_clang_build.patch, modules/sdformat/15.3.0/patches/module_dot_bazel.patch, modules/sdformat/15.3.0/presubmit.yml, modules/sdformat/15.3.0/source.json, modules/sdformat/metadata.json
Also update presubmit.yml to drop bazel 6 and specify build verification targets explicitly.
Some bazel changes had to be patched in to pass presubmits, which will be part of the next upstream release in sdformat.
=> Add sdformat v15.3.0

MODULE.bazel, tools/BUILD
For modules we test with https://github.com/bazelbuild/bazel-central-registry/blob/bd6000574b1908998f503acbcb69111487a72b32/docs/README.md#L180 to prepare https://github.com/bazelbuild/bazel/issues/23043, hence we should also do this for this repo itself and load the starlark rules.
=> Load sh_test from rules_shell

modules/libzip/1.11.4/MODULE.bazel, modules/libzip/1.11.4/patches/add-build-file.patch, modules/libzip/1.11.4/patches/module_dot_bazel.patch, modules/libzip/1.11.4/presubmit.yml, modules/libzip/1.11.4/source.json, modules/libzip/metadata.json
Also,
- Set cmake `ENABLE_LZMA` to off to fix linker errors
- Bump version for all dependencies in MODULE.bazel
- Add bazel 8.x coverage in presubmits
- Add MacOS coverage in presubmits
=> Bump libzip to 1.11.4

modules/toolchains_llvm_bootstrapped/0.1.9/MODULE.bazel, modules/toolchains_llvm_bootstrapped/0.1.9/attestations.json, modules/toolchains_llvm_bootstrapped/0.1.9/presubmit.yml, modules/toolchains_llvm_bootstrapped/0.1.9/source.json, modules/toolchains_llvm_bootstrapped/metadata.json
Release: https://github.com/cerisier/toolchains_llvm_bootstrapped/releases/tag/0.1.9
=> Publish toolchains_llvm_bootstrapped@0.1.9

modules/liburing/2.10/MODULE.bazel, modules/liburing/2.10/overlay/BUILD.bazel, modules/liburing/2.10/overlay/MODULE.bazel, modules/liburing/2.10/presubmit.yml, modules/liburing/2.10/source.json, modules/liburing/metadata.json
BUILD.bazel is identical to liburing 2.5. Migrated to using overlay dir.
=> Add liburing 2.10

modules/toolchains_llvm_bootstrapped/0.2.1/MODULE.bazel, modules/toolchains_llvm_bootstrapped/0.2.1/attestations.json, modules/toolchains_llvm_bootstrapped/0.2.1/presubmit.yml, modules/toolchains_llvm_bootstrapped/0.2.1/source.json, modules/toolchains_llvm_bootstrapped/metadata.json
Release: https://github.com/cerisier/toolchains_llvm_bootstrapped/releases/tag/0.2.1
=> Publish toolchains_llvm_bootstrapped@0.2.1

modules/soplex/7.1.4.bcr.1/MODULE.bazel, modules/soplex/7.1.4.bcr.1/overlay/BUILD.bazel, modules/soplex/7.1.4.bcr.1/overlay/MODULE.bazel, modules/soplex/7.1.4.bcr.1/patches/add_config_dot_h.patch, modules/soplex/7.1.4.bcr.1/patches/add_git_hash_dot_cpp.patch, modules/soplex/7.1.4.bcr.1/patches/fmt_dot_hpp.patch, modules/soplex/7.1.4.bcr.1/patches/macos_debug.patch, modules/soplex/7.1.4.bcr.1/patches/spxfileio_dot_h.patch, modules/soplex/7.1.4.bcr.1/presubmit.yml, modules/soplex/7.1.4.bcr.1/source.json, modules/soplex/metadata.json
Cf. https://github.com/scipopt/soplex/issues/47 and https://github.com/bazelbuild/bazel/issues/3513 for context. This patch adds a patch to ensure soplex's upstream use of `DEBUG` does not conflict with the `DEBUG` preprocessor symbol introduced by bazel on Apple platforms for debug builds.
=> Add patch to soplex for MacOS builds in `dbg` mode.

modules/gazelle_cc/0.1.0/MODULE.bazel, modules/gazelle_cc/0.1.0/attestations.json, modules/gazelle_cc/0.1.0/patches/module_dot_bazel_version.patch, modules/gazelle_cc/0.1.0/presubmit.yml, modules/gazelle_cc/0.1.0/source.json, modules/gazelle_cc/metadata.json
Release: https://github.com/EngFlow/gazelle_cc/releases/tag/v0.1.0
=> Publish gazelle_cc@0.1.0

modules/rules_swift/metadata.json
This had the wrong `compatibility_level` when we published it. Fixed in 3.0.2
=> Yank rules_swift 3.0.0

modules/protovalidate-cc/0.7.0/MODULE.bazel, modules/protovalidate-cc/0.7.0/presubmit.yml, modules/protovalidate-cc/0.7.0/source.json, modules/protovalidate-cc/metadata.json
Release: https://github.com/bufbuild/protovalidate-cc/releases/tag/v0.7.0
=> Publish protovalidate-cc@0.7.0

modules/civetweb/1.16.bcr.2/MODULE.bazel, modules/civetweb/1.16.bcr.2/patches/add_build_file.patch, modules/civetweb/1.16.bcr.2/patches/module_dot_bazel.patch, modules/civetweb/1.16.bcr.2/presubmit.yml, modules/civetweb/1.16.bcr.2/source.json, modules/civetweb/metadata.json
When websocket is needed, the original library lacks "-DUSE_WEBSOCKET", so a link error will occur
```
bazel-out/k8-fastbuild/bin/modules/dreamview/backend/handlers/_objs/websocket_handler/websocket_handler.pic.o:websocket_handler.cc:function apollo::dreamview::WebSocketHandler::SendData(mg_connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int): error: undefined reference to 'mg_websocket_write'
```
Add -DUSE_WEBSOCKET and add header files
=> fix(civetweb): fix undefined reference to 'mg_websocket_write'

modules/protovalidate-cc/0.8.0/MODULE.bazel, modules/protovalidate-cc/0.8.0/presubmit.yml, modules/protovalidate-cc/0.8.0/source.json, modules/protovalidate-cc/metadata.json
Release: https://github.com/bufbuild/protovalidate-cc/releases/tag/v0.8.0
=> Publish protovalidate-cc@0.8.0

modules/azure-core-cpp/1.14.1.bcr.2/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.2/overlay/BUILD.bazel, modules/azure-core-cpp/1.14.1.bcr.2/overlay/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.2/overlay/test/MODULE.bazel, modules/azure-core-cpp/1.14.1.bcr.2/presubmit.yml, modules/azure-core-cpp/1.14.1.bcr.2/source.json, modules/azure-core-cpp/metadata.json
This library's transport wasn't working b/c I forgot to define macros for the specified transport settings.
The only change is that we now define `BUILD_CURL_HTTP_TRANSPORT_ADAPTER` when curl is being used and `BUILD_TRANSPORT_WINHTTP_ADAPTER` when winhttp is being used.
=> [azure-core-cpp] Fix broken transport by defining the appropriate macros

modules/gz-sim/9.2.0/MODULE.bazel, modules/gz-sim/9.2.0/patches/module_dot_bazel.patch, modules/gz-sim/9.2.0/presubmit.yml, modules/gz-sim/9.2.0/source.json, modules/gz-sim/metadata.json
This PR adds the Gz Sim package to BCR, which is part of the Gazebo simulation framework. Only the core library is currently supported in bazel.
=> Add gz-sim (core)

modules/libxslt/1.1.43/MODULE.bazel, modules/libxslt/1.1.43/patches/build_dot_bazel.patch, modules/libxslt/1.1.43/patches/module_dot_bazel.patch, modules/libxslt/1.1.43/presubmit.yml, modules/libxslt/1.1.43/source.json, modules/libxslt/metadata.json
This pull request packages [libxslt](https://gitlab.gnome.org/GNOME/libxslt) using `rules_foreign_cc`'s `cmake` module.
The package was tested with a small test program depending on libxslt and libxml2 on Ubuntu 25.04 aarch64.
The validation test `bazel run -- //tools:bcr_validation --check=libxlt` passed.
This is my first contribution to the bazel-central-registry, so please review this PR carefully :)
Also, is there a way to split libxslt and libexslt into separate entities, i.e. `@libxslt//:libxslt` and `@libxslt//:libexslt`?
=> feat: Add package libxslt 1.1.43

modules/freeimage/3.19.10.bcr.1/MODULE.bazel, modules/freeimage/3.19.10.bcr.1/patches/add_build_file.patch, modules/freeimage/3.19.10.bcr.1/patches/module_dot_bazel.patch, modules/freeimage/3.19.10.bcr.1/patches/tif_unix.patch, modules/freeimage/3.19.10.bcr.1/presubmit.yml, modules/freeimage/3.19.10.bcr.1/source.json, modules/freeimage/metadata.json
Adds a patch to avoid duplicate tif unix function definitions.
=> freeimage@3.19.10.bcr.1

tools/bcr_validation.py, tools/slsa.py
We no longer need to depend on an experimental feature.
This change also fixes slsa-verifier output - for some reason it doesn't print to stdout, only stderr.
=> Upgrade slsa-verifier to v2.7.1

modules/cpp-sqlite/0.0.0-20230222-7f931c4/MODULE.bazel, modules/cpp-sqlite/0.0.0-20230222-7f931c4/overlay/BUILD.bazel, modules/cpp-sqlite/0.0.0-20230222-7f931c4/overlay/MODULE.bazel, modules/cpp-sqlite/0.0.0-20230222-7f931c4/presubmit.yml, modules/cpp-sqlite/0.0.0-20230222-7f931c4/source.json, modules/cpp-sqlite/0.0.0-20241111-21be8b5/MODULE.bazel, modules/cpp-sqlite/0.0.0-20241111-21be8b5/overlay/BUILD.bazel, modules/cpp-sqlite/0.0.0-20241111-21be8b5/overlay/MODULE.bazel, modules/cpp-sqlite/0.0.0-20241111-21be8b5/presubmit.yml, modules/cpp-sqlite/0.0.0-20241111-21be8b5/source.json, modules/cpp-sqlite/metadata.json
NOTE: There are two versions submitted. The newer version has changes that are backwards-incompatible with the older version, so I bumped the compatibility_level. I included both because I need to depend specifically on the older version.
=> Add cpp-sqlite

tools/bcr_validation.py
This makes it easier to reason about the relation between version and compatibility level, especially when using `max_compatibility_level`. 
The docs already suggest this property, but don't state it as an invariant. We can hold the BCR to this standard while we decide whether this should become a hard requirement for all registries.
=> Enforce that `compatibility_level` is monontically increasing

docs/mcp.md, tools/BUILD, tools/README.md
Use `bazel run` to start the server, which is more convenient than requiring users to set up the python environment.
=> Improve setup of the BCR MCP server

modules/boost.endian/1.88.0.bcr.1/MODULE.bazel, modules/boost.endian/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.endian/1.88.0.bcr.1/overlay/MODULE.bazel, modules/boost.endian/1.88.0.bcr.1/presubmit.yml, modules/boost.endian/1.88.0.bcr.1/source.json, modules/boost.endian/metadata.json, modules/boost.static_assert/1.88.0.bcr.1/MODULE.bazel, modules/boost.static_assert/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.static_assert/1.88.0.bcr.1/overlay/MODULE.bazel, modules/boost.static_assert/1.88.0.bcr.1/presubmit.yml, modules/boost.static_assert/1.88.0.bcr.1/source.json, modules/boost.static_assert/metadata.json, modules/boost.typeof/1.88.0.bcr.1/MODULE.bazel, modules/boost.typeof/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.typeof/1.88.0.bcr.1/overlay/MODULE.bazel, modules/boost.typeof/1.88.0.bcr.1/presubmit.yml, modules/boost.typeof/1.88.0.bcr.1/source.json, modules/boost.vmd/1.88.0.bcr.1/MODULE.bazel, modules/boost.vmd/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.vmd/1.88.0.bcr.1/overlay/MODULE.bazel, modules/boost.vmd/1.88.0.bcr.1/presubmit.yml, modules/boost.vmd/1.88.0.bcr.1/source.json, modules/boost.vmd/metadata.json, modules/boost.winapi/1.88.0.bcr.1/MODULE.bazel, modules/boost.winapi/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.winapi/1.88.0.bcr.1/overlay/MODULE.bazel, modules/boost.winapi/1.88.0.bcr.1/presubmit.yml, modules/boost.winapi/1.88.0.bcr.1/source.json, modules/boost.winapi/metadata.json
Add Boost 1.88.0 Level 1 dependencies, in particular:
- endian
- static_assert
- typeof
- vmd
- winapi
=> Add Boost 1.88.0 Level 1 dependencies

tools/migrate_to_bzlmod.py
Use module extensions when there is a macro, instead of repo rules. 
Don't just abort when an error is not parsed correctly - Print the error first.
=> Updates to the bzlmod migration tool

modules/postgres/14.18/MODULE.bazel, modules/postgres/14.18/overlay/BUILD.bazel, modules/postgres/14.18/overlay/MODULE.bazel, modules/postgres/14.18/presubmit.yml, modules/postgres/14.18/source.json, modules/postgres/metadata.json
We are internally using a Bazelified version of [Taopq](https://github.com/taocpp/taopq/tree/main) and it depends on Postgres 14.
I would hence like to add Postgres 14 to the BCR.
I recognize that this is an older version.
Hence, we should
@bazel-io skip_check compatibility_level
Otherwise, it will require us to bump the compatibility level, which would blow up the later version that already exists.
Ran: 
```
bazel run -- //tools:bcr_validation --check=postgres@14.18
```
Also made a temp project with `MODULE.bazel` declaring `bazel_dep(name = "postgres", version = "14.18")` and:
```
bazel clean --expunge && bazel build   --discard_analysis_cache   --disk_cache="" --enable_bzlmod     --registry="file:///<MY_LOCAL_REPO_DIR>"   --lockfile_mode=off   @postgres//...
```
=> Add postgres 14.18

tools/registry.py
This change addresses the issue identified on https://github.com/bazelbuild/bazel-central-registry/pull/5369 where downloads from https://sourceforge.net/ would be sent back html documents instead of the target files.
=> Update user-agent header for bcr_validation downloads

MODULE.bazel
This affects `//tools:setup_presubmit_repos` only.
=> Update MODULE.bazel to refer to the latest bazelci.py

modules/google_cloud_cpp/3.0.0-rc1/MODULE.bazel, modules/google_cloud_cpp/3.0.0-rc1/patches/copyright.patch, modules/google_cloud_cpp/3.0.0-rc1/presubmit.yml, modules/google_cloud_cpp/3.0.0-rc1/source.json, modules/google_cloud_cpp/metadata.json
This pull request adds google-cloud-cpp@3.0.0-rc1 to the Bazel Central Registry.
This is the next release candidate for our upcoming v3.0.0 major version. We are publishing this pre-release to the BCR to continue testing our new Bzlmod support and allow customers to begin previewing the integration.
=> feat: add google_cloud_cpp@3.0.0-rc1

modules/postgres/14.18.bcr.1/MODULE.bazel, modules/postgres/14.18.bcr.1/overlay/BUILD.bazel, modules/postgres/14.18.bcr.1/overlay/MODULE.bazel, modules/postgres/14.18.bcr.1/presubmit.yml, modules/postgres/14.18.bcr.1/source.json, modules/postgres/metadata.json
This is here in case we don't like the approach in:
- https://github.com/bazelbuild/bazel-central-registry/pull/5464
It turns out that I made a typo in the previous release:
https://github.com/bazelbuild/bazel-central-registry/pull/5206
This typo prevents dependents from using the target at the version
The module name should match the BCR name (postgres instead of postgres14).
Ran: 
```
bazel run -- //tools:bcr_validation --check=postgres@14.18.bcr.1
```
Also made a temp project with `MODULE.bazel` declaring `bazel_dep(name = "postgres", version = "14.18.bcr.1")` and:
```
bazel clean --expunge && bazel build   --discard_analysis_cache   --disk_cache="" --enable_bzlmod     --registry="file:///<MY_LOCAL_REPO_DIR>"   --lockfile_mode=off   @postgres//...
```
=> Fix MODULE typo by adding Postgres 14.18.bcr.1

modules/seastar/25.08.0-20250807194611-1520326e6032/MODULE.bazel, modules/seastar/25.08.0-20250807194611-1520326e6032/overlay/BUILD.bazel, modules/seastar/25.08.0-20250807194611-1520326e6032/overlay/MODULE.bazel, modules/seastar/25.08.0-20250807194611-1520326e6032/presubmit.yml, modules/seastar/25.08.0-20250807194611-1520326e6032/source.json, modules/seastar/metadata.json
Adds the Seastar C++ library to the BCR.
Seastar primarily focuses on keeping a stable trunk, and there isn't currently any official tagged releases.
=> Add seastar@25.08.0

modules/re2/2025-08-12/MODULE.bazel, modules/re2/2025-08-12/presubmit.yml, modules/re2/2025-08-12/source.json, modules/re2/metadata.json
Release: https://github.com/google/re2/releases/tag/2025-08-12
=> Publish re2@2025-08-12

modules/poco/1.14.2-20250528.bcr.1/MODULE.bazel, modules/poco/1.14.2-20250528.bcr.1/overlay/BUILD, modules/poco/1.14.2-20250528.bcr.1/overlay/MODULE.bazel, modules/poco/1.14.2-20250528.bcr.1/presubmit.yml, modules/poco/1.14.2-20250528.bcr.1/source.json, modules/poco/metadata.json
#5579 is not great, because some included symbols are not defined, leading to errors of the form
```
ld.lld: error: undefined symbol: Poco::floatToFixedStr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, float, int, int, char, char)
>>> referenced by NumberFormatter.cpp
>>>               bazel-out/haswell-fastbuild/bin/external/poco+/_objs/PocoFoundation/NumberFormatter.pic.o:(Poco::NumberFormatter::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, float, int, int))
```
This might not be a problem when building with `-c opt`, depending on which parts of the library is used, as optimization flags will delete unused code.
This fixes those issues (verified by building with `-c fastbuild`).
=> fix poco on BCR

modules/pre-commit-hooks/1.3.1/MODULE.bazel, modules/pre-commit-hooks/1.3.1/presubmit.yml, modules/pre-commit-hooks/1.3.1/source.json, modules/pre-commit-hooks/metadata.json
Add the following to `MODULE.bazel`:
```py
bazel_dep(name = "pre-commit", version = "<version>")
bazel_dep(name = "pre-commit-hooks", version = "<version>")
```
Create a `hooks` directory to create the `pre-commit` configuration:
```py
load("@pre-commit//pre-commit:defs.bzl", "pre_commit")
pre_commit(
name = "hooks",
srcs = ["@pre-commit-hooks"],
)
```
Install the hooks with `bazelisk run -- hooks:install`.
Run the hooks with `bazelisk run -- hooks`.
The project uses `rules_python` which is hermetic when `--@rules_python//python/config_settings:bootstrap_impl` is set to `script`.
All hooks provided are hermetic.
=> feat: add `pre-commit-hooks@1.3.1`

tools/bcr_validation.py
Docs:
> With context diffs, and to a lesser extent with normal diffs, patch can detect when the line
numbers mentioned in the patch are incorrect, and will attempt to find the correct place to
apply each hunk of the patch.  As a first guess, it takes the line number mentioned for the
hunk, plus or minus any offset used in applying the previous hunk.  If that is not the correct
place, patch will scan both forwards and backwards for a set of lines matching the context
given in the hunk.  First patch looks for a place where all lines of the context match.  If no
such place is found, and it is a context diff, and the maximum fuzz factor is set to 1 or more,
then another scan takes place ignoring the first and last line of context.  If that fails, and
the maximum fuzz factor is set to 2 or …
=> fix(validation): don't allow patch to fuzz

modules/osqp-eigen/0.10.3/MODULE.bazel, modules/osqp-eigen/0.10.3/presubmit.yml, modules/osqp-eigen/0.10.3/source.json, modules/osqp-eigen/metadata.json
@wep21 this integrates tagged v0.10.3 of osqp-eigen.
I worked with the maintainers there to make sure an easy bcr creation is possible as osqp-eigen itself is now bazelised. 
see https://github.com/robotology/osqp-eigen/pull/205
=> osqp-eigen@0.10.3

modules/boost.beast/1.88.0.bcr.1/MODULE.bazel, modules/boost.beast/1.88.0.bcr.1/overlay/BUILD.bazel, modules/boost.beast/1.88.0.bcr.1/source.json
WARNING: This PR modifies an already published module
By accident, I copied the wrong `MODULE.bazel` and `BUILD.bazel` file (did take the ones from `1.87.0` and not `1.87.0.bcr.1`).
This PR fixes this. I propose to modify the existing `boost.beast@1.88.0.bcr.1` 
In the current version, you get compiler errors such as:
```
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::basic_parser<false>::put(boost::asio::const_buffer, boost::system::error_code&)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::to_string(boost::beast::http::verb)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to …
```
=> Fix boost.beast@1.88.0.bcr.1

modules/fmt/11.2.0.bcr.1/MODULE.bazel, modules/fmt/11.2.0.bcr.1/overlay/BUILD.bazel, modules/fmt/11.2.0.bcr.1/overlay/MODULE.bazel, modules/fmt/11.2.0.bcr.1/patches/f4345467fce7edbc6b36c3fa1cf197a67be617e2.patch, modules/fmt/11.2.0.bcr.1/presubmit.yml, modules/fmt/11.2.0.bcr.1/source.json, modules/fmt/metadata.json
- Backport fmtlib/fmt@f4345467fce7edbc6b36c3fa1cf197a67be617e2 to fix warning `unterminated-string-initialization` in clang 21
- Add myself as maintainer as suggested by the current maintainer in https://github.com/bazelbuild/bazel-central-registry/pull/5736#issuecomment-3246727819
=> Add fmt 11.2.0.bcr.1

modules/blake3/1.8.2/MODULE.bazel, modules/blake3/1.8.2/overlay/BUILD.bazel, modules/blake3/1.8.2/overlay/MODULE.bazel, modules/blake3/1.8.2/overlay/c/BUILD.bazel, modules/blake3/1.8.2/presubmit.yml, modules/blake3/1.8.2/source.json, modules/blake3/README.md, modules/blake3/metadata.json
BLAKE3 version 1.8.2
Adds oneTBB Support - This can be enabled with the `--define=blake3:tbb=enabled` flag. I've added a `README.md` that explains this and a new presubmit task.
I have continued the overlay structure that was used in `1.5.4.bcr.1` instead of using patches.
The existing presubmit matrix and the specific CI configuration for Windows ARM64 have been preserved from the previous version as I lack a local Windows environment to validate any changes. I have also kept the `bazel_compatibility` of the prior version.
This is my first contribution to the BCR. I am very open to all feedback and happy to make any necessary changes. I have also added myself as a maintainer in `metadata.json`. Please let me know if this is acceptable or if you'd prefer a different approach.
=> feat(blake3): Add version 1.8.2 with optional oneTBB support

modules/aom/3.12.1.bcr.1/MODULE.bazel, modules/aom/3.12.1.bcr.1/overlay/BUILD.bazel, modules/aom/3.12.1.bcr.1/overlay/MODULE.bazel, modules/aom/3.12.1.bcr.1/patches/af548f4167a174f64f09d149458dd950219972ac.patch, modules/aom/3.12.1.bcr.1/presubmit.yml, modules/aom/3.12.1.bcr.1/source.json, modules/aom/metadata.json
- Convert from patches to overlay
- Backport [`af548f4167a174f64f09d149458dd950219972ac`](https://aomedia.googlesource.com/aom/+/af548f4167a174f64f09d149458dd950219972ac) to fix warning `unterminated-string-initialization` in clang 21
- Add myself as maintainer
=> Add aom 3.12.1.bcr.1

modules/rules_tensorrt_rtx/0.1.0/MODULE.bazel, modules/rules_tensorrt_rtx/0.1.0/attestations.json, modules/rules_tensorrt_rtx/0.1.0/presubmit.yml, modules/rules_tensorrt_rtx/0.1.0/source.json, modules/rules_tensorrt_rtx/metadata.json
Release: https://github.com/wep21/rules_tensorrt_rtx/releases/tag/v0.1.0
=> Publish rules_tensorrt_rtx@0.1.0

modules/hermetic_clang_toolchain/1.0.0/MODULE.bazel, modules/hermetic_clang_toolchain/1.0.0/presubmit.yml, modules/hermetic_clang_toolchain/1.0.0/source.json, modules/hermetic_clang_toolchain/metadata.json
A lightweight, hermetic Clang toolchain for `bazel` that downloads pre-built
LLVM binaries and bundles necessary system dependencies.
- fully hermetic
- lightweight - downloads pre-built binaries instead of building from source
- cross-platform - works on all linux x86_64 systems
- `clang18` - pre-built compiler binaries
- `ubuntu` lib - bundled `libtinfo5` for compatibility
Add this to your `MODULE.bazel`:
```python
bazel_dep(name = "hermetic_clang_toolchain", version = "1.0.0")
```
=> hermetic_clang_toolchain@1.0.0

modules/hermetic_clang_toolchain/1.0.1/MODULE.bazel, modules/hermetic_clang_toolchain/1.0.1/presubmit.yml, modules/hermetic_clang_toolchain/1.0.1/source.json, modules/hermetic_clang_toolchain/metadata.json
The `hermetic_clang_toolchain` now allows for selecting different `clang` versions (17, 18, 19, 20, 21).
```starlark
bazel_dep(name = "hermetic_clang_toolchain", version = "1.0.1")
hermetic_clang = use_extension("@hermetic_clang_toolchain//clang_toolchain:hermetic_clang.bzl", "hermetic_clang_extension")
hermetic_clang.use(version = "21.1.0")
use_repo(hermetic_clang, "hermetic_clang")
register_toolchains("@hermetic_clang_toolchain//clang_toolchain:hermetic_clang_toolchain")
```
=> hermetic_clang_toolchain@1.0.1

CODEOWNERS
This ensures that maintainers are notified of all infra changes even if they don't watch all activity.
=> Add maintainers as code owners for everything but `/modules/`

modules/lz4/1.10.0/MODULE.bazel, modules/lz4/1.10.0/overlay/BUILD.bazel, modules/lz4/1.10.0/overlay/MODULE.bazel, modules/lz4/1.10.0/overlay/programs/BUILD.bazel, modules/lz4/1.10.0/presubmit.yml, modules/lz4/1.10.0/source.json, modules/lz4/README.md, modules/lz4/metadata.json
Adds multithreaded support for the CLI tool via the bool flag `--@lz4//programs:multithreading=true`. The multithreading feature is now disabled by default on all platforms, including Windows. This provides consistent behaviour but diverges slightly from the upstream build, which enables it by default on Windows. I have added a README to document this.
I have switched to overlay from patches, and the CI has been updated to more modern and varied runners. I have also included a multithreaded CI target.
As this module has no maintainer, I have added myself in `metadata.json`.
=> feat(LZ4): Add version 1.10.0 with optional multithreaded CLI support

modules/protovalidate/metadata.json
The removed user account is no longer active on GitHub.
=> Update maintainers for protovalidate

modules/cpr/1.12.0/MODULE.bazel, modules/cpr/1.12.0/overlay/BUILD.bazel, modules/cpr/1.12.0/overlay/MODULE.bazel, modules/cpr/1.12.0/presubmit.yml, modules/cpr/1.12.0/source.json, modules/cpr/metadata.json
Add https://github.com/libcpr/cpr/releases/tag/1.12.0
Closes https://github.com/bazelbuild/bazel-central-registry/issues/599
There are some upstream efforts to add Bazel integration like https://github.com/libcpr/cpr/issues/1167, but this isn't landed or part of any release.
There is also https://github.com/hedronvision/bazel-make-cc-https-easy but that is Workspace only and unmaintained.
As far as I can see the existing work to Bazelize libcpr was mostly focused on getting curl to build or to use the host curl. This BCR module completely avoids that by just depending on the curl BCR module that exists now (it didn't when some of the previous work was done)
=> Add libcpr

docs/README.md
Large integers in version strings can cause some older Bazel releases to crash with a NumberFormatException.
=> Shorten date in recommended pseudo version string

modules/nghttp2/1.65.0/MODULE.bazel, modules/nghttp2/1.65.0/overlay/BUILD.bazel, modules/nghttp2/1.65.0/overlay/MODULE.bazel, modules/nghttp2/1.65.0/overlay/config/config.h, modules/nghttp2/1.65.0/presubmit.yml, modules/nghttp2/1.65.0/source.json, modules/nghttp2/metadata.json
=> Add nghttp2 module

modules/mcap/2.0.2/MODULE.bazel, modules/mcap/2.0.2/overlay/BUILD.bazel, modules/mcap/2.0.2/overlay/MODULE.bazel, modules/mcap/2.0.2/presubmit.yml, modules/mcap/2.0.2/source.json, modules/mcap/metadata.json
Add mcap 2.0.2. Followed mostly https://github.com/bazelbuild/bazel-central-registry/pull/2665.
PR needs  @bazel-io skip_check unstable_url because the release has no stable url available.
=> mcap@2.0.2

tools/bcr_validation.py
Use archive_type from source.json if specified
Needed in https://github.com/bazelbuild/bazel-central-registry/pull/6006#issuecomment-3365291938
=> Use archive_type from source.json if specified

modules/lz4/metadata.json
Following on from Issue #5899 and PR #5922, this yanks `1.10.0` which can cause dependency build failures due to breaking changes in its refactored build targets
=> Yank LZ4 1.10.0

.gemini/styleguide.md
Hopefully prevent comments like https://github.com/bazelbuild/bazel-central-registry/pull/5999#discussion_r2381049986, https://github.com/bazelbuild/bazel-central-registry/pull/6124
=> Update styleguide with Bazel module dependency notes
