bazelbuild/bazel-central-registry

tools/add_module.py
tools/registry.py
tools/sync_to_gcs.sh

1. Python scripts for updating the registry content
2. A shell script to sync registry content to bcr.bazel.build

Add tools for bazel central registry

---

modules/zlib/1.2.11/MODULE.bazel
modules/zlib/1.2.11/patches/add_build_file.patch
modules/zlib/1.2.11/presubmit.yml
modules/zlib/1.2.11/source.json
modules/zlib/metadata.json
tools/registry.py

Context https://github.com/bazelbuild/bazel-central-registry/issues/7

Add zlib 1.2.11

---

modules/platforms/0.0.4/MODULE.bazel
modules/platforms/0.0.4/presubmit.yml
modules/platforms/0.0.4/source.json
modules/platforms/metadata.json

Context https://github.com/bazelbuild/bazel-central-registry/issues/7

Add platform 0.0.4

---

modules/bazel_skylib/1.0.3/MODULE.bazel
modules/bazel_skylib/1.0.3/presubmit.yml
modules/bazel_skylib/1.0.3/source.json
modules/bazel_skylib/metadata.json

Add bazel_skylib 1.0.3

---

modules/rules_python/0.4.0/MODULE.bazel
modules/rules_python/0.4.0/patches/propagate_pip_install_dependencies.patch
modules/rules_python/0.4.0/presubmit.yml
modules/rules_python/0.4.0/source.json
modules/rules_python/metadata.json

Working towards: https://github.com/bazelbuild/bazel-central-registry/issues/7

Add rules_python 0.4.0

---

modules/rules_pkg/0.5.1/MODULE.bazel
modules/rules_pkg/0.5.1/presubmit.yml
modules/rules_pkg/0.5.1/source.json
modules/rules_pkg/metadata.json

Add rules_pkg 0.5.1

---

modules/rules_proto/metadata.json

Probably a good idea to add some testing for this too

fix wrong version of rules_proto

---

modules/rules_nodejs/4.5.0/MODULE.bazel
modules/rules_nodejs/4.5.0/presubmit.yml
modules/rules_nodejs/4.5.0/source.json
modules/rules_nodejs/metadata.json

This is currently not working.
See repro:
https://github.com/alexeagle/nodejs_bzlmod_example
Probably need some help here @Wyverald @meteorcloudy - either here in the issue or on Slack would be good :)

Add rules_nodejs 4.5.0

---

modules/glog/0.5.0/MODULE.bazel
modules/glog/0.5.0/presubmit.yml
modules/glog/0.5.0/source.json
modules/glog/metadata.json

Leaving this as draft as it requires gflags to be merged first.

Add glog 0.5.0

---

modules/rules_pkg/0.5.1/patches/use_label_for_select.patch
modules/rules_pkg/0.5.1/source.json

Fixes https://github.com/bazelbuild/bazel/issues/15156

Patch rules_pkg 0.5.1 to use label in select statment

---

modules/rules_erlang/3.1.0/MODULE.bazel
modules/rules_erlang/3.1.0/presubmit.yml
modules/rules_erlang/3.1.0/source.json
modules/rules_erlang/metadata.json

https://github.com/rabbitmq/rules_erlang/releases/tag/3.1.0

Add rules_erlang 3.1.0

---

modules/aspect_rules_js/1.0.0/MODULE.bazel
modules/aspect_rules_js/1.0.0/presubmit.yml
modules/aspect_rules_js/1.0.0/source.json
modules/aspect_rules_js/metadata.json

[Automated] Publish aspect-build/rules_js@v1.0.0.

aspect-build/rules_js@v1.0.0

---

modules/gazelle/0.26.0/source.json

https://github.com/bazelbuild/bazel-gazelle/commit/a648a15f9f9e9ffe1bdfb5fb3d92f8ef9a727126

gazelle: Fix canonical label literal usage

---

modules/rules_pkg/0.7.0/MODULE.bazel
modules/rules_pkg/0.7.0/presubmit.yml
modules/rules_pkg/0.7.0/source.json
modules/rules_pkg/metadata.json

Required to fix https://buildkite.com/bazel/bazel-bazel-with-bzlmod/builds/269#_

Add rules_pkg 0.7.0

---

modules/upb/0.0.0-20220602-e5f2601/MODULE.bazel
modules/upb/0.0.0-20220602-e5f2601/presubmit.yml
modules/upb/0.0.0-20220602-e5f2601/source.json
modules/upb/metadata.json

Required to fix https://buildkite.com/bazel/bazel-bazel-with-bzlmod/builds/269#_

Add upb 0.0.0-20220602-e5f2601

---

modules/protoc-gen-validate/0.6.7/MODULE.bazel
modules/protoc-gen-validate/0.6.7/patches/protoc_gen_validate.patch
modules/protoc-gen-validate/0.6.7/presubmit.yml
modules/protoc-gen-validate/0.6.7/source.json
modules/protoc-gen-validate/metadata.json

Required to fix https://buildkite.com/bazel/bazel-bazel-with-bzlmod/builds/269#_

Add protoc-gen-validate 0.6.7

---

modules/zlib/metadata.json

Fix yanked_versions to be a map instead of a list

---

modules/protobuf/3.19.2/MODULE.bazel

protobuf: stop using the yanked version of zlib

---

modules/aspect_bazel_lib/0.11.0/MODULE.bazel
modules/aspect_bazel_lib/0.11.4/MODULE.bazel
modules/aspect_bazel_lib/0.12.1/MODULE.bazel
modules/aspect_bazel_lib/1.0.0/MODULE.bazel
modules/bazel_skylib/1.0.3/MODULE.bazel
modules/bazel_skylib/1.1.1/MODULE.bazel
modules/bazel_skylib/1.2.0/MODULE.bazel
modules/rules_cc/0.0.1/MODULE.bazel
modules/rules_java/5.0.0/MODULE.bazel
modules/rules_nodejs/4.5.0/MODULE.bazel
modules/rules_nodejs/4.5.1/MODULE.bazel
modules/rules_nodejs/5.5.0/MODULE.bazel
modules/rules_python/0.4.0/MODULE.bazel
modules/rules_sh/0.2.0/MODULE.bazel
modules/rules_sh/0.2.0/patches/add_module_extension.patch
modules/rules_sh/0.2.0/source.json

Fixing https://github.com/bazelbuild/bazel-central-registry/issues/127

Migrate toolchain registrations to new API

---

modules/rules_cc/0.0.2/MODULE.bazel
modules/rules_cc/0.0.2/presubmit.yml
modules/rules_cc/0.0.2/source.json
modules/rules_cc/metadata.json

Required by https://github.com/bazelbuild/bazel/pull/16252

Add rules_cc 0.0.2

---

modules/zlib/1.2.13/MODULE.bazel
modules/zlib/1.2.13/patches/add_build_file.patch
modules/zlib/1.2.13/presubmit.yml
modules/zlib/1.2.13/source.json
modules/zlib/metadata.json

Context: https://github.com/bazelbuild/bazel/pull/16508

Add zlib 1.2.13

---

modules/zlib/metadata.json

Due to https://github.com/advisories/GHSA-cfmr-vrgj-vqwv

Yank zlib 1.2.12

---

docs/README.md

As part of our legal review, we should have a moderation process for checked in modules.

Document the process to take down a module

---

modules/nlohmann_json/3.6.1/MODULE.bazel
modules/nlohmann_json/3.6.1/patches/add_build_file.patch
modules/nlohmann_json/3.6.1/patches/module_dot_bazel.patch
modules/nlohmann_json/3.6.1/presubmit.yml
modules/nlohmann_json/3.6.1/source.json
modules/nlohmann_json/metadata.json

I wasn't sure about naming here, but just taking the 'json' namespace seemed like a bad idea

Add nlohmann/json

---

modules/nlohmann_json/3.11.2/MODULE.bazel
modules/nlohmann_json/3.11.2/patches/add_build_file.patch
modules/nlohmann_json/3.11.2/patches/module_dot_bazel.patch
modules/nlohmann_json/3.11.2/presubmit.yml
modules/nlohmann_json/3.11.2/source.json
modules/nlohmann_json/metadata.json

This is the current newest version

Add nlohmann_json 3.11.2

---

modules/boringssl/0.0.0-20230215-5c22014/MODULE.bazel
modules/boringssl/0.0.0-20230215-5c22014/patches/module_dot_bazel.patch
modules/boringssl/0.0.0-20230215-5c22014/presubmit.yml
modules/boringssl/0.0.0-20230215-5c22014/source.json
modules/boringssl/metadata.json

This is a dependency of github.com/google/tink.

Add boringssl@0.0.0-20230215-5c22014 to BCR

---

modules/rules_testing/0.0.1/MODULE.bazel
modules/rules_testing/0.0.1/patches/module_dot_bazel.patch
modules/rules_testing/0.0.1/presubmit.yml
modules/rules_testing/0.0.1/source.json
modules/rules_testing/metadata.json

Add rules_testing to BCR

---

modules/rapidjson/1.1.0/MODULE.bazel
modules/rapidjson/1.1.0/patches/add_build_file.patch
modules/rapidjson/1.1.0/patches/module_dot_bazel.patch
modules/rapidjson/1.1.0/presubmit.yml
modules/rapidjson/1.1.0/source.json
modules/rapidjson/metadata.json

This is a dependency of Tink C++ [ref](https://github.com/google/tink/blob/0d9af8f93fde9705711ff662d1b393770bb666ac/cc/tink_cc_deps.bzl#L77).

Add rapidjson@1.1.0 to BCR

---

tools/bcr_validation.py
tools/verify_stable_archives.py

Context: https://blog.bazel.build/2023/02/15/github-archive-checksum.html

Fix URL stability check and make some validations optional

---

modules/rules_bison/0.2.2/MODULE.bazel
modules/rules_bison/0.2.2/patches/module_dot_bazel.patch
modules/rules_bison/0.2.2/presubmit.yml
modules/rules_bison/0.2.2/source.json
modules/rules_bison/metadata.json

As requested in https://github.com/bazelbuild/bazel-central-registry/issues/204

Add rules_bison v0.2.2

---

modules/lz4-erlang/1.9.2.4/MODULE.bazel
modules/lz4-erlang/1.9.2.4/patches/name.patch
modules/lz4-erlang/1.9.2.4/presubmit.yml
modules/lz4-erlang/1.9.2.4/source.json
modules/lz4-erlang/metadata.json

https://github.com/rabbitmq/lz4-erlang/releases/tag/v1.9.2.4

Add lz4-erlang version 1.9.2.4

---

modules/lz4-erlang/1.9.2.5/MODULE.bazel
modules/lz4-erlang/1.9.2.5/presubmit.yml
modules/lz4-erlang/1.9.2.5/source.json
modules/lz4-erlang/metadata.json

https://github.com/rabbitmq/lz4-erlang/releases/tag/v1.9.2.5

Add lz4-erlang@1.9.2.5

---

modules/rules_python_gazelle_plugin/0.22.0/MODULE.bazel
modules/rules_python_gazelle_plugin/0.22.0/patches/module_dot_bazel_version.patch
modules/rules_python_gazelle_plugin/0.22.0/presubmit.yml
modules/rules_python_gazelle_plugin/0.22.0/source.json
modules/rules_python_gazelle_plugin/metadata.json

rules_python_gazelle_plugin is not published automatically by rules_python

Publish bazelbuild/rules_python_gazelle_plugin@0.22.0

---

modules/gazelle/0.32.0/MODULE.bazel
modules/gazelle/0.32.0/presubmit.yml
modules/gazelle/0.32.0/source.json
modules/gazelle/metadata.json
modules/rules_go/0.41.0/MODULE.bazel
modules/rules_go/0.41.0/patches/bump_gazelle_version.patch
modules/rules_go/0.41.0/presubmit.yml
modules/rules_go/0.41.0/source.json
modules/rules_go/metadata.json

Both modules require each other and thus can't be published separately.

Publish rules_go@v0.41.0 and gazelle@v0.32.0

---

docs/README.md
docs/bcr-policies.md
tools/add_module.py
tools/migrate_to_bzlmod.py
tools/registry.py

Fix spelling mistakes

---

modules/libdeflate/1.18/MODULE.bazel
modules/libdeflate/1.18/patches/add_build_file.patch
modules/libdeflate/1.18/patches/module_dot_bazel.patch
modules/libdeflate/1.18/presubmit.yml
modules/libdeflate/1.18/source.json
modules/libdeflate/metadata.json

Add libdeflate 1.18

---

modules/rabbitmq_ra/2.6.2/MODULE.bazel
modules/rabbitmq_ra/2.6.2/patches/ra.patch
modules/rabbitmq_ra/2.6.2/presubmit.yml
modules/rabbitmq_ra/2.6.2/source.json
modules/rabbitmq_ra/metadata.json

https://github.com/rabbitmq/ra/releases/tag/v2.6.2

Add rabbitmq_ra v2.6.2

---

modules/rabbitmq_osiris/1.6.3/MODULE.bazel
modules/rabbitmq_osiris/1.6.3/patches/rename_module.patch
modules/rabbitmq_osiris/1.6.3/presubmit.yml
modules/rabbitmq_osiris/1.6.3/source.json
modules/rabbitmq_osiris/metadata.json

intended to replace com_github_rabbitmq_osiris at the same version
See #840 for discussion

Add rabbitmq_osiris v1.6.3

---

modules/imath/3.1.9/MODULE.bazel
modules/imath/3.1.9/patches/add_build_file.patch
modules/imath/3.1.9/patches/module_dot_bazel.patch
modules/imath/3.1.9/presubmit.yml
modules/imath/3.1.9/source.json
modules/imath/metadata.json

Add imath 3.1.9

---

modules/rabbitmq_seshat/0.6.1/MODULE.bazel
modules/rabbitmq_seshat/0.6.1/presubmit.yml
modules/rabbitmq_seshat/0.6.1/source.json
modules/rabbitmq_seshat/metadata.json

https://github.com/rabbitmq/seshat/releases

Add rabbitmq_seshat 0.6.1

---

MODULE.bazel
tools/BUILD

Bump rules_python dependency (0.17.3 -> 0.25.0)

Bump rules_python dependency

---

modules/aspect_bazel_lib/metadata.json

See https://github.com/bazelbuild/bazel-central-registry/pull/896#pullrequestreview-1612237260

chore: yank latest aspect_bazel_lib

---

modules/openexr/3.2.0/MODULE.bazel
modules/openexr/3.2.0/patches/module_dot_bazel.patch
modules/openexr/3.2.0/presubmit.yml
modules/openexr/3.2.0/source.json
modules/openexr/metadata.json

Add OpenEXR

---

modules/glog/0.6.0/MODULE.bazel
modules/glog/0.6.0/patches/module_dot_bazel.patch
modules/glog/0.6.0/patches/remove_only_the_first_leading_at.patch
modules/glog/0.6.0/presubmit.yml
modules/glog/0.6.0/source.json
modules/glog/metadata.json

Add glog-0.6.0

---

modules/fmt/10.1.1/MODULE.bazel
modules/fmt/10.1.1/patches/add_build_file.patch
modules/fmt/10.1.1/patches/module_dot_bazel.patch
modules/fmt/10.1.1/presubmit.yml
modules/fmt/10.1.1/source.json
modules/fmt/metadata.json

Add fmt 10.1.1

---

modules/gazelle/metadata.json
modules/rules_go/metadata.json

This PR adds a couple maintainers that have been working on the `rules_go` and `gazelle` Bzlmod experience.

add 2 maintainers to `rules_go` and `gazelle`

---

modules/rules_buf/0.1.1/MODULE.bazel
modules/rules_buf/0.1.1/patches/bzlmod.patch
modules/rules_buf/0.1.1/presubmit.yml
modules/rules_buf/0.1.1/source.json
modules/rules_buf/metadata.json

it comes from aspect-forks until https://github.com/bufbuild/rules_buf/pull/42 is merged, hopefully for the next release

chore: add rules_buf

---

modules/libpng/1.6.40/MODULE.bazel
modules/libpng/1.6.40/patches/add_build_file.patch
modules/libpng/1.6.40/patches/module_dot_bazel.patch
modules/libpng/1.6.40/presubmit.yml
modules/libpng/1.6.40/source.json
modules/libpng/metadata.json

Add libpng 1.6.40

---

README.md

Typography: Github -> GitHub

---

modules/libwebp/1.3.2/MODULE.bazel
modules/libwebp/1.3.2/patches/add_build_file.patch
modules/libwebp/1.3.2/patches/module_dot_bazel.patch
modules/libwebp/1.3.2/presubmit.yml
modules/libwebp/1.3.2/source.json
modules/libwebp/metadata.json

Add libwebp

---

modules/tinyply/2.3.4/MODULE.bazel
modules/tinyply/2.3.4/patches/add_module_dot_bazel.patch
modules/tinyply/2.3.4/presubmit.yml
modules/tinyply/2.3.4/source.json
modules/tinyply/metadata.json

Add tinyply

---

modules/readerwriterqueue/1.0.6/MODULE.bazel
modules/readerwriterqueue/1.0.6/patches/add_build_file.patch
modules/readerwriterqueue/1.0.6/patches/module_dot_bazel.patch
modules/readerwriterqueue/1.0.6/presubmit.yml
modules/readerwriterqueue/1.0.6/source.json
modules/readerwriterqueue/metadata.json

BUILD file contents copies from
https://github.com/mvukov/rules_ros2/blob/main/repositories/readerwriterqueue.BUILD.bazel.

Add readerwriterqueue module to GCR.

---

modules/zstd/1.5.5/MODULE.bazel
modules/zstd/1.5.5/patches/add_build_file.patch
modules/zstd/1.5.5/patches/module_dot_bazel.patch
modules/zstd/1.5.5/presubmit.yml
modules/zstd/1.5.5/source.json
modules/zstd/metadata.json

~~BUILD file contents copied from https://github.com/mvukov/rules_ros2/blob/main/repositories/zstd.BUILD.bazel~~

Add zstd module to GCR.

---

modules/mcap/0.8.0/MODULE.bazel
modules/mcap/0.8.0/patches/add_build_file.patch
modules/mcap/0.8.0/patches/module_dot_bazel.patch
modules/mcap/0.8.0/presubmit.yml
modules/mcap/0.8.0/source.json
modules/mcap/1.2.1/MODULE.bazel
modules/mcap/1.2.1/patches/add_build_file.patch
modules/mcap/1.2.1/patches/module_dot_bazel.patch
modules/mcap/1.2.1/presubmit.yml
modules/mcap/1.2.1/source.json
modules/mcap/metadata.json

BUILD file contents copied from https://github.com/mvukov/rules_ros2/blob/main/repositories/mcap.BUILD.bazel

Add mcap module to GCR.

---

modules/rules_codeowners/0.2.1/MODULE.bazel
modules/rules_codeowners/0.2.1/presubmit.yml
modules/rules_codeowners/0.2.1/source.json
modules/rules_codeowners/metadata.json

Adds [rules_codeowners](https://github.com/zegl/rules_codeowners) to the registry.

Add rules_codeowners

---

.bazelci/presubmit.yml

Prerequisite for https://github.com/bazelbuild/continuous-integration/issues/1813

chore: add configuration for BazelCI

---

modules/doctest/2.4.11/MODULE.bazel
modules/doctest/2.4.11/patches/add_module_dot_bazel.patch
modules/doctest/2.4.11/presubmit.yml
modules/doctest/2.4.11/source.json
modules/doctest/metadata.json

Add doctest 2.4.11

---

modules/asio/1.28.2/MODULE.bazel
modules/asio/1.28.2/patches/add_build_file.patch
modules/asio/1.28.2/patches/module_dot_bazel.patch
modules/asio/1.28.2/presubmit.yml
modules/asio/1.28.2/source.json
modules/asio/metadata.json

I wonder how can I test it locally ..

Add asio 1.28.2

---

modules/cpptoml/0.1.1/MODULE.bazel
modules/cpptoml/0.1.1/patches/add_build_file.patch
modules/cpptoml/0.1.1/patches/module_dot_bazel.patch
modules/cpptoml/0.1.1/presubmit.yml
modules/cpptoml/0.1.1/source.json
modules/cpptoml/metadata.json

- add [cpptoml](https://github.com/skystrife/cpptoml)

feat: add cpptoml

---

modules/onetbb/2021.11.0/MODULE.bazel
modules/onetbb/2021.11.0/patches/add_module_dot_bazel.patch
modules/onetbb/2021.11.0/presubmit.yml
modules/onetbb/2021.11.0/source.json
modules/onetbb/metadata.json

Add oneTBB 2021.11.0

---

modules/glm/metadata.json

As per comment on https://github.com/bazelbuild/bazel-central-registry/pull/1064#issuecomment-1885814257

Add self as bzlmod maintainer for modules/glm

---

modules/zlib-ng/2.0.7/MODULE.bazel
modules/zlib-ng/2.0.7/patches/add_build_file.patch
modules/zlib-ng/2.0.7/patches/add_module_dot_bazel.patch
modules/zlib-ng/2.0.7/presubmit.yml
modules/zlib-ng/2.0.7/source.json
modules/zlib-ng/metadata.json

Add zlib-ng 2.0.7.
Resolves: #567

Add zlib-ng 2.0.7

---

modules/foonathan_memory/0.7.3/MODULE.bazel
modules/foonathan_memory/0.7.3/patches/add_build_file.patch
modules/foonathan_memory/0.7.3/patches/module_dot_bazel.patch
modules/foonathan_memory/0.7.3/presubmit.yml
modules/foonathan_memory/0.7.3/source.json
modules/foonathan_memory/metadata.json

- add [foonathan memory 0.7.3](https://github.com/foonathan/memory/releases/tag/v0.7-3)

feat: add foonathan memory 0.7.3

---

modules/fastcdr/2.1.3/MODULE.bazel
modules/fastcdr/2.1.3/patches/add_build_file.patch
modules/fastcdr/2.1.3/patches/add_cmake_configure_file.patch
modules/fastcdr/2.1.3/patches/module_dot_bazel.patch
modules/fastcdr/2.1.3/presubmit.yml
modules/fastcdr/2.1.3/source.json
modules/fastcdr/metadata.json

- add [fastcdr v2.1.3](https://github.com/eProsima/Fast-CDR/releases/tag/v2.1.3)

feat: add fastcdr v2.1.3

---

modules/libuuid/2.39.3/MODULE.bazel
modules/libuuid/2.39.3/patches/add_build_file.patch
modules/libuuid/2.39.3/patches/module_dot_bazel.patch
modules/libuuid/2.39.3/presubmit.yml
modules/libuuid/2.39.3/source.json
modules/libuuid/metadata.json

add [libuuid](https://packages.ubuntu.com/search?keywords=uuid-dev)

feat: add libuuid

---

modules/qdldl/0.1.7/MODULE.bazel
modules/qdldl/0.1.7/patches/add_build_file.patch
modules/qdldl/0.1.7/patches/add_cmake_configure_file.patch
modules/qdldl/0.1.7/patches/module_dot_bazel.patch
modules/qdldl/0.1.7/presubmit.yml
modules/qdldl/0.1.7/source.json
modules/qdldl/metadata.json

- add [qdldl](https://github.com/osqp/qdldl/releases/tag/v0.1.7)

feat: add qdldl

---

modules/suitesparse/7.6.0/MODULE.bazel
modules/suitesparse/7.6.0/patches/add_build_file.patch
modules/suitesparse/7.6.0/patches/module_dot_bazel.patch
modules/suitesparse/7.6.0/presubmit.yml
modules/suitesparse/7.6.0/source.json
modules/suitesparse/metadata.json

add [suitesparse amd](https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.6.0)

feat: add suitesparse amd

---

modules/bzlparty_tools/0.2.0/MODULE.bazel
modules/bzlparty_tools/0.2.0/presubmit.yml
modules/bzlparty_tools/0.2.0/source.json
modules/bzlparty_tools/metadata.json

Project: [bzlparty_tools](https://github.com/bzlparty/tools/)
Release: [v0.2.0](https://github.com/bzlparty/tools/releases/tag/v0.2.0)

Add bzlparty_tools@0.2.0

---

modules/swift_argument_parser/1.3.0/MODULE.bazel
modules/swift_argument_parser/1.3.0/patches/add_build_file.patch
modules/swift_argument_parser/1.3.0/patches/module_dot_bazel.patch
modules/swift_argument_parser/1.3.0/presubmit.yml
modules/swift_argument_parser/1.3.0/source.json
modules/swift_argument_parser/metadata.json

https://github.com/apple/swift-argument-parser/releases/tag/1.3.0

Add Swift Argument Parser 1.3.0

---

tools/BUILD
tools/update_integrity.py
tools/update_integrity_test.sh

I felt bad for not adding tests in https://github.com/bazelbuild/bazel-central-registry/pull/1407 so here we go.

Add integration test for update_integrity tool

---

modules/cmake_configure_file/0.1.0/MODULE.bazel
modules/cmake_configure_file/0.1.0/presubmit.yml
modules/cmake_configure_file/0.1.0/source.json
modules/cmake_configure_file/metadata.json

- add [cmake_configure_file](https://github.com/wep21/cmake_configure_file/releases/tag/v0.1.0) from [drake](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/cmake_configure_file.bzl)

feat: add cmake configure file

---

modules/flip/1.3/MODULE.bazel
modules/flip/1.3/patches/add_build_file.patch
modules/flip/1.3/patches/module_dot_bazel.patch
modules/flip/1.3/presubmit.yml
modules/flip/1.3/source.json
modules/flip/metadata.json

Add flip 1.3

---

modules/rules_testing/0.6.0/MODULE.bazel
modules/rules_testing/0.6.0/patches/module_dot_bazel_version.patch
modules/rules_testing/0.6.0/presubmit.yml
modules/rules_testing/0.6.0/source.json
modules/rules_testing/metadata.json

Release: https://github.com/bazelbuild/rules_testing/releases/tag/v0.6.0
Author: @comius

rules_testing@0.6.0

---

modules/cpplint/1.6.1/MODULE.bazel
modules/cpplint/1.6.1/patches/add_build_file.patch
modules/cpplint/1.6.1/patches/module_dot_bazel.patch
modules/cpplint/1.6.1/presubmit.yml
modules/cpplint/1.6.1/source.json
modules/cpplint/metadata.json

- add [cpplint](https://github.com/cpplint/cpplint/releases/tag/1.6.1)

feat: add cpplint

---

modules/glog/0.7.0/MODULE.bazel
modules/glog/0.7.0/patches/module_dot_bazel.patch
modules/glog/0.7.0/presubmit.yml
modules/glog/0.7.0/source.json
modules/glog/metadata.json

Add glog 0.7.0

---

modules/glm/1.0.0/MODULE.bazel
modules/glm/1.0.0/patches/add_build_file.patch
modules/glm/1.0.0/patches/add_module_dot_bazel.patch
modules/glm/1.0.0/presubmit.yml
modules/glm/1.0.0/source.json
modules/glm/metadata.json

Add glm 1.0.0

---

modules/libpng/1.6.41/MODULE.bazel
modules/libpng/1.6.41/patches/add_build_file.patch
modules/libpng/1.6.41/patches/module_dot_bazel.patch
modules/libpng/1.6.41/presubmit.yml
modules/libpng/1.6.41/source.json
modules/libpng/metadata.json

Add libpng 1.6.41

---

modules/libpng/1.6.42/MODULE.bazel
modules/libpng/1.6.42/patches/add_build_file.patch
modules/libpng/1.6.42/patches/module_dot_bazel.patch
modules/libpng/1.6.42/presubmit.yml
modules/libpng/1.6.42/source.json
modules/libpng/metadata.json

Add libpng 1.6.42

---

tools/migrate_to_bzlmod.py

Fix spelling

---

modules/tinyformat/2.3.0/MODULE.bazel
modules/tinyformat/2.3.0/patches/add_build_file.patch
modules/tinyformat/2.3.0/patches/module_dot_bazel.patch
modules/tinyformat/2.3.0/presubmit.yml
modules/tinyformat/2.3.0/source.json
modules/tinyformat/metadata.json

Add tinyformat 2.3.0

---

tools/bcr_validation.py

Addressing https://github.com/bazelbuild/bazel-central-registry/pull/1591#discussion_r1517371565

Check module name conflict when ignoring casing

---

modules/emboss/2024.0304.184309/MODULE.bazel
modules/emboss/2024.0304.184309/patches/module_dot_bazel.patch
modules/emboss/2024.0304.184309/presubmit.yml
modules/emboss/2024.0304.184309/source.json
modules/emboss/metadata.json

Release: https://github.com/google/emboss/releases/tag/v2024.0304.184309
Used by:
* https://github.com/google/ecclesia-machine-management

emboss@2024.0304.184309

---

modules/s2geometry/0.10.0/MODULE.bazel
modules/s2geometry/0.10.0/patches/add_build_file.patch
modules/s2geometry/0.10.0/patches/module_dot_bazel.patch
modules/s2geometry/0.10.0/presubmit.yml
modules/s2geometry/0.10.0/source.json
modules/s2geometry/metadata.json

Release: https://github.com/google/s2geometry/releases/tag/v0.10.0
Used by:
* https://github.com/opencomputeproject/ocp-diag-core-cpp

s2geometry@0.10.0

---

.github/workflows/dismiss_approvals.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml

To get fix from https://github.com/bazelbuild/continuous-integration/pull/1929

Update GitHub Actions for BCR Reviewer

---

modules/libarchive/3.7.2.bcr.1/MODULE.bazel
modules/libarchive/3.7.2.bcr.1/patches/build_with_bazel.patch
modules/libarchive/3.7.2.bcr.1/patches/fix_bzip2_includes.patch
modules/libarchive/3.7.2.bcr.1/presubmit.yml
modules/libarchive/3.7.2.bcr.1/source.json
modules/libarchive/metadata.json

I forgot to include `HAVE_REGEX_H`, so try to fix the windows build if we're doing another release anyway :)

Libarchive@3.7.2.bcr.1

---

modules/libarchive/3.7.2.bcr.2/MODULE.bazel
modules/libarchive/3.7.2.bcr.2/patches/build_with_bazel.patch
modules/libarchive/3.7.2.bcr.2/patches/fix_bzip2_includes.patch
modules/libarchive/3.7.2.bcr.2/presubmit.yml
modules/libarchive/3.7.2.bcr.2/source.json
modules/libarchive/metadata.json

I had skimped on the #defines so some functionality was not compiled in.

libarchive@3.7.2.bcr.2

---

modules/crc32c/1.1.0/MODULE.bazel
modules/crc32c/1.1.0/patches/add_build_file.patch
modules/crc32c/1.1.0/patches/module_dot_bazel.patch
modules/crc32c/1.1.0/presubmit.yml
modules/crc32c/1.1.0/source.json
modules/crc32c/metadata.json

Release: https://github.com/google/crc32c/releases/tag/1.1.0
Used by:

crc32c@1.1.0

---

modules/rules_coreutils/1.0.0-alpha.8/MODULE.bazel
modules/rules_coreutils/1.0.0-alpha.8/presubmit.yml
modules/rules_coreutils/1.0.0-alpha.8/source.json
modules/rules_coreutils/metadata.json

Adds new `coreutils_sha*sum` rules.

feat(rules_coreutils): add `1.0.0-alpha.8`

---

modules/flatbuffers/24.3.7/MODULE.bazel
modules/flatbuffers/24.3.7/patches/extensions_dot_bzl.patch
modules/flatbuffers/24.3.7/patches/module_dot_bazel.patch
modules/flatbuffers/24.3.7/presubmit.yml
modules/flatbuffers/24.3.7/source.json
modules/flatbuffers/metadata.json

Release: https://github.com/google/flatbuffers/releases/tag/v24.3.7
Related to #1604

flatbuffers@24.3.7

---

modules/zstd/metadata.json

Follow up on https://github.com/bazelbuild/bazel-central-registry/pull/1730#discussion_r1552125173

zstd: Add my GitHub ID

---

modules/tcmalloc/0.0.0-20240411-5ed309d/MODULE.bazel
modules/tcmalloc/0.0.0-20240411-5ed309d/patches/0001-Add-MODULE.bazel.patch
modules/tcmalloc/0.0.0-20240411-5ed309d/presubmit.yml
modules/tcmalloc/0.0.0-20240411-5ed309d/source.json
modules/tcmalloc/metadata.json

Upstream PR https://github.com/google/tcmalloc/pull/230

Add tcmalloc

---

modules/highwayhash/0.0.0-20240305-5ad3bf8/MODULE.bazel
modules/highwayhash/0.0.0-20240305-5ad3bf8/patches/add_build_file.patch
modules/highwayhash/0.0.0-20240305-5ad3bf8/patches/module_dot_bazel.patch
modules/highwayhash/0.0.0-20240305-5ad3bf8/presubmit.yml
modules/highwayhash/0.0.0-20240305-5ad3bf8/source.json
modules/highwayhash/metadata.json

https://github.com/google/highwayhash/tree/5ad3bf8444cfc663b11bf367baaa31f36e7ff7c8
Used by:

highwayhash@0.0.0-20240305-5ad3bf8

---

modules/riegeli/0.0.0-20231123-411cda7/MODULE.bazel
modules/riegeli/0.0.0-20231123-411cda7/patches/build.patch
modules/riegeli/0.0.0-20231123-411cda7/patches/dot_bazelrc.patch
modules/riegeli/0.0.0-20231123-411cda7/patches/module_dot_bazel.patch
modules/riegeli/0.0.0-20231123-411cda7/presubmit.yml
modules/riegeli/0.0.0-20231123-411cda7/source.json
modules/riegeli/metadata.json

Release: https://github.com/google/riegeli/archive/411cda7f6aa81f8b8591b04cf141b1decdcc928c.tar.gz
Used by:
* https://github.com/google/fuzztest

riegeli@0.0.0-20231123-411cda7

---

modules/libdeflate/1.20/MODULE.bazel
modules/libdeflate/1.20/patches/add_build_file.patch
modules/libdeflate/1.20/patches/module_dot_bazel.patch
modules/libdeflate/1.20/presubmit.yml
modules/libdeflate/1.20/source.json
modules/libdeflate/metadata.json

Add libdeflate 1.20

---

modules/ape/1.0.0-beta.2/MODULE.bazel
modules/ape/1.0.0-beta.2/presubmit.yml
modules/ape/1.0.0-beta.2/source.json
modules/ape/metadata.json

Brings Apple Silicon and MinGW shell support! Yay.

feat(ape): add `1.0.0-beta.2`

---

modules/bliss/0.73/MODULE.bazel
modules/bliss/0.73/patches/add_build_file.patch
modules/bliss/0.73/patches/bliss-0.73.patch
modules/bliss/0.73/patches/module_dot_bazel.patch
modules/bliss/0.73/presubmit.yml
modules/bliss/0.73/source.json
modules/bliss/metadata.json

Release: http://www.tcs.hut.fi/Software/bliss/bliss-0.73.zip
Used by: 
* https://github.com/google/or-tools

bliss@0.73

---

modules/rules_diff/1.0.0-beta.2/MODULE.bazel
modules/rules_diff/1.0.0-beta.2/presubmit.yml
modules/rules_diff/1.0.0-beta.2/source.json
modules/rules_diff/metadata.json

Apple Silicon support via `ape@1.0.0-beta.2`.

feat(rules_diff): add `1.0.0-beta.2`

---

modules/libwebp/1.4.0/MODULE.bazel
modules/libwebp/1.4.0/patches/add_build_file.patch
modules/libwebp/1.4.0/patches/module_dot_bazel.patch
modules/libwebp/1.4.0/presubmit.yml
modules/libwebp/1.4.0/source.json
modules/libwebp/metadata.json

Add libwebp 1.4.0

---

modules/civetweb/1.16/MODULE.bazel
modules/civetweb/1.16/patches/add_build_file.patch
modules/civetweb/1.16/patches/module_dot_bazel.patch
modules/civetweb/1.16/presubmit.yml
modules/civetweb/1.16/source.json
modules/civetweb/metadata.json

Release: https://github.com/civetweb/civetweb/releases/tag/v1.16
Used by:
* https://github.com/jupp0r/prometheus-cpp

civetweb@1.16

---

modules/cpuinfo/0.0.0-20231104-d6860c4/MODULE.bazel
modules/cpuinfo/0.0.0-20231104-d6860c4/patches/module_dot_bazel.patch
modules/cpuinfo/0.0.0-20231104-d6860c4/presubmit.yml
modules/cpuinfo/0.0.0-20231104-d6860c4/source.json
modules/cpuinfo/metadata.json

Used by:
* https://github.com/google/mediapipe
* https://github.com/google/ruy

cpuinfo@0.0.0-20231104-d6860c4

---

modules/fp16/0.0.0-20210320-0a92994/MODULE.bazel
modules/fp16/0.0.0-20210320-0a92994/patches/add_build_file.patch
modules/fp16/0.0.0-20210320-0a92994/patches/module_dot_bazel.patch
modules/fp16/0.0.0-20210320-0a92994/presubmit.yml
modules/fp16/0.0.0-20210320-0a92994/source.json
modules/fp16/metadata.json

fp16@0.0.0-20210320-0a92994

---

modules/fxdiv/0.0.0-20201209-63058ef/MODULE.bazel
modules/fxdiv/0.0.0-20201209-63058ef/patches/module_dot_bazel.patch
modules/fxdiv/0.0.0-20201209-63058ef/presubmit.yml
modules/fxdiv/0.0.0-20201209-63058ef/source.json
modules/fxdiv/metadata.json

Used by:
* https://github.com/Maratyszcza/pthreadpool

fxdiv@0.0.0-20201209-63058ef

---

modules/ruy/0.0.0-20200416-9f53ba4/MODULE.bazel
modules/ruy/0.0.0-20200416-9f53ba4/patches/module_dot_bazel.patch
modules/ruy/0.0.0-20200416-9f53ba4/presubmit.yml
modules/ruy/0.0.0-20200416-9f53ba4/source.json
modules/ruy/metadata.json

ruy@0.0.0-20200416-9f53ba4

---

modules/rules_coreutils/1.0.0-beta.1/MODULE.bazel
modules/rules_coreutils/1.0.0-beta.1/presubmit.yml
modules/rules_coreutils/1.0.0-beta.1/source.json
modules/rules_coreutils/metadata.json

Brings Apple Silicon, remote execution and Windows testing.

feat: add `rules_coreutils@1.0.0-beta.1`

---

modules/highway/1.1.0/MODULE.bazel
modules/highway/1.1.0/patches/module_dot_bazel.patch
modules/highway/1.1.0/presubmit.yml
modules/highway/1.1.0/source.json
modules/highway/metadata.json

Release: https://github.com/google/highway/releases/tag/1.1.0

highway@1.1.0

---

modules/pthreadpool/0.0.0-20230829-4fe0e1e/MODULE.bazel
modules/pthreadpool/0.0.0-20230829-4fe0e1e/patches/module_dot_bazel.patch
modules/pthreadpool/0.0.0-20230829-4fe0e1e/patches/pthreadpool.patch
modules/pthreadpool/0.0.0-20230829-4fe0e1e/presubmit.yml
modules/pthreadpool/0.0.0-20230829-4fe0e1e/source.json
modules/pthreadpool/metadata.json

pthreadpool@0.0.0-20230829-4fe0e1e

---

modules/tree-sitter-bazel/0.22.6/MODULE.bazel
modules/tree-sitter-bazel/0.22.6/presubmit.yml
modules/tree-sitter-bazel/0.22.6/source.json
modules/tree-sitter-bazel/metadata.json

Update `tree-sitter-bazel` to `0.22.6`.

Update `tree-sitter-bazel` to `0.22.6`.

---

modules/jwt_verify_lib/0.0.0-20230517-b59e807/MODULE.bazel
modules/jwt_verify_lib/0.0.0-20230517-b59e807/patches/jwt_verify_lib.patch
modules/jwt_verify_lib/0.0.0-20230517-b59e807/patches/module_dot_bazel.patch
modules/jwt_verify_lib/0.0.0-20230517-b59e807/presubmit.yml
modules/jwt_verify_lib/0.0.0-20230517-b59e807/source.json
modules/jwt_verify_lib/metadata.json

Used by:
Related to: https://github.com/google/jwt_verify_lib/pull/103

jwt_verify_lib@0.0.0-20230517-b59e807

---

modules/rules_squashfs/1.0.0-alpha.2/MODULE.bazel
modules/rules_squashfs/1.0.0-alpha.2/presubmit.yml
modules/rules_squashfs/1.0.0-alpha.2/source.json
modules/rules_squashfs/metadata.json

Updates for `ToolchainInfo` changes in `toolchain_utils`.

feat: add `rules_squashfs@1.0.0-alpha.2`

---

modules/proto-converter/0.0.0-20230607-d77ff30/MODULE.bazel
modules/proto-converter/0.0.0-20230607-d77ff30/patches/module_dot_bazel.patch
modules/proto-converter/0.0.0-20230607-d77ff30/patches/proto-converter.patch
modules/proto-converter/0.0.0-20230607-d77ff30/presubmit.yml
modules/proto-converter/0.0.0-20230607-d77ff30/source.json
modules/proto-converter/metadata.json

Used by:
* https://github.com/grpc-ecosystem/grpc-httpjson-transcoding

proto-converter@0.0.0-20230607-d77ff30

---

modules/su-exec/0.0.0-20221219-4c3bb42/MODULE.bazel
modules/su-exec/0.0.0-20221219-4c3bb42/patches/add_build_file.patch
modules/su-exec/0.0.0-20221219-4c3bb42/patches/module_dot_bazel.patch
modules/su-exec/0.0.0-20221219-4c3bb42/presubmit.yml
modules/su-exec/0.0.0-20221219-4c3bb42/source.json
modules/su-exec/metadata.json

su-exec@0.0.0-20221219-4c3bb42

---

modules/cpuinfo/metadata.json

cpuinfo: Add maintainer

---

modules/cpuinfo/0.0.0-20240417-3c8b153/MODULE.bazel
modules/cpuinfo/0.0.0-20240417-3c8b153/patches/module_dot_bazel.patch
modules/cpuinfo/0.0.0-20240417-3c8b153/presubmit.yml
modules/cpuinfo/0.0.0-20240417-3c8b153/source.json
modules/cpuinfo/metadata.json

Add cpuinfo@3c8b1533ac03dd6531ab6e7b9245d488f13a82a5

cpuinfo@3c8b1533ac03dd6531ab6e7b9245d488f13a82a5

---

modules/hypothesis/0.0.0-20240425-3acfea6/MODULE.bazel
modules/hypothesis/0.0.0-20240425-3acfea6/patches/add_build_file.patch
modules/hypothesis/0.0.0-20240425-3acfea6/patches/module_dot_bazel.patch
modules/hypothesis/0.0.0-20240425-3acfea6/presubmit.yml
modules/hypothesis/0.0.0-20240425-3acfea6/source.json
modules/hypothesis/metadata.json

Add hypothesis@0.0.0-20240425-3acfea6

Add hypothesis@0.0.0-20240425-3acfea6

---

modules/xds/0.0.0-20240423-555b57e/MODULE.bazel
modules/xds/0.0.0-20240423-555b57e/patches/bzlmod.patch
modules/xds/0.0.0-20240423-555b57e/presubmit.yml
modules/xds/0.0.0-20240423-555b57e/source.json
modules/xds/metadata.json

Used by grpc, envoy and probably more

Add cncf/xds

---

tools/registry.py

as this seems to be the recommended approach as suggested in https://github.com/bazelbuild/bazel-central-registry/pull/2161#pullrequestreview-2091488119.

Fix update_integrity tool to support relative paths

---

modules/quill/4.3.0/MODULE.bazel
modules/quill/4.3.0/patches/add_build_file.patch
modules/quill/4.3.0/patches/module_dot_bazel.patch
modules/quill/4.3.0/presubmit.yml
modules/quill/4.3.0/source.json
modules/quill/metadata.json

`quill` is a C++17 low latency logging library.  The project can be found [here](https://github.com/odygrd/quill)

add quill version 4.3.0

---

modules/grpc/1.62.1.bcr.2/MODULE.bazel
modules/grpc/1.62.1.bcr.2/patches/py_grpc_library.patch
modules/grpc/1.62.1.bcr.2/patches/update_module_bazel.patch
modules/grpc/1.62.1.bcr.2/presubmit.yml
modules/grpc/1.62.1.bcr.2/source.json
modules/grpc/metadata.json

This also adds the corresponding test targets to avoid backsliding.

Fix Python support for gRPC

---

modules/google_benchmark/1.8.4/MODULE.bazel
modules/google_benchmark/1.8.4/presubmit.yml
modules/google_benchmark/1.8.4/source.json
modules/google_benchmark/metadata.json

google_benchmark@1.8.4

---

modules/textforge/1.0.0/MODULE.bazel
modules/textforge/1.0.0/presubmit.yml
modules/textforge/1.0.0/source.json
modules/textforge/metadata.json

Adding the TextForge module to generate files from JSON data and a template. It uses Jinja2 to render the content of the generated files from the JSON data.

Adding version 1.0.0 of textforge

---

modules/quill/4.4.0/MODULE.bazel
modules/quill/4.4.0/presubmit.yml
modules/quill/4.4.0/source.json
modules/quill/metadata.json

latest version upstreams the bazel files

add quill 4.4.0

---

modules/rules_coreutils/1.0.0-beta.3/MODULE.bazel
modules/rules_coreutils/1.0.0-beta.3/presubmit.yml
modules/rules_coreutils/1.0.0-beta.3/source.json
modules/rules_coreutils/metadata.json

Switches to the statically linked UUtils `musl` variant.

feat: add `rules_coreutils@1.0.0-beta.3`

---

modules/pico-sdk/1.6.0-rc1/MODULE.bazel
modules/pico-sdk/1.6.0-rc1/patches/0001-Minimal-fixes-for-BCR.patch
modules/pico-sdk/1.6.0-rc1/patches/0002-Add-Bazel-example-for-BCR.patch
modules/pico-sdk/1.6.0-rc1/patches/0003-Pioasm-MSVC-workaround.patch
modules/pico-sdk/1.6.0-rc1/presubmit.yml
modules/pico-sdk/1.6.0-rc1/source.json
modules/pico-sdk/metadata.json

Add early testing release candidate for the Pico SDK.

Add pico-sdk@1.6.0-rc1

---

modules/zsync3/0.0.2/MODULE.bazel
modules/zsync3/0.0.2/presubmit.yml
modules/zsync3/0.0.2/source.json
modules/zsync3/metadata.json

Add https://github.com/lalten/zsync

Add zsync3

---

modules/rules_xz/1.0.0-beta.1/MODULE.bazel
modules/rules_xz/1.0.0-beta.1/presubmit.yml
modules/rules_xz/1.0.0-beta.1/source.json
modules/rules_xz/metadata.json

```py
load("@rules_xz//xz/compress:defs.bzl", "xz_compress")
load("@rules_xz//xz/decompress:defs.bzl", "xz_decompress")
xz_compress(
name = "compress",
src = "//fixture:hello-world.txt",
)
xz_decompress(
name = "decompress",
src = ":compress",
)
```
Hermetic through `@ape//:xz` binary.

feat: add `rules_xz@1.0.0-beta.1`

---

modules/delaunator-cpp/0.0.0-20181007-c1521f6/MODULE.bazel
modules/delaunator-cpp/0.0.0-20181007-c1521f6/overlay/BUILD.bazel
modules/delaunator-cpp/0.0.0-20181007-c1521f6/overlay/MODULE.bazel
modules/delaunator-cpp/0.0.0-20181007-c1521f6/presubmit.yml
modules/delaunator-cpp/0.0.0-20181007-c1521f6/source.json
modules/delaunator-cpp/metadata.json

delaunator-cpp@c1521f6

---

.editorconfig

Add a [EditorConfig](https://editorconfig.org/) file 
- Unify JSON, YAML indentation
- Add new line at the end of every file

Add a EditorConfig file 

---

modules/grpc-proto/0.0.0-20240627-ec30f58/MODULE.bazel
modules/grpc-proto/0.0.0-20240627-ec30f58/patches/module_dot_bazel.patch
modules/grpc-proto/0.0.0-20240627-ec30f58/presubmit.yml
modules/grpc-proto/0.0.0-20240627-ec30f58/source.json
modules/grpc-proto/metadata.json

Used by : 
* https://github.com/grpc/grpc-java

grpc-proto@0.0.0-20240627-ec30f58

---

modules/glew/2.2.0/MODULE.bazel
modules/glew/2.2.0/overlay/BUILD.bazel
modules/glew/2.2.0/overlay/MODULE.bazel
modules/glew/2.2.0/presubmit.yml
modules/glew/2.2.0/source.json
modules/glew/metadata.json

glew@2.2.0

---

modules/fastcdr/2.2.2/MODULE.bazel
modules/fastcdr/2.2.2/patches/add_build_file.patch
modules/fastcdr/2.2.2/patches/module_dot_bazel.patch
modules/fastcdr/2.2.2/presubmit.yml
modules/fastcdr/2.2.2/source.json
modules/fastcdr/metadata.json

feat: add fastcdr v2.2.2

---

modules/freertos/10.5.1/MODULE.bazel
modules/freertos/10.5.1/patches/bazel.patch
modules/freertos/10.5.1/presubmit.yml
modules/freertos/10.5.1/source.json
modules/freertos/metadata.json

Eventually I would like to add the `BUILD.bazel` and `MODULE.bazel` files directly to FreeRTOS. Started the conversation with maintainers here: https://forums.freertos.org/t/bazel-build-file-for-the-freertos-kernel/20963

Add FreeRTOS

---

tools/registry.py

Add a workaround for downloading private github archives

---

modules/libconfig/1.7.3/MODULE.bazel
modules/libconfig/1.7.3/patches/add_build_file.patch
modules/libconfig/1.7.3/patches/module_dot_bazel.patch
modules/libconfig/1.7.3/presubmit.yml
modules/libconfig/1.7.3/source.json
modules/libconfig/metadata.json

PR for #2455
Release: https://github.com/hyperrealm/libconfig/releases/tag/v1.7.3
Used by:
* https://github.com/kubevirt/kubevirt
* https://github.com/JFreegman/toxic

libconfig@1.7.3 (#2455)

---

modules/flatbuffers/24.3.25/MODULE.bazel
modules/flatbuffers/24.3.25/patches/bzlmod.patch
modules/flatbuffers/24.3.25/patches/extensions_dot_bzl.patch
modules/flatbuffers/24.3.25/patches/module_dot_bazel.patch
modules/flatbuffers/24.3.25/presubmit.yml
modules/flatbuffers/24.3.25/source.json
modules/flatbuffers/metadata.json

https://github.com/google/flatbuffers/archive/refs/tags/v24.3.25.tar.gz is the only download url that flatbuffers provides.

Add flatbuffers@24.3.25.

---

modules/libfuse/3.16.2/MODULE.bazel
modules/libfuse/3.16.2/overlay/BUILD.bazel
modules/libfuse/3.16.2/overlay/MODULE.bazel
modules/libfuse/3.16.2/presubmit.yml
modules/libfuse/3.16.2/source.json
modules/libfuse/metadata.json

https://github.com/libfuse/libfuse

Add libfuse

---

modules/libcpuid/0.6.5/MODULE.bazel
modules/libcpuid/0.6.5/patches/add_build_file.patch
modules/libcpuid/0.6.5/patches/module_dot_bazel.patch
modules/libcpuid/0.6.5/presubmit.yml
modules/libcpuid/0.6.5/source.json
modules/libcpuid/metadata.json

added libcpuid

---

modules/squashfuse/0.5.2/MODULE.bazel
modules/squashfuse/0.5.2/overlay/BUILD.bazel
modules/squashfuse/0.5.2/overlay/MODULE.bazel
modules/squashfuse/0.5.2/presubmit.yml
modules/squashfuse/0.5.2/source.json
modules/squashfuse/metadata.json

https://github.com/vasi/squashfuse
Depends on https://github.com/bazelbuild/bazel-central-registry/pull/2509

Add squashfuse

---

tools/registry.py

Fix undefined variable error in `registry.py`

---

modules/foonathan_memory/0.7.3.bcr.2/MODULE.bazel
modules/foonathan_memory/0.7.3.bcr.2/patches/add_build_file.patch
modules/foonathan_memory/0.7.3.bcr.2/patches/module_dot_bazel.patch
modules/foonathan_memory/0.7.3.bcr.2/presubmit.yml
modules/foonathan_memory/0.7.3.bcr.2/source.json
modules/foonathan_memory/metadata.json

- update foonathan memory to build with rules_cc
- need skip-url-stability-check

feat: update foonathan memory

---

modules/boost.static_assert/1.83.0/MODULE.bazel
modules/boost.static_assert/1.83.0/patches/add_build_file.patch
modules/boost.static_assert/1.83.0/patches/module_dot_bazel.patch
modules/boost.static_assert/1.83.0/presubmit.yml
modules/boost.static_assert/1.83.0/source.json
modules/boost.static_assert/metadata.json

- add [boost.static_assert](http://boost.org/libs/static_assert)
- need skip url sanity check

feat: add boost static_assert

---

modules/boost.assert/1.83.0/MODULE.bazel
modules/boost.assert/1.83.0/patches/add_build_file.patch
modules/boost.assert/1.83.0/patches/module_dot_bazel.patch
modules/boost.assert/1.83.0/presubmit.yml
modules/boost.assert/1.83.0/source.json
modules/boost.assert/metadata.json

- add [boost.assert](http://boost.org/libs/assert)
- need skip url sanity check

feat: add boost assert

---

modules/swift-syntax/510.0.3/MODULE.bazel
modules/swift-syntax/510.0.3/patches/fix_module_dot_bazel_versions.patch
modules/swift-syntax/510.0.3/presubmit.yml
modules/swift-syntax/510.0.3/source.json
modules/swift-syntax/metadata.json

Publishes: https://github.com/swiftlang/swift-syntax/releases/tag/510.0.3

Add swiftlang/swift-syntax version 510.0.3

---

modules/picotool/1.1.3-rc1/MODULE.bazel
modules/picotool/1.1.3-rc1/presubmit.yml
modules/picotool/1.1.3-rc1/source.json
modules/picotool/metadata.json

This will need the `skip-url-stability-check` label.

Add picotool@1.1.3-rc1

---

modules/boost.type_traits/1.83.0/MODULE.bazel
modules/boost.type_traits/1.83.0/patches/add_build_file.patch
modules/boost.type_traits/1.83.0/patches/module_dot_bazel.patch
modules/boost.type_traits/1.83.0/presubmit.yml
modules/boost.type_traits/1.83.0/source.json
modules/boost.type_traits/metadata.json

- add [boost.type_traits](http://boost.org/libs/type_traits)

feat: add boost.type_traits

---

modules/boost.preprocessor/1.83.0/MODULE.bazel
modules/boost.preprocessor/1.83.0/patches/add_build_file.patch
modules/boost.preprocessor/1.83.0/patches/module_dot_bazel.patch
modules/boost.preprocessor/1.83.0/presubmit.yml
modules/boost.preprocessor/1.83.0/source.json
modules/boost.preprocessor/metadata.json

- add [boost.preprocessor](http://boost.org/libs/preprocessor)

feat: add boost.preprocessor

---

modules/boost.core/1.83.0/MODULE.bazel
modules/boost.core/1.83.0/patches/add_build_file.patch
modules/boost.core/1.83.0/patches/module_dot_bazel.patch
modules/boost.core/1.83.0/presubmit.yml
modules/boost.core/1.83.0/source.json
modules/boost.core/metadata.json

- add [boost.core](http://boost.org/libs/core)

feat: add boost.core

---

modules/boost.array/1.83.0/MODULE.bazel
modules/boost.array/1.83.0/patches/add_build_file.patch
modules/boost.array/1.83.0/patches/module_dot_bazel.patch
modules/boost.array/1.83.0/presubmit.yml
modules/boost.array/1.83.0/source.json
modules/boost.array/metadata.json

- add [boost.array](http://boost.org/libs/array)

feat: add boost.array

---

modules/boost.array/metadata.json
modules/boost.assert/metadata.json
modules/boost.config/metadata.json
modules/boost.core/metadata.json
modules/boost.preprocessor/metadata.json
modules/boost.static_assert/metadata.json
modules/boost.throw_exception/metadata.json
modules/boost.type_traits/metadata.json

Add maintainer to boost libs

---

modules/boost.uuid/1.83.0/MODULE.bazel
modules/boost.uuid/1.83.0/overlay/BUILD.bazel
modules/boost.uuid/1.83.0/overlay/MODULE.bazel
modules/boost.uuid/1.83.0/presubmit.yml
modules/boost.uuid/1.83.0/source.json
modules/boost.uuid/metadata.json

boost.uuid@1.83.0

---

MODULE.bazel

Bump rules_python to 0.34.0

---

modules/fremtind_rules_vitest/0.2.0/MODULE.bazel
modules/fremtind_rules_vitest/0.2.0/patches/module_dot_bazel_version.patch
modules/fremtind_rules_vitest/0.2.0/presubmit.yml
modules/fremtind_rules_vitest/0.2.0/source.json
modules/fremtind_rules_vitest/metadata.json

Release https://github.com/fremtind/rules_vitest/releases/tag/v0.2.0

Added fremtind_rules_vitest 0.2.0

---

modules/rules_python_gazelle_plugin/metadata.json

The same has been done a while ago in the `rules_python` project already.
See #2401

Add aignas as a maintainer to rules_python_gazelle_plugin

---

modules/boost.typeof/1.83.0/MODULE.bazel
modules/boost.typeof/1.83.0/overlay/BUILD.bazel
modules/boost.typeof/1.83.0/overlay/MODULE.bazel
modules/boost.typeof/1.83.0/presubmit.yml
modules/boost.typeof/1.83.0/source.json
modules/boost.typeof/metadata.json

- add [boost.typeof](http://boost.org/libs/typeof)

feat: add boost.typeof

---

modules/boost.integer/1.83.0/MODULE.bazel
modules/boost.integer/1.83.0/overlay/BUILD.bazel
modules/boost.integer/1.83.0/overlay/MODULE.bazel
modules/boost.integer/1.83.0/presubmit.yml
modules/boost.integer/1.83.0/source.json
modules/boost.integer/metadata.json

- add [boost.integer](http://boost.org/libs/integer)

feat: add boost.integer

---

modules/boost.io/1.83.0/MODULE.bazel
modules/boost.io/1.83.0/overlay/BUILD.bazel
modules/boost.io/1.83.0/overlay/MODULE.bazel
modules/boost.io/1.83.0/presubmit.yml
modules/boost.io/1.83.0/source.json
modules/boost.io/metadata.json

- add [boost.io](http://boost.org/libs/io)

feat: add boost.io

---

modules/boost.concept_check/1.83.0/MODULE.bazel
modules/boost.concept_check/1.83.0/overlay/BUILD.bazel
modules/boost.concept_check/1.83.0/overlay/MODULE.bazel
modules/boost.concept_check/1.83.0/presubmit.yml
modules/boost.concept_check/1.83.0/source.json
modules/boost.concept_check/metadata.json

- add [boost.concept_check](http://boost.org/libs/concept_check)

feat: add boost.concept_check

---

modules/boost.move/1.83.0/MODULE.bazel
modules/boost.move/1.83.0/overlay/BUILD.bazel
modules/boost.move/1.83.0/overlay/MODULE.bazel
modules/boost.move/1.83.0/presubmit.yml
modules/boost.move/1.83.0/source.json
modules/boost.move/metadata.json

feat: add boost.move

---

modules/boost.predef/1.83.0/MODULE.bazel
modules/boost.predef/1.83.0/overlay/BUILD.bazel
modules/boost.predef/1.83.0/overlay/MODULE.bazel
modules/boost.predef/1.83.0/presubmit.yml
modules/boost.predef/1.83.0/source.json
modules/boost.predef/metadata.json

feat: add boost.predef

---

modules/boost.tuple/1.83.0/MODULE.bazel
modules/boost.tuple/1.83.0/overlay/BUILD.bazel
modules/boost.tuple/1.83.0/overlay/MODULE.bazel
modules/boost.tuple/1.83.0/presubmit.yml
modules/boost.tuple/1.83.0/source.json
modules/boost.tuple/metadata.json

feat: add boost.tuple

---

modules/fremtind_rules_vitest/0.2.1/MODULE.bazel
modules/fremtind_rules_vitest/0.2.1/patches/module_dot_bazel_version.patch
modules/fremtind_rules_vitest/0.2.1/presubmit.yml
modules/fremtind_rules_vitest/0.2.1/source.json
modules/fremtind_rules_vitest/metadata.json

Release https://github.com/fremtind/rules_vitest/releases/tag/v0.2.1

fremtind_rules_vitest v0.2.1

---

modules/boost.bind/1.83.0/MODULE.bazel
modules/boost.bind/1.83.0/overlay/BUILD.bazel
modules/boost.bind/1.83.0/overlay/MODULE.bazel
modules/boost.bind/1.83.0/presubmit.yml
modules/boost.bind/1.83.0/source.json
modules/boost.bind/metadata.json

- add [boost.bind](http://boost.org/libs/bind)

feat: add boost.bind

---

modules/rules_cpan/1.0.0/MODULE.bazel
modules/rules_cpan/1.0.0/presubmit.yml
modules/rules_cpan/1.0.0/source.json
modules/rules_cpan/metadata.json

Add https://github.com/lalten/rules_cpan

Add rules_cpan

---

modules/cpp-httplib/0.16.3/MODULE.bazel
modules/cpp-httplib/0.16.3/overlay/BUILD.bazel
modules/cpp-httplib/0.16.3/overlay/MODULE.bazel
modules/cpp-httplib/0.16.3/presubmit.yml
modules/cpp-httplib/0.16.3/source.json
modules/cpp-httplib/metadata.json

- add newer cpp-httplib
- enable openssl and zlib support

feat: add cpp-httplib 0.16.3

---

modules/boost.container_hash/1.83.0/MODULE.bazel
modules/boost.container_hash/1.83.0/overlay/BUILD.bazel
modules/boost.container_hash/1.83.0/overlay/MODULE.bazel
modules/boost.container_hash/1.83.0/presubmit.yml
modules/boost.container_hash/1.83.0/source.json
modules/boost.container_hash/metadata.json
modules/boost.mpl/1.83.0/MODULE.bazel
modules/boost.mpl/1.83.0/overlay/BUILD.bazel
modules/boost.mpl/1.83.0/overlay/MODULE.bazel
modules/boost.mpl/1.83.0/presubmit.yml
modules/boost.mpl/1.83.0/source.json
modules/boost.mpl/metadata.json
modules/boost.optional/1.83.0/MODULE.bazel
modules/boost.optional/1.83.0/overlay/BUILD.bazel
modules/boost.optional/1.83.0/overlay/MODULE.bazel
modules/boost.optional/1.83.0/presubmit.yml
modules/boost.optional/1.83.0/source.json
modules/boost.optional/metadata.json

- add boost container_hash, mpl, optional

feat: add boost container_hash, mpl, optional

---

modules/boost.functional/1.83.0/MODULE.bazel
modules/boost.functional/1.83.0/overlay/BUILD.bazel
modules/boost.functional/1.83.0/overlay/MODULE.bazel
modules/boost.functional/1.83.0/presubmit.yml
modules/boost.functional/1.83.0/source.json
modules/boost.functional/metadata.json
modules/boost.pool/1.83.0/MODULE.bazel
modules/boost.pool/1.83.0/overlay/BUILD.bazel
modules/boost.pool/1.83.0/overlay/MODULE.bazel
modules/boost.pool/1.83.0/presubmit.yml
modules/boost.pool/1.83.0/source.json
modules/boost.pool/metadata.json
modules/boost.rational/1.83.0/MODULE.bazel
modules/boost.rational/1.83.0/overlay/BUILD.bazel
modules/boost.rational/1.83.0/overlay/MODULE.bazel
modules/boost.rational/1.83.0/presubmit.yml
modules/boost.rational/1.83.0/source.json
modules/boost.rational/metadata.json
modules/boost.smart_ptr/1.83.0/MODULE.bazel
modules/boost.smart_ptr/1.83.0/overlay/BUILD.bazel
modules/boost.smart_ptr/1.83.0/overlay/MODULE.bazel
modules/boost.smart_ptr/1.83.0/presubmit.yml
modules/boost.smart_ptr/1.83.0/source.json
modules/boost.smart_ptr/metadata.json
modules/boost.variant/1.83.0/MODULE.bazel
modules/boost.variant/1.83.0/overlay/BUILD.bazel
modules/boost.variant/1.83.0/overlay/MODULE.bazel
modules/boost.variant/1.83.0/presubmit.yml
modules/boost.variant/1.83.0/source.json
modules/boost.variant/metadata.json

feat: add boost functional, pool, rational, smart_ptr, variant

---

modules/apple_rules_lint/metadata.json

---
9a9ff501 apple_rules_lint: add gibfahn as maintainer
<br/>

apple_rules_lint: add gibfahn as maintainer

---

metadata.schema.json
modules/rules_detekt/metadata.json
modules/rules_jvm_external/metadata.json
modules/rules_pmd/metadata.json

Note: here's a very fancy regex that includes a check on the max characters: https://github.com/shinnn/github-username-regex?tab=readme-ov-file#githubusernameregex
The one I've added here is simpler and more lax, just intended to catch obvious mistakes.

chore: metadata schema checks github usernames are valid

---

modules/concurrentqueue/1.0.4/MODULE.bazel
modules/concurrentqueue/1.0.4/overlay/BUILD.bazel
modules/concurrentqueue/1.0.4/overlay/MODULE.bazel
modules/concurrentqueue/1.0.4/presubmit.yml
modules/concurrentqueue/1.0.4/source.json
modules/concurrentqueue/metadata.json

- add concurrentqueue from cameron314

feat: add concurrentqueue

---

modules/rules_tar/1.0.0-beta.2/MODULE.bazel
modules/rules_tar/1.0.0-beta.2/presubmit.yml
modules/rules_tar/1.0.0-beta.2/source.json
modules/rules_tar/metadata.json

Learns the `tar_concatenate` rule.

feat: add `rules_tar@1.0.0-beta.2`

---

modules/rules_cuda/0.2.3/MODULE.bazel
modules/rules_cuda/0.2.3/patches/module_dot_bazel_version.patch
modules/rules_cuda/0.2.3/presubmit.yml
modules/rules_cuda/0.2.3/source.json
modules/rules_cuda/metadata.json

- closes #2639
- #2639 is missing presubmit.yaml content

feat: add rules_cuda@v0.2.3

---

modules/boost.iterator/1.83.0/MODULE.bazel
modules/boost.iterator/1.83.0/overlay/BUILD.bazel
modules/boost.iterator/1.83.0/overlay/MODULE.bazel
modules/boost.iterator/1.83.0/presubmit.yml
modules/boost.iterator/1.83.0/source.json
modules/boost.iterator/metadata.json
modules/boost.numeric_conversion/1.83.0/MODULE.bazel
modules/boost.numeric_conversion/1.83.0/overlay/BUILD.bazel
modules/boost.numeric_conversion/1.83.0/overlay/MODULE.bazel
modules/boost.numeric_conversion/1.83.0/presubmit.yml
modules/boost.numeric_conversion/1.83.0/source.json
modules/boost.numeric_conversion/metadata.json
modules/boost.ratio/1.83.0/MODULE.bazel
modules/boost.ratio/1.83.0/overlay/BUILD.bazel
modules/boost.ratio/1.83.0/overlay/MODULE.bazel
modules/boost.ratio/1.83.0/presubmit.yml
modules/boost.ratio/1.83.0/source.json
modules/boost.ratio/metadata.json

feat: add boost iterator, numeric_conversion, ratio

---

modules/boost.range/1.83.0/MODULE.bazel
modules/boost.range/1.83.0/overlay/BUILD.bazel
modules/boost.range/1.83.0/overlay/MODULE.bazel
modules/boost.range/1.83.0/presubmit.yml
modules/boost.range/1.83.0/source.json
modules/boost.range/metadata.json

feat: add boost.range

---

modules/livox_sdk2/1.2.5/MODULE.bazel
modules/livox_sdk2/1.2.5/overlay/BUILD.bazel
modules/livox_sdk2/1.2.5/overlay/MODULE.bazel
modules/livox_sdk2/1.2.5/presubmit.yml
modules/livox_sdk2/1.2.5/source.json
modules/livox_sdk2/metadata.json

- add lidar sdk for livox mid, hap

feat: add livox sdk2

---

modules/libevdev/1.13.2/MODULE.bazel
modules/libevdev/1.13.2/patches/add_build_file.patch
modules/libevdev/1.13.2/patches/module_dot_bazel.patch
modules/libevdev/1.13.2/presubmit.yml
modules/libevdev/1.13.2/source.json
modules/libevdev/metadata.json

This adds bazel configs for the libevdev library for interacting with event-based devices in Linux and FreeBSD.
I followed the instructions correctly, hopefully. :)

Add libevdev (C/C++)

---

modules/fildesh/0.2.0/MODULE.bazel
modules/fildesh/0.2.0/presubmit.yml
modules/fildesh/0.2.0/source.json
modules/fildesh/metadata.json

Release: https://github.com/fildesh/fildesh/releases/tag/v0.2.0

fildesh@0.2.0

---

modules/boost.algorithm/1.83.0/MODULE.bazel
modules/boost.algorithm/1.83.0/overlay/BUILD.bazel
modules/boost.algorithm/1.83.0/overlay/MODULE.bazel
modules/boost.algorithm/1.83.0/presubmit.yml
modules/boost.algorithm/1.83.0/source.json
modules/boost.algorithm/metadata.json
modules/boost.any/1.83.0/MODULE.bazel
modules/boost.any/1.83.0/overlay/BUILD.bazel
modules/boost.any/1.83.0/overlay/MODULE.bazel
modules/boost.any/1.83.0/presubmit.yml
modules/boost.any/1.83.0/source.json
modules/boost.any/metadata.json
modules/boost.intrusive/1.83.0/MODULE.bazel
modules/boost.intrusive/1.83.0/overlay/BUILD.bazel
modules/boost.intrusive/1.83.0/overlay/MODULE.bazel
modules/boost.intrusive/1.83.0/presubmit.yml
modules/boost.intrusive/1.83.0/source.json
modules/boost.intrusive/metadata.json
modules/boost.proto/1.83.0/MODULE.bazel
modules/boost.proto/1.83.0/overlay/BUILD.bazel
modules/boost.proto/1.83.0/overlay/MODULE.bazel
modules/boost.proto/1.83.0/presubmit.yml
modules/boost.proto/1.83.0/source.json
modules/boost.proto/metadata.json

feat: add boost algorithm, any, intrusive, proto

---

modules/boost.atomic/1.83.0/MODULE.bazel
modules/boost.atomic/1.83.0/overlay/BUILD.bazel
modules/boost.atomic/1.83.0/overlay/MODULE.bazel
modules/boost.atomic/1.83.0/presubmit.yml
modules/boost.atomic/1.83.0/source.json
modules/boost.atomic/metadata.json
modules/boost.container/1.83.0/MODULE.bazel
modules/boost.container/1.83.0/overlay/BUILD.bazel
modules/boost.container/1.83.0/overlay/MODULE.bazel
modules/boost.container/1.83.0/presubmit.yml
modules/boost.container/1.83.0/source.json
modules/boost.container/metadata.json

feat: add boost atomic, container

---

modules/rules_elixir/1.1.0/MODULE.bazel
modules/rules_elixir/1.1.0/presubmit.yml
modules/rules_elixir/1.1.0/source.json
modules/rules_elixir/metadata.json

https://github.com/rabbitmq/rules_elixir/releases/tag/v1.1.0

Add rules_elixir@1.1.0

---

modules/zopfli/1.0.3.bcr.1/MODULE.bazel
modules/zopfli/1.0.3.bcr.1/patches/add_build_file.patch
modules/zopfli/1.0.3.bcr.1/patches/module_dot_bazel.patch
modules/zopfli/1.0.3.bcr.1/presubmit.yml
modules/zopfli/1.0.3.bcr.1/source.json
modules/zopfli/metadata.json

zopfli@1.0.3.bcr.1

---

modules/boost.lexical_cast/1.83.0/MODULE.bazel
modules/boost.lexical_cast/1.83.0/overlay/BUILD.bazel
modules/boost.lexical_cast/1.83.0/overlay/MODULE.bazel
modules/boost.lexical_cast/1.83.0/presubmit.yml
modules/boost.lexical_cast/1.83.0/source.json
modules/boost.lexical_cast/metadata.json
modules/boost.phoenix/1.83.0/MODULE.bazel
modules/boost.phoenix/1.83.0/overlay/BUILD.bazel
modules/boost.phoenix/1.83.0/overlay/MODULE.bazel
modules/boost.phoenix/1.83.0/presubmit.yml
modules/boost.phoenix/1.83.0/source.json
modules/boost.phoenix/metadata.json
modules/boost.test/1.83.0/MODULE.bazel
modules/boost.test/1.83.0/overlay/BUILD.bazel
modules/boost.test/1.83.0/overlay/MODULE.bazel
modules/boost.test/1.83.0/presubmit.yml
modules/boost.test/1.83.0/source.json
modules/boost.test/metadata.json

feat: add boost test, lexical_cast, phoenix

---

modules/boost.date_time/1.83.0/MODULE.bazel
modules/boost.date_time/1.83.0/overlay/BUILD.bazel
modules/boost.date_time/1.83.0/overlay/MODULE.bazel
modules/boost.date_time/1.83.0/presubmit.yml
modules/boost.date_time/1.83.0/source.json
modules/boost.date_time/metadata.json
modules/boost.dynamic_bitset/1.83.0/MODULE.bazel
modules/boost.dynamic_bitset/1.83.0/overlay/BUILD.bazel
modules/boost.dynamic_bitset/1.83.0/overlay/MODULE.bazel
modules/boost.dynamic_bitset/1.83.0/presubmit.yml
modules/boost.dynamic_bitset/1.83.0/source.json
modules/boost.dynamic_bitset/metadata.json
modules/boost.polygon/1.83.0/MODULE.bazel
modules/boost.polygon/1.83.0/overlay/BUILD.bazel
modules/boost.polygon/1.83.0/overlay/MODULE.bazel
modules/boost.polygon/1.83.0/presubmit.yml
modules/boost.polygon/1.83.0/source.json
modules/boost.polygon/metadata.json
modules/boost.qvm/1.83.0/MODULE.bazel
modules/boost.qvm/1.83.0/overlay/BUILD.bazel
modules/boost.qvm/1.83.0/overlay/MODULE.bazel
modules/boost.qvm/1.83.0/presubmit.yml
modules/boost.qvm/1.83.0/source.json
modules/boost.qvm/metadata.json

feat: add boost date_time, dynamic_bitset, polygon, qvm

---

modules/boost.context/1.83.0/MODULE.bazel
modules/boost.context/1.83.0/overlay/BUILD.bazel
modules/boost.context/1.83.0/overlay/MODULE.bazel
modules/boost.context/1.83.0/presubmit.yml
modules/boost.context/1.83.0/source.json
modules/boost.context/metadata.json
modules/boost.random/1.83.0/MODULE.bazel
modules/boost.random/1.83.0/overlay/BUILD.bazel
modules/boost.random/1.83.0/overlay/MODULE.bazel
modules/boost.random/1.83.0/presubmit.yml
modules/boost.random/1.83.0/source.json
modules/boost.random/metadata.json

feat: add boost context, random

---

modules/boost.coroutine/1.83.0/MODULE.bazel
modules/boost.coroutine/1.83.0/overlay/BUILD.bazel
modules/boost.coroutine/1.83.0/overlay/MODULE.bazel
modules/boost.coroutine/1.83.0/presubmit.yml
modules/boost.coroutine/1.83.0/source.json
modules/boost.coroutine/metadata.json
modules/boost.interprocess/1.83.0/MODULE.bazel
modules/boost.interprocess/1.83.0/overlay/BUILD.bazel
modules/boost.interprocess/1.83.0/overlay/MODULE.bazel
modules/boost.interprocess/1.83.0/presubmit.yml
modules/boost.interprocess/1.83.0/source.json
modules/boost.interprocess/metadata.json

feat: add boost coroutine, interprocess

---

modules/boost.thread/1.83.0/MODULE.bazel
modules/boost.thread/1.83.0/overlay/BUILD.bazel
modules/boost.thread/1.83.0/overlay/MODULE.bazel
modules/boost.thread/1.83.0/overlay/test/BUILD.bazel
modules/boost.thread/1.83.0/overlay/test/MODULE.bazel
modules/boost.thread/1.83.0/patches/fix_assert.patch
modules/boost.thread/1.83.0/presubmit.yml
modules/boost.thread/1.83.0/source.json
modules/boost.thread/metadata.json

- as title
- add patch for posix build

feat: add boost thread

---

modules/boost.spirit/1.83.0/MODULE.bazel
modules/boost.spirit/1.83.0/overlay/BUILD.bazel
modules/boost.spirit/1.83.0/overlay/MODULE.bazel
modules/boost.spirit/1.83.0/overlay/test/BUILD.bazel
modules/boost.spirit/1.83.0/overlay/test/MODULE.bazel
modules/boost.spirit/1.83.0/presubmit.yml
modules/boost.spirit/1.83.0/source.json
modules/boost.spirit/metadata.json

feat: add boost spirit

---

modules/boost.compatibility/1.83.0/MODULE.bazel
modules/boost.compatibility/1.83.0/overlay/BUILD.bazel
modules/boost.compatibility/1.83.0/overlay/MODULE.bazel
modules/boost.compatibility/1.83.0/presubmit.yml
modules/boost.compatibility/1.83.0/source.json
modules/boost.compatibility/metadata.json

feat: add boost compatibility

---

modules/foxglove_websocket/1.3.0/MODULE.bazel
modules/foxglove_websocket/1.3.0/overlay/BUILD.bazel
modules/foxglove_websocket/1.3.0/overlay/MODULE.bazel
modules/foxglove_websocket/1.3.0/presubmit.yml
modules/foxglove_websocket/1.3.0/source.json
modules/foxglove_websocket/metadata.json

feat: add foxglove websocket 1.3.0

---

modules/boost.property_tree/1.83.0/MODULE.bazel
modules/boost.property_tree/1.83.0/overlay/BUILD.bazel
modules/boost.property_tree/1.83.0/overlay/MODULE.bazel
modules/boost.property_tree/1.83.0/presubmit.yml
modules/boost.property_tree/1.83.0/source.json
modules/boost.property_tree/metadata.json

feat: add boost property_tree

---

modules/geographiclib/2.4.0/MODULE.bazel
modules/geographiclib/2.4.0/overlay/BUILD.bazel
modules/geographiclib/2.4.0/overlay/MODULE.bazel
modules/geographiclib/2.4.0/presubmit.yml
modules/geographiclib/2.4.0/source.json
modules/geographiclib/metadata.json

- as title
- https://geographiclib.sourceforge.io/

feat: add geographiclib 2.4

---

modules/rules_bison/0.3/MODULE.bazel
modules/rules_bison/0.3/presubmit.yml
modules/rules_bison/0.3/source.json
modules/rules_bison/metadata.json

Release: https://github.com/jmillikin/rules_bison/releases/tag/v0.3

rules_bison@0.3

---

modules/boost.scope_exit/1.83.0/MODULE.bazel
modules/boost.scope_exit/1.83.0/overlay/BUILD.bazel
modules/boost.scope_exit/1.83.0/overlay/MODULE.bazel
modules/boost.scope_exit/1.83.0/presubmit.yml
modules/boost.scope_exit/1.83.0/source.json
modules/boost.scope_exit/metadata.json

- rework on #2938 
- closes #2938

feat: add boost scope_exit

---

modules/rapidjson/1.1.0.bcr.20241007/MODULE.bazel
modules/rapidjson/1.1.0.bcr.20241007/patches/add_build_file.patch
modules/rapidjson/1.1.0.bcr.20241007/patches/module_dot_bazel.patch
modules/rapidjson/1.1.0.bcr.20241007/presubmit.yml
modules/rapidjson/1.1.0.bcr.20241007/source.json
modules/rapidjson/metadata.json

There hasn't been a tag on this repo in 8 years, this pulls in the most
recent commit

Add rapidjson commit

---

modules/flann/1.9.2/MODULE.bazel
modules/flann/1.9.2/overlay/BUILD.bazel
modules/flann/1.9.2/overlay/MODULE.bazel
modules/flann/1.9.2/presubmit.yml
modules/flann/1.9.2/source.json
modules/flann/metadata.json

- as title
- https://www.cs.ubc.ca/research/flann/

feat: add flann 1.9.2

---

modules/sqlite3/3.46.1/MODULE.bazel
modules/sqlite3/3.46.1/patches/add_build_file.patch
modules/sqlite3/3.46.1/patches/module_dot_bazel.patch
modules/sqlite3/3.46.1/presubmit.yml
modules/sqlite3/3.46.1/source.json
modules/sqlite3/metadata.json

Closes https://github.com/bazelbuild/bazel-central-registry/pull/2132.

sqlite3@3.46.1

---

modules/boost.signals2/1.83.0/MODULE.bazel
modules/boost.signals2/1.83.0/overlay/BUILD.bazel
modules/boost.signals2/1.83.0/overlay/MODULE.bazel
modules/boost.signals2/1.83.0/presubmit.yml
modules/boost.signals2/1.83.0/source.json
modules/boost.signals2/metadata.json

feat: add boost signals2

---

modules/boost.sort/1.83.0/MODULE.bazel
modules/boost.sort/1.83.0/overlay/BUILD.bazel
modules/boost.sort/1.83.0/overlay/MODULE.bazel
modules/boost.sort/1.83.0/presubmit.yml
modules/boost.sort/1.83.0/source.json
modules/boost.sort/metadata.json

feat: add boost.sort

---

modules/boost.iostreams/1.83.0/MODULE.bazel
modules/boost.iostreams/1.83.0/overlay/BUILD.bazel
modules/boost.iostreams/1.83.0/overlay/MODULE.bazel
modules/boost.iostreams/1.83.0/presubmit.yml
modules/boost.iostreams/1.83.0/source.json
modules/boost.iostreams/metadata.json
modules/boost.multi_array/1.83.0/MODULE.bazel
modules/boost.multi_array/1.83.0/overlay/BUILD.bazel
modules/boost.multi_array/1.83.0/overlay/MODULE.bazel
modules/boost.multi_array/1.83.0/presubmit.yml
modules/boost.multi_array/1.83.0/source.json
modules/boost.multi_array/metadata.json
modules/boost.program_options/1.83.0/MODULE.bazel
modules/boost.program_options/1.83.0/overlay/BUILD.bazel
modules/boost.program_options/1.83.0/overlay/MODULE.bazel
modules/boost.program_options/1.83.0/overlay/test/BUILD.bazel
modules/boost.program_options/1.83.0/overlay/test/MODULE.bazel
modules/boost.program_options/1.83.0/presubmit.yml
modules/boost.program_options/1.83.0/source.json
modules/boost.program_options/metadata.json
modules/boost.ptr_container/1.83.0/MODULE.bazel
modules/boost.ptr_container/1.83.0/overlay/BUILD.bazel
modules/boost.ptr_container/1.83.0/overlay/MODULE.bazel
modules/boost.ptr_container/1.83.0/presubmit.yml
modules/boost.ptr_container/1.83.0/source.json
modules/boost.ptr_container/metadata.json

feat: add boost iostreams, multi_array, program_options, ptr_container

---

modules/bazel-diff/7.3.0/MODULE.bazel
modules/bazel-diff/7.3.0/presubmit.yml
modules/bazel-diff/7.3.0/source.json
modules/bazel-diff/metadata.json

Bazel diff 7.3.0

---

modules/pcl/1.14.1/MODULE.bazel
modules/pcl/1.14.1/overlay/BUILD.bazel
modules/pcl/1.14.1/overlay/MODULE.bazel
modules/pcl/1.14.1/overlay/test/BUILD.bazel
modules/pcl/1.14.1/overlay/test/MODULE.bazel
modules/pcl/1.14.1/presubmit.yml
modules/pcl/1.14.1/source.json
modules/pcl/metadata.json

- closes https://github.com/bazelbuild/bazel-central-registry/issues/1279

feat: add pcl

---

modules/foxglove_schemas_protobuf/0.2.1/MODULE.bazel
modules/foxglove_schemas_protobuf/0.2.1/overlay/BUILD.bazel
modules/foxglove_schemas_protobuf/0.2.1/overlay/MODULE.bazel
modules/foxglove_schemas_protobuf/0.2.1/presubmit.yml
modules/foxglove_schemas_protobuf/0.2.1/source.json
modules/foxglove_schemas_protobuf/metadata.json

feat: add foxglove schemas protobuf 0.2.1

---

modules/boost.process/1.83.0/MODULE.bazel
modules/boost.process/1.83.0/overlay/BUILD.bazel
modules/boost.process/1.83.0/overlay/MODULE.bazel
modules/boost.process/1.83.0/presubmit.yml
modules/boost.process/1.83.0/source.json
modules/boost.process/metadata.json

Closes https://github.com/bazelbuild/bazel-central-registry/issues/2993
Took the deps from https://alandefreitas.github.io/boostdep_graph/index.html

Add boost.process

---

modules/babylon/1.4.2/MODULE.bazel
modules/babylon/1.4.2/presubmit.yml
modules/babylon/1.4.2/source.json
modules/babylon/metadata.json

babylon@1.4.2

---

modules/emboss/2024.1017.203246/MODULE.bazel
modules/emboss/2024.1017.203246/patches/module_dot_bazel.patch
modules/emboss/2024.1017.203246/presubmit.yml
modules/emboss/2024.1017.203246/source.json
modules/emboss/metadata.json

Release: https://github.com/google/emboss/releases/download/v2024.1017.203246/emboss.zip

emboss@2024.1017.203246

---

modules/rules_buf/metadata.json

I had volunteer time to make the initial BCR entry for this ruleset but I don't have time to maintain it.
FYI @srikrsna-buf

chore: hand off rules_buf maintainership

---

modules/download_utils/1.0.0-beta.4/MODULE.bazel
modules/download_utils/1.0.0-beta.4/presubmit.yml
modules/download_utils/1.0.0-beta.4/source.json
modules/download_utils/metadata.json

feat: add `download_utils@1.0.0-beta.4`

---

modules/boost.tti/1.83.0.bcr.1/MODULE.bazel
modules/boost.tti/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.tti/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.tti/1.83.0.bcr.1/presubmit.yml
modules/boost.tti/1.83.0.bcr.1/source.json
modules/boost.tti/metadata.json
modules/boost.uuid/1.83.0.bcr.1/MODULE.bazel
modules/boost.uuid/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.uuid/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.uuid/1.83.0.bcr.1/presubmit.yml
modules/boost.uuid/1.83.0.bcr.1/source.json
modules/boost.uuid/metadata.json

feat: update boost.tti, uuid

---

modules/boost.parameter/1.83.0.bcr.1/MODULE.bazel
modules/boost.parameter/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.parameter/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.parameter/1.83.0.bcr.1/presubmit.yml
modules/boost.parameter/1.83.0.bcr.1/source.json
modules/boost.parameter/metadata.json
modules/boost.scope_exit/1.83.0.bcr.1/MODULE.bazel
modules/boost.scope_exit/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.scope_exit/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.scope_exit/1.83.0.bcr.1/presubmit.yml
modules/boost.scope_exit/1.83.0.bcr.1/source.json
modules/boost.scope_exit/metadata.json
modules/boost.signals2/1.83.0.bcr.1/MODULE.bazel
modules/boost.signals2/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.signals2/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.signals2/1.83.0.bcr.1/presubmit.yml
modules/boost.signals2/1.83.0.bcr.1/source.json
modules/boost.signals2/metadata.json
modules/boost.variant/1.83.0.bcr.1/MODULE.bazel
modules/boost.variant/1.83.0.bcr.1/overlay/BUILD.bazel
modules/boost.variant/1.83.0.bcr.1/overlay/MODULE.bazel
modules/boost.variant/1.83.0.bcr.1/presubmit.yml
modules/boost.variant/1.83.0.bcr.1/source.json
modules/boost.variant/metadata.json

Fix empty glob in boost.parameter .scope_exit .signals2

---

modules/xsimd/8.1.0/MODULE.bazel
modules/xsimd/8.1.0/patches/add_build_file.patch
modules/xsimd/8.1.0/patches/module_dot_bazel.patch
modules/xsimd/8.1.0/presubmit.yml
modules/xsimd/8.1.0/source.json
modules/xsimd/metadata.json

add new module xsimd and its first bcr version 8.1.0

add xsimd@8.1.0

---

modules/rules_cpan/1.1.0/MODULE.bazel
modules/rules_cpan/1.1.0/presubmit.yml
modules/rules_cpan/1.1.0/source.json
modules/rules_cpan/metadata.json

Add https://github.com/lalten/rules_cpan/releases/tag/v1.1.0 which should fix https://github.com/bazelbuild/bazel-central-registry/issues/3056 for rules_cpan

Add rules_cpan@1.1.0

---

modules/lcov/2.2/MODULE.bazel
modules/lcov/2.2/overlay/BUILD
modules/lcov/2.2/overlay/MODULE.bazel
modules/lcov/2.2/overlay/cpanfile
modules/lcov/2.2/overlay/cpanfile.snapshot
modules/lcov/2.2/overlay/cpanfile.snapshot.lock.json
modules/lcov/2.2/presubmit.yml
modules/lcov/2.2/source.json
modules/lcov/metadata.json

Add https://github.com/linux-test-project/lcov/releases/tag/v2.2

Add lcov@2.2

---

MODULE.bazel

Bump rules aspect_rules_js to 1.42.3

Bump rules aspect_rules_js to 1.42.3

---

MODULE.bazel

Bump rules_python to 0.40.0

---

modules/livox_sdk2/1.2.5.bcr.1/MODULE.bazel
modules/livox_sdk2/1.2.5.bcr.1/overlay/BUILD.bazel
modules/livox_sdk2/1.2.5.bcr.1/overlay/MODULE.bazel
modules/livox_sdk2/1.2.5.bcr.1/patches/gcc13_compat.patch
modules/livox_sdk2/1.2.5.bcr.1/presubmit.yml
modules/livox_sdk2/1.2.5.bcr.1/source.json
modules/livox_sdk2/metadata.json

- patch from https://github.com/Livox-SDK/Livox-SDK2/pull/85

feat: update livox sdk2

---

modules/reproc/14.2.5/MODULE.bazel
modules/reproc/14.2.5/overlay/BUILD.bazel
modules/reproc/14.2.5/overlay/MODULE.bazel
modules/reproc/14.2.5/presubmit.yml
modules/reproc/14.2.5/source.json
modules/reproc/metadata.json

reproc@14.2.5
Resolving https://github.com/bazelbuild/bazel-central-registry/issues/3221

reproc@14.2.5

---

MODULE.bazel

Bump aspect_rules_js to 2.1.0

---

modules/rules_m4/0.2.4/MODULE.bazel
modules/rules_m4/0.2.4/presubmit.yml
modules/rules_m4/0.2.4/source.json
modules/rules_m4/metadata.json

Release: https://github.com/jmillikin/rules_m4/releases/tag/v0.2.4

rules_m4@0.2.4

---

modules/cutlass/3.5.1/MODULE.bazel
modules/cutlass/3.5.1/patches/add_build_file.patch
modules/cutlass/3.5.1/patches/module_dot_bazel.patch
modules/cutlass/3.5.1/presubmit.yml
modules/cutlass/3.5.1/source.json
modules/cutlass/metadata.json

add cutlass@3.5.1

---

modules/nanopb/0.4.9.1/MODULE.bazel
modules/nanopb/0.4.9.1/patches/bazel.patch
modules/nanopb/0.4.9.1/presubmit.yml
modules/nanopb/0.4.9.1/source.json
modules/nanopb/metadata.json

@PetteriAimonen FYI, adding the new release to the BCR.

nanopb@0.4.9.1

---

modules/open62541/1.4.6/MODULE.bazel
modules/open62541/1.4.6/patches/add_build_file.patch
modules/open62541/1.4.6/patches/build_with_boringssl.patch
modules/open62541/1.4.6/patches/module_dot_bazel.patch
modules/open62541/1.4.6/patches/open62541-create-bzl.patch
modules/open62541/1.4.6/presubmit.yml
modules/open62541/1.4.6/source.json
modules/open62541/metadata.json

@bazel-io skip_check unstable_url no stable release url in upstream repo.

Add open62541

---

modules/openssl/3.3.1.bcr.0/MODULE.bazel
modules/openssl/3.3.1.bcr.0/overlay/BUILD.bazel
modules/openssl/3.3.1.bcr.0/overlay/MODULE.bazel
modules/openssl/3.3.1.bcr.0/overlay/test_bazel_build/BUILD.bazel
modules/openssl/3.3.1.bcr.0/overlay/utils.bzl
modules/openssl/3.3.1.bcr.0/presubmit.yml
modules/openssl/3.3.1.bcr.0/source.json
modules/openssl/metadata.json

Add openssl 3.3.1.bcr.0

---

modules/skcms/20241202.0/MODULE.bazel
modules/skcms/20241202.0/overlay/BUILD.bazel
modules/skcms/20241202.0/overlay/MODULE.bazel
modules/skcms/20241202.0/presubmit.yml
modules/skcms/20241202.0/source.json
modules/skcms/metadata.json

Add skcms module

---

modules/trompeloeil/49/MODULE.bazel
modules/trompeloeil/49/overlay/BUILD.bazel
modules/trompeloeil/49/overlay/MODULE.bazel
modules/trompeloeil/49/overlay/test/BUILD.bazel
modules/trompeloeil/49/overlay/test/MODULE.bazel
modules/trompeloeil/49/presubmit.yml
modules/trompeloeil/49/source.json
modules/trompeloeil/metadata.json

Add trompeloeil v49

---

modules/glpk/5.0.bcr.2/MODULE.bazel
modules/glpk/5.0.bcr.2/patches/add_build_file.patch
modules/glpk/5.0.bcr.2/patches/module_dot_bazel.patch
modules/glpk/5.0.bcr.2/presubmit.yml
modules/glpk/5.0.bcr.2/source.json
modules/glpk/metadata.json

remove empty glob rule
bump dependency in MODULE + patch

fix glpk for bazel 8

---

modules/opentelemetry-proto/1.4.0.bcr.1/MODULE.bazel
modules/opentelemetry-proto/1.4.0.bcr.1/patches/module_dot_bazel.patch
modules/opentelemetry-proto/1.4.0.bcr.1/presubmit.yml
modules/opentelemetry-proto/1.4.0.bcr.1/source.json
modules/opentelemetry-proto/metadata.json

Add Python and Go proto bindings

Improve opentelemetry-proto

---

modules/cpplint/2.0.0/MODULE.bazel
modules/cpplint/2.0.0/patches/add_build_file.patch
modules/cpplint/2.0.0/patches/module_dot_bazel.patch
modules/cpplint/2.0.0/presubmit.yml
modules/cpplint/2.0.0/source.json
modules/cpplint/metadata.json

bump: add cpplint 2.0.0

---

modules/periphery/3.0.0.beta9/MODULE.bazel
modules/periphery/3.0.0.beta9/presubmit.yml
modules/periphery/3.0.0.beta9/source.json
modules/periphery/metadata.json

Should be the last beta before the final release 🤞.

Add periphery 3.0.0.beta9

---

modules/skcms/20241202.0.bcr.1/MODULE.bazel
modules/skcms/20241202.0.bcr.1/overlay/BUILD.bazel
modules/skcms/20241202.0.bcr.1/overlay/MODULE.bazel
modules/skcms/20241202.0.bcr.1/presubmit.yml
modules/skcms/20241202.0.bcr.1/source.json
modules/skcms/metadata.json

BUILD file provided in initial module release was stale

skcms fixup: link missing symbols

---

README.md
docs/README.md

small style improvements in README

docs: Improve md syntax in README

---

modules/envoy_api/0.0.0-20241214-918efc9/MODULE.bazel
modules/envoy_api/0.0.0-20241214-918efc9/patches/bzlmod_fixes.patch
modules/envoy_api/0.0.0-20241214-918efc9/patches/module_dot_bazel.patch
modules/envoy_api/0.0.0-20241214-918efc9/presubmit.yml
modules/envoy_api/0.0.0-20241214-918efc9/source.json
modules/envoy_api/metadata.json

- Based on https://github.com/envoyproxy/envoy/pull/34355
- Requires https://github.com/bazelbuild/bazel-central-registry/pull/3420 and https://github.com/bazelbuild/bazel-central-registry/pull/3423
- Upstreaming target name alignment in https://github.com/bazelbuild/bazel-central-registry/pull/3415 and https://github.com/envoyproxy/envoy/pull/37662
- Issue for patched Protobuf: https://github.com/envoyproxy/envoy/issues/37669

Add envoy_api

---

modules/zstr/1.0.7/MODULE.bazel
modules/zstr/1.0.7/overlay/BUILD.bazel
modules/zstr/1.0.7/overlay/MODULE.bazel
modules/zstr/1.0.7/presubmit.yml
modules/zstr/1.0.7/source.json
modules/zstr/metadata.json

Small C++ wrapper around zlib. 
Header only.

initial version of zstr

---

modules/verible/0.0.3892/MODULE.bazel
modules/verible/0.0.3892/patches/module_dot_bazel.patch
modules/verible/0.0.3892/presubmit.yml
modules/verible/0.0.3892/source.json
modules/verible/metadata.json

Add verible@0.0.3892

---

modules/bant/0.1.11/MODULE.bazel
modules/bant/0.1.11/presubmit.yml
modules/bant/0.1.11/source.json
modules/bant/metadata.json

Add bant@0.1.11

---

modules/rules_nccl/0.0.1/MODULE.bazel
modules/rules_nccl/0.0.1/presubmit.yml
modules/rules_nccl/0.0.1/source.json
modules/rules_nccl/metadata.json

A simple module for compiling and linking local installed NCCL library.
Release: https://github.com/MoFHeka/rules_nccl/releases/tag/v0.0.1
Author: @MoFHeka

rules_nccl@0.0.1

---

modules/rules_spring/2.6.1/MODULE.bazel
modules/rules_spring/2.6.1/presubmit.yml
modules/rules_spring/2.6.1/source.json
modules/rules_spring/metadata.json

patch release for rules_spring
https://github.com/salesforce/rules_spring/releases/tag/2.6.1

rules_spring 2.6.1

---

modules/pugixml/1.15/MODULE.bazel
modules/pugixml/1.15/overlay/BUILD.bazel
modules/pugixml/1.15/overlay/MODULE.bazel
modules/pugixml/1.15/presubmit.yml
modules/pugixml/1.15/source.json
modules/pugixml/metadata.json

pugixml@1.15

---

MODULE.bazel

Update buildozer to 7.3.1

---

modules/byte_track_eigen/2.1.0.bcr.1/MODULE.bazel
modules/byte_track_eigen/2.1.0.bcr.1/overlay/BUILD.bazel
modules/byte_track_eigen/2.1.0.bcr.1/overlay/MODULE.bazel
modules/byte_track_eigen/2.1.0.bcr.1/presubmit.yml
modules/byte_track_eigen/2.1.0.bcr.1/source.json
modules/byte_track_eigen/metadata.json

chore: update rules_cc in byte-track-eigen

---

modules/livox_sdk2/1.2.5.bcr.2/MODULE.bazel
modules/livox_sdk2/1.2.5.bcr.2/overlay/BUILD.bazel
modules/livox_sdk2/1.2.5.bcr.2/overlay/MODULE.bazel
modules/livox_sdk2/1.2.5.bcr.2/patches/gcc13_compat.patch
modules/livox_sdk2/1.2.5.bcr.2/presubmit.yml
modules/livox_sdk2/1.2.5.bcr.2/source.json
modules/livox_sdk2/metadata.json

chore: update rules_cc in livox sdk2

---

tools/bcr_validation.py

Context: https://github.com/bazelbuild/bazel-central-registry/pull/3633

Disallow dir symlinks under modules/

---

modules/envoy_api/0.0.0-20250128-4de3c74/MODULE.bazel
modules/envoy_api/0.0.0-20250128-4de3c74/patches/bzlmod_fixes.patch
modules/envoy_api/0.0.0-20250128-4de3c74/patches/module_dot_bazel.patch
modules/envoy_api/0.0.0-20250128-4de3c74/presubmit.yml
modules/envoy_api/0.0.0-20250128-4de3c74/source.json
modules/envoy_api/metadata.json

Based on https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/envoy_api/0.0.0-20241214-918efc9
- Applied the same set of patches except the changes already upstreamed.

Added envoy_api@0.0.0-20250128-4de3c74

---

modules/rules_android_ndk/0.1.3/MODULE.bazel
modules/rules_android_ndk/0.1.3/patches/module_dot_bazel_version.patch
modules/rules_android_ndk/0.1.3/presubmit.yml
modules/rules_android_ndk/0.1.3/source.json
modules/rules_android_ndk/metadata.json

Fixes https://github.com/bazelbuild/rules_android_ndk/issues/99

Add rules_android_ndk v0.1.3

---

modules/openconfig_gnmi/0.13.0/MODULE.bazel
modules/openconfig_gnmi/0.13.0/presubmit.yml
modules/openconfig_gnmi/0.13.0/source.json
modules/openconfig_gnmi/metadata.json

Add BCR package for github.com/openconfig/gnmi.

Add openconfig_gnmi@0.13.0

---

modules/rapidcheck/2023.12.14/BUILD.bazel
modules/rapidcheck/2023.12.14/MODULE.bazel
modules/rapidcheck/2023.12.14/patches/add_build_file.patch
modules/rapidcheck/2023.12.14/patches/module_dot_bazel.patch
modules/rapidcheck/2023.12.14/presubmit.yml
modules/rapidcheck/2023.12.14/source.json
modules/rapidcheck/metadata.json

This PR adds the rapidcheck dependency to the BCR.

add rapidcheck to BCR

---

modules/rules_pkl/0.4.0/MODULE.bazel
modules/rules_pkl/0.4.0/presubmit.yml
modules/rules_pkl/0.4.0/source.json
modules/rules_pkl/metadata.json

Release notes: https://github.com/apple/rules_pkl/releases/tag/v0.4.0

Add `0.4.0` release of `rules_pkl`

---

modules/rules_android/0.6.1/MODULE.bazel
modules/rules_android/0.6.1/presubmit.yml
modules/rules_android/0.6.1/source.json
modules/rules_android/metadata.json

https://github.com/bazelbuild/rules_android/issues/329

rules_android v0.6.1

---

modules/foxglove_schemas_protobuf/0.2.2.bcr.1/MODULE.bazel
modules/foxglove_schemas_protobuf/0.2.2.bcr.1/overlay/BUILD.bazel
modules/foxglove_schemas_protobuf/0.2.2.bcr.1/overlay/MODULE.bazel
modules/foxglove_schemas_protobuf/0.2.2.bcr.1/presubmit.yml
modules/foxglove_schemas_protobuf/0.2.2.bcr.1/source.json
modules/foxglove_schemas_protobuf/metadata.json

- integrity has changed due to the change of the repository
- yank old versions

fix: update foxglove schema protobuf

---

modules/pcre2/10.45/MODULE.bazel
modules/pcre2/10.45/presubmit.yml
modules/pcre2/10.45/source.json
modules/pcre2/metadata.json

Release tag: https://github.com/PCRE2Project/pcre2/releases/tag/pcre2-10.45.
Upstream release tracking issue: https://github.com/PCRE2Project/pcre2/issues/683.

pcre2@10.45

---

modules/rules_tar/1.0.1/MODULE.bazel
modules/rules_tar/1.0.1/presubmit.yml
modules/rules_tar/1.0.1/source.json
modules/rules_tar/metadata.json
modules/rules_xz/1.0.1/MODULE.bazel
modules/rules_xz/1.0.1/presubmit.yml
modules/rules_xz/1.0.1/source.json
modules/rules_xz/metadata.json

Yank `rules_{xz,tar}@1.0.0`

---

modules/exprtk/0.0.3/MODULE.bazel
modules/exprtk/0.0.3/overlay/BUILD.bazel
modules/exprtk/0.0.3/overlay/MODULE.bazel
modules/exprtk/0.0.3/presubmit.yml
modules/exprtk/0.0.3/source.json
modules/exprtk/metadata.json

Added the latest version `0.0.3` from https://github.com/ArashPartow/exprtk.

Added `exprtk`.

---

MODULE.bazel

Bump rules_python to 1.1.0

---

modules/openjph/0.21.0/MODULE.bazel
modules/openjph/0.21.0/overlay/BUILD.bazel
modules/openjph/0.21.0/overlay/MODULE.bazel
modules/openjph/0.21.0/presubmit.yml
modules/openjph/0.21.0/source.json
modules/openjph/metadata.json

openjph@0.21.0

---

MODULE.bazel

Bump aspect_rules_js to 2.2.0

---

tools/bcr_validation.py

Addressing https://buildkite.com/bazel/bcr-presubmit/builds/11273#019560ee-feb9-4556-8103-ed721d5fffff

Fix source repo check in bcr_validation.py

---

README.md
docs/README.md

- flesh out main README.md a bit more with an overview
- add some thus far undocumented information to the contribution guidelines

Add some more docs

---

modules/icu/76.1/MODULE.bazel
modules/icu/76.1/overlay/MODULE.bazel
modules/icu/76.1/presubmit.yml
modules/icu/76.1/source.json
modules/icu/metadata.json

Added `icu`.

---

modules/boost.dll/1.87.0/MODULE.bazel
modules/boost.dll/1.87.0/overlay/BUILD.bazel
modules/boost.dll/1.87.0/overlay/MODULE.bazel
modules/boost.dll/1.87.0/presubmit.yml
modules/boost.dll/1.87.0/source.json
modules/boost.dll/metadata.json

Add https://github.com/boostorg/dll/tree/boost-1.87.0
Cc: @wep21 @Vertexwahn

Add boost.dll

---

modules/jsonnet/metadata.json

Add @johnbartholomew (me) as a maintainer for the `jsonnet` module.

jsonnet: add maintainer

---

modules/libffi/3.4.7.bcr.1/MODULE.bazel
modules/libffi/3.4.7.bcr.1/overlay/BUILD.bazel
modules/libffi/3.4.7.bcr.1/overlay/MODULE.bazel
modules/libffi/3.4.7.bcr.1/presubmit.yml
modules/libffi/3.4.7.bcr.1/source.json
modules/libffi/metadata.json

Previously this wasn't tested and wasn't working.

Add mac support to libffi.

---

modules/libusb/1.0.28/MODULE.bazel
modules/libusb/1.0.28/overlay/BUILD.bazel
modules/libusb/1.0.28/overlay/MODULE.bazel
modules/libusb/1.0.28/overlay/config.h-linux
modules/libusb/1.0.28/overlay/config.h-macos
modules/libusb/1.0.28/presubmit.yml
modules/libusb/1.0.28/source.json
modules/libusb/metadata.json

feat: add libusb

---

modules/boost.icl/1.83.0/MODULE.bazel
modules/boost.icl/1.83.0/overlay/BUILD.bazel
modules/boost.icl/1.83.0/overlay/MODULE.bazel
modules/boost.icl/1.83.0/presubmit.yml
modules/boost.icl/1.83.0/source.json
modules/boost.icl/1.87.0/MODULE.bazel
modules/boost.icl/1.87.0/overlay/BUILD.bazel
modules/boost.icl/1.87.0/overlay/MODULE.bazel
modules/boost.icl/1.87.0/presubmit.yml
modules/boost.icl/1.87.0/source.json
modules/boost.icl/metadata.json
modules/boost.stacktrace/1.83.0/MODULE.bazel
modules/boost.stacktrace/1.83.0/overlay/BUILD.bazel
modules/boost.stacktrace/1.83.0/overlay/MODULE.bazel
modules/boost.stacktrace/1.83.0/presubmit.yml
modules/boost.stacktrace/1.83.0/source.json
modules/boost.stacktrace/1.87.0/MODULE.bazel
modules/boost.stacktrace/1.87.0/overlay/BUILD.bazel
modules/boost.stacktrace/1.87.0/overlay/MODULE.bazel
modules/boost.stacktrace/1.87.0/presubmit.yml
modules/boost.stacktrace/1.87.0/source.json
modules/boost.stacktrace/metadata.json

- as title
requested by @hzeller

feat: add boost.icl, boost.stacktrace

---

modules/pystring/1.1.4/MODULE.bazel
modules/pystring/1.1.4/overlay/BUILD.bazel
modules/pystring/1.1.4/overlay/MODULE.bazel
modules/pystring/1.1.4/presubmit.yml
modules/pystring/1.1.4/source.json
modules/pystring/metadata.json

pystring@1.1.4

---

modules/alsa_lib/1.2.9/MODULE.bazel
modules/alsa_lib/1.2.9/overlay/BUILD.bazel
modules/alsa_lib/1.2.9/overlay/MODULE.bazel
modules/alsa_lib/1.2.9/presubmit.yml
modules/alsa_lib/1.2.9/source.json
modules/alsa_lib/metadata.json

https://www.alsa-project.org/wiki/Main_Page

alsa_lib@1.2.9

---

docs/bcr-policies.md

Please suggest any other checks that you usually do!

Add a playbook for BCR maintainers

---

modules/icu/76.1.bcr.1/MODULE.bazel
modules/icu/76.1.bcr.1/README.md
modules/icu/76.1.bcr.1/overlay/MODULE.bazel
modules/icu/76.1.bcr.1/overlay/bcr/BUILD.bazel
modules/icu/76.1.bcr.1/overlay/bcr/break_iterator_test.cc
modules/icu/76.1.bcr.1/patches/icu4c_source_common_BUILD.bazel.patch
modules/icu/76.1.bcr.1/patches/icu4c_source_common_putil.cpp.patch
modules/icu/76.1.bcr.1/presubmit.yml
modules/icu/76.1.bcr.1/source.json
modules/icu/metadata.json

ICU is nothing without its data. See https://unicode-org.github.io/icu/userguide/icu_data/ for reference.

Updated `icu` to compile with data.

---

MODULE.bazel

Update rules_python to version 1.3.0

Update rules_python to version 1.3.0

---

modules/rules_ytt/0.4.0/MODULE.bazel
modules/rules_ytt/0.4.0/patches/module_dot_bazel.patch
modules/rules_ytt/0.4.0/presubmit.yml
modules/rules_ytt/0.4.0/source.json
modules/rules_ytt/metadata.json

Release https://github.com/ekhabarov/rules_ytt/releases/tag/v0.4.0

rules_ytt@0.4.0.

---

modules/saru/0.0.0-20130617092049-c11c375fefd7/MODULE.bazel
modules/saru/0.0.0-20130617092049-c11c375fefd7/patches/diff.patch
modules/saru/0.0.0-20130617092049-c11c375fefd7/presubmit.yml
modules/saru/0.0.0-20130617092049-c11c375fefd7/source.json
modules/saru/metadata.json

Added saru

---

modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/MODULE.bazel
modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/patches/module-dot-bazel-dev-dependency.patch
modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/patches/module-dot-bazel-pypi-hub-name.patch
modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/patches/module-dot-bazel-version.patch
modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/presubmit.yml
modules/pybind11_protobuf/0.0.0-20250210-f02a2b7/source.json
modules/pybind11_protobuf/metadata.json

This adds support for Protobuf v30.

Add pybind11_protobuf 0.0.0-20250210-f02a2b7

---

modules/libcap/2.27/MODULE.bazel
modules/libcap/2.27/overlay/BUILD.bazel
modules/libcap/2.27/overlay/MODULE.bazel
modules/libcap/2.27/presubmit.yml
modules/libcap/2.27/source.json
modules/libcap/metadata.json

Build file taken from: https://github.com/google/sandboxed-api/blob/main/sandboxed_api/bazel/external/libcap.BUILD

Add libcap 2.27

---

modules/prodrive_technologies_bazel_latex/1.2.2-20250401-c552d5b/MODULE.bazel
modules/prodrive_technologies_bazel_latex/1.2.2-20250401-c552d5b/overlay/MODULE.bazel
modules/prodrive_technologies_bazel_latex/1.2.2-20250401-c552d5b/presubmit.yml
modules/prodrive_technologies_bazel_latex/1.2.2-20250401-c552d5b/source.json
modules/prodrive_technologies_bazel_latex/metadata.json

prodrive_technologies_bazel_latex@1.2.2-20250401-c552d5b

prodrive_technologies_bazel_latex@1.2.2-20250401-c552d5b

---

MODULE.bazel

Bump aspect_rules_js to 2.3.3

---

modules/cel-spec/0.23.0/MODULE.bazel
modules/cel-spec/0.23.0/patches/module_dot_bazel.patch
modules/cel-spec/0.23.0/presubmit.yml
modules/cel-spec/0.23.0/source.json
modules/cel-spec/metadata.json

Public cel-spec@0.23.0
Update the maintainers to refer to a CEL team member.

Add cel-spec@0.23.0

---

modules/rules_ios/5.6.0/MODULE.bazel
modules/rules_ios/5.6.0/patches/module_dot_bazel_version.patch
modules/rules_ios/5.6.0/presubmit.yml
modules/rules_ios/5.6.0/source.json
modules/rules_ios/metadata.json

Had to manually do this since the publish-to-bcr action didn't

Add rules_ios 5.6.0

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

To deploy recent changes:
- https://github.com/bazelbuild/continuous-integration/pull/2213
- https://github.com/bazelbuild/continuous-integration/pull/2202

Update BCR PR reviewer

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

Deploying the fix in bazelbuild/continuous-integration#2217

Update BCR PR reviewer workflows

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

Fix for: https://github.com/bazelbuild/continuous-integration/pull/2220

Bump BCR PR reviewer workflows

---

modules/gutil/20250409.0/MODULE.bazel
modules/gutil/20250409.0/presubmit.yml
modules/gutil/20250409.0/source.json
modules/gutil/metadata.json

gutil-20250409

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

Wrong hash used in https://github.com/bazelbuild/bazel-central-registry/pull/4286

Update BCR PR Reviewer commit

---

modules/osqp-eigen/0.10.0/MODULE.bazel
modules/osqp-eigen/0.10.0/overlay/BUILD.bazel
modules/osqp-eigen/0.10.0/overlay/MODULE.bazel
modules/osqp-eigen/0.10.0/overlay/tests/BUILD.bazel
modules/osqp-eigen/0.10.0/overlay/tests/MODULE.bazel
modules/osqp-eigen/0.10.0/presubmit.yml
modules/osqp-eigen/0.10.0/source.json
modules/osqp-eigen/metadata.json

feat: add osqp-eigen

---

modules/aspect_rules_lint/1.3.4/MODULE.bazel
modules/aspect_rules_lint/1.3.4/attestations.json
modules/aspect_rules_lint/1.3.4/patches/module_dot_bazel_version.patch
modules/aspect_rules_lint/1.3.4/presubmit.yml
modules/aspect_rules_lint/1.3.4/source.json
modules/aspect_rules_lint/metadata.json

Release: https://github.com/aspect-build/rules_lint/releases/tag/v1.3.4

Publish aspect_rules_lint@1.3.4

---

tools/slsa.py

Useful for debugging.
Progress towards https://github.com/bazelbuild/bazel-central-registry/issues/3829

Print slsa-verifier command and output

---

modules/librdkafka/2.3.0/MODULE.bazel
modules/librdkafka/2.3.0/overlay/BUILD.bazel
modules/librdkafka/2.3.0/overlay/MODULE.bazel
modules/librdkafka/2.3.0/overlay/test/MODULE.bazel
modules/librdkafka/2.3.0/patches/src-cpp_rdkafkacpp_int.h.patch
modules/librdkafka/2.3.0/patches/src_rd.h.patch
modules/librdkafka/2.3.0/patches/src_tinycthread.h.patch
modules/librdkafka/2.3.0/patches/tests_0113-cooperative_rebalance.cpp.patch
modules/librdkafka/2.3.0/patches/tests_testcpp.h.patch
modules/librdkafka/2.3.0/presubmit.yml
modules/librdkafka/2.3.0/source.json
modules/librdkafka/metadata.json

This change aims to provide backward compatibility for the Rust community until https://github.com/fede1024/rust-rdkafka/issues/755 can be implemented.

librdkafka@2.3.0

---

modules/gawk/5.3.2/MODULE.bazel
modules/gawk/5.3.2/overlay/BUILD.bazel
modules/gawk/5.3.2/overlay/MODULE.bazel
modules/gawk/5.3.2/overlay/posix/config_darwin.h
modules/gawk/5.3.2/overlay/posix/config_linux.h
modules/gawk/5.3.2/overlay/test/BUILD.bazel
modules/gawk/5.3.2/presubmit.yml
modules/gawk/5.3.2/source.json
modules/gawk/metadata.json

closes https://github.com/bazelbuild/bazel-central-registry/issues/4246

gawk@5.3.2

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

To deploy https://github.com/bazelbuild/continuous-integration/pull/2233

Update BCR reviewer hash

---

modules/boringssl/metadata.json

As such I probably should not be approving these anymore. David Adrian has volunteered to help ensure this stays covered.

I have been laid off from Google.

---

modules/suitesparse/7.10.1.bcr.1/MODULE.bazel
modules/suitesparse/7.10.1.bcr.1/overlay/BUILD.bazel
modules/suitesparse/7.10.1.bcr.1/overlay/MODULE.bazel
modules/suitesparse/7.10.1.bcr.1/presubmit.yml
modules/suitesparse/7.10.1.bcr.1/source.json
modules/suitesparse/metadata.json

https://github.com/bazelbuild/bazel-central-registry/pull/4145#discussion_r2045029917

feat: update suitesparse 7.10.1 and yank previous one

---

modules/nasm/2.14.02.bcr.1/MODULE.bazel
modules/nasm/2.14.02.bcr.1/patches/add_build_file.patch
modules/nasm/2.14.02.bcr.1/patches/add_config_h.patch
modules/nasm/2.14.02.bcr.1/patches/add_module_dot_bazel.patch
modules/nasm/2.14.02.bcr.1/presubmit.yml
modules/nasm/2.14.02.bcr.1/source.json
modules/nasm/2.16.03.bcr.1/MODULE.bazel
modules/nasm/2.16.03.bcr.1/overlay/BUILD.bazel
modules/nasm/2.16.03.bcr.1/overlay/MODULE.bazel
modules/nasm/2.16.03.bcr.1/overlay/config_linux.h
modules/nasm/2.16.03.bcr.1/overlay/config_macos.h
modules/nasm/2.16.03.bcr.1/presubmit.yml
modules/nasm/2.16.03.bcr.1/source.json
modules/nasm/metadata.json

These updates account for the http://www.nasm.us/ outage.
relates to https://github.com/bazelbuild/bazel-central-registry/issues/4354

nasm@2.16.03.bcr.1

---

modules/aspect_bazel_lib/2.15.3/MODULE.bazel
modules/aspect_bazel_lib/2.15.3/attestations.json
modules/aspect_bazel_lib/2.15.3/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.15.3/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.15.3/presubmit.yml
modules/aspect_bazel_lib/2.15.3/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.15.3

Publish aspect_bazel_lib@2.15.3

---

modules/cxx.rs/1.0.158/MODULE.bazel
modules/cxx.rs/1.0.158/patches/module_dot_bazel_version.patch
modules/cxx.rs/1.0.158/presubmit.yml
modules/cxx.rs/1.0.158/source.json
modules/cxx.rs/metadata.json

Release: https://github.com/dtolnay/cxx/releases/tag/1.0.158

Publish cxx.rs@1.0.158

---

modules/aspect_rules_js/2.3.7/MODULE.bazel
modules/aspect_rules_js/2.3.7/attestations.json
modules/aspect_rules_js/2.3.7/patches/module_dot_bazel_version.patch
modules/aspect_rules_js/2.3.7/presubmit.yml
modules/aspect_rules_js/2.3.7/source.json
modules/aspect_rules_js/metadata.json

Release: https://github.com/aspect-build/rules_js/releases/tag/v2.3.7

Publish aspect_rules_js@2.3.7

---

modules/aspect_rules_py/1.3.4/MODULE.bazel
modules/aspect_rules_py/1.3.4/attestations.json
modules/aspect_rules_py/1.3.4/patches/module_dot_bazel_version.patch
modules/aspect_rules_py/1.3.4/patches/rust_dev_dep.patch
modules/aspect_rules_py/1.3.4/presubmit.yml
modules/aspect_rules_py/1.3.4/source.json
modules/aspect_rules_py/metadata.json

Release: https://github.com/aspect-build/rules_py/releases/tag/v1.3.4

Publish aspect_rules_py@1.3.4

---

modules/gawk/5.3.2.bcr.1/MODULE.bazel
modules/gawk/5.3.2.bcr.1/overlay/BUILD.bazel
modules/gawk/5.3.2.bcr.1/overlay/MODULE.bazel
modules/gawk/5.3.2.bcr.1/overlay/posix/config_darwin.h
modules/gawk/5.3.2.bcr.1/overlay/posix/config_linux.h
modules/gawk/5.3.2.bcr.1/overlay/test/BUILD.bazel
modules/gawk/5.3.2.bcr.1/presubmit.yml
modules/gawk/5.3.2.bcr.1/source.json
modules/gawk/metadata.json

Changes:
- Silence compiler warnings

gawk@5.3.2.bcr.1

---

modules/aspect_rules_jest/0.23.1/MODULE.bazel
modules/aspect_rules_jest/0.23.1/attestations.json
modules/aspect_rules_jest/0.23.1/patches/module_dot_bazel_version.patch
modules/aspect_rules_jest/0.23.1/presubmit.yml
modules/aspect_rules_jest/0.23.1/source.json
modules/aspect_rules_jest/metadata.json

Release: https://github.com/aspect-build/rules_jest/releases/tag/v0.23.1

Publish aspect_rules_jest@0.23.1

---

modules/aspect_rules_esbuild/0.22.1/MODULE.bazel
modules/aspect_rules_esbuild/0.22.1/attestations.json
modules/aspect_rules_esbuild/0.22.1/patches/module_dot_bazel_version.patch
modules/aspect_rules_esbuild/0.22.1/presubmit.yml
modules/aspect_rules_esbuild/0.22.1/source.json
modules/aspect_rules_esbuild/metadata.json

Release: https://github.com/aspect-build/rules_esbuild/releases/tag/v0.22.1

Publish aspect_rules_esbuild@0.22.1

---

MODULE.bazel
tools/bazel-vet

feat: add a tool to verify attestations of direct module deps

---

modules/effcee/0.0.0-20250222/MODULE.bazel
modules/effcee/0.0.0-20250222/patches/pr_82.patch
modules/effcee/0.0.0-20250222/presubmit.yml
modules/effcee/0.0.0-20250222/source.json
modules/effcee/metadata.json

closes https://github.com/bazelbuild/bazel-central-registry/issues/4369

effcee@0.0.0-20250222

---

modules/nlohmann_json/3.12.0/MODULE.bazel
modules/nlohmann_json/3.12.0/patches/add_singleheader_target.patch
modules/nlohmann_json/3.12.0/patches/module_dot_bazel.patch
modules/nlohmann_json/3.12.0/presubmit.yml
modules/nlohmann_json/3.12.0/source.json
modules/nlohmann_json/metadata.json

nlohmann_json@3.12.0

---

modules/rules_nasm/0.3.1/MODULE.bazel
modules/rules_nasm/0.3.1/presubmit.yml
modules/rules_nasm/0.3.1/source.json
modules/rules_nasm/metadata.json

https://github.com/morganwl/rules_nasm/releases/tag/0.3.1

rules_nasm@0.3.1

---

modules/aspect_bazel_lib/2.16.0/MODULE.bazel
modules/aspect_bazel_lib/2.16.0/attestations.json
modules/aspect_bazel_lib/2.16.0/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.16.0/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.16.0/presubmit.yml
modules/aspect_bazel_lib/2.16.0/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.16.0

Publish aspect_bazel_lib@2.16.0

---

modules/ftxui/6.1.9/MODULE.bazel
modules/ftxui/6.1.9/presubmit.yml
modules/ftxui/6.1.9/source.json
modules/ftxui/metadata.json

Release: https://github.com/ArthurSonzogni/FTXUI/releases/tag/v6.1.9

Publish ftxui@6.1.9

---

modules/openconfig_gnsi/1.9.0/MODULE.bazel
modules/openconfig_gnsi/1.9.0/patches/module_dot_bazel.patch
modules/openconfig_gnsi/1.9.0/presubmit.yml
modules/openconfig_gnsi/1.9.0/source.json
modules/openconfig_gnsi/metadata.json

Add BCR package for github.com/openconfig/gnsi.

Add openconfig_gnsi@1.9.0

---

.github/workflows/dismiss_approvals.yml
.github/workflows/generate_module_diff.yml
.github/workflows/notify_maintainers.yml
.github/workflows/review_prs.yml
.github/workflows/skip_check.yml

Deploy https://github.com/bazelbuild/continuous-integration/pull/2297
Closing https://github.com/bazel-contrib/publish-to-bcr/issues/261

Update BCR PR reviewer hash

---

modules/cjson/1.7.19-0.20240923110858-12c4bf1986c2.bcr.1/MODULE.bazel
modules/cjson/1.7.19-0.20240923110858-12c4bf1986c2.bcr.1/patches/diff.patch
modules/cjson/1.7.19-0.20240923110858-12c4bf1986c2.bcr.1/presubmit.yml
modules/cjson/1.7.19-0.20240923110858-12c4bf1986c2.bcr.1/source.json
modules/cjson/metadata.json

cjson@1.7.19-0.20240923110858-12c4bf1986c2.bcr.1

---

tools/bcr_validation.py

Add a bazel_compatibility checks when using overlay directories,

Add validation of bazel_compatibility

---

tools/bcr_validation.py

Fix typo in bcr_validation.py

---

modules/argparse/3.2.0/MODULE.bazel
modules/argparse/3.2.0/patches/module_dot_bazel.patch
modules/argparse/3.2.0/presubmit.yml
modules/argparse/3.2.0/source.json
modules/argparse/metadata.json

Release: https://github.com/p-ranav/argparse/archive/refs/tags/v3.2.tar.gz

Add argparse-3.2.0

---

modules/remotery/1.0.0/MODULE.bazel
modules/remotery/1.0.0/patches/add_build_file.patch
modules/remotery/1.0.0/patches/module_dot_bazel.patch
modules/remotery/1.0.0/presubmit.yml
modules/remotery/1.0.0/source.json
modules/remotery/metadata.json

Adds remotery v1.0.0 from: https://github.com/Celtoys/Remotery

Add remotery

---

modules/byte_track_eigen/2.1.0.bcr.2/MODULE.bazel
modules/byte_track_eigen/2.1.0.bcr.2/overlay/BUILD.bazel
modules/byte_track_eigen/2.1.0.bcr.2/overlay/MODULE.bazel
modules/byte_track_eigen/2.1.0.bcr.2/presubmit.yml
modules/byte_track_eigen/2.1.0.bcr.2/source.json
modules/byte_track_eigen/metadata.json

chore: update deps of byte track eigen

---

modules/libdeflate/1.24/MODULE.bazel
modules/libdeflate/1.24/overlay/BUILD.bazel
modules/libdeflate/1.24/overlay/MODULE.bazel
modules/libdeflate/1.24/presubmit.yml
modules/libdeflate/1.24/source.json
modules/libdeflate/metadata.json

libdeflate@1.24

---

modules/aspect_bazel_lib/2.17.0/MODULE.bazel
modules/aspect_bazel_lib/2.17.0/attestations.json
modules/aspect_bazel_lib/2.17.0/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.17.0/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.17.0/presubmit.yml
modules/aspect_bazel_lib/2.17.0/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.17.0

Publish aspect_bazel_lib@2.17.0

---

modules/aspect_bazel_lib/2.17.1/MODULE.bazel
modules/aspect_bazel_lib/2.17.1/attestations.json
modules/aspect_bazel_lib/2.17.1/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.17.1/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.17.1/presubmit.yml
modules/aspect_bazel_lib/2.17.1/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.17.1

Publish aspect_bazel_lib@2.17.1

---

modules/rules_cc_resources/0.2.0/MODULE.bazel
modules/rules_cc_resources/0.2.0/presubmit.yml
modules/rules_cc_resources/0.2.0/source.json
modules/rules_cc_resources/metadata.json

add date type uint,reduce cpp file size

Add rules_cc_resources.0.2.0

---

modules/gz-common/6.1.0/MODULE.bazel
modules/gz-common/6.1.0/patches/module_dot_bazel.patch
modules/gz-common/6.1.0/presubmit.yml
modules/gz-common/6.1.0/source.json
modules/gz-common/metadata.json

Add gz-common: https://github.com/gazebosim/gz-common

Add gz-common module

---

modules/openconfig_gnoi/0.6.2/MODULE.bazel
modules/openconfig_gnoi/0.6.2/patches/module_dot_bazel.patch
modules/openconfig_gnoi/0.6.2/presubmit.yml
modules/openconfig_gnoi/0.6.2/source.json
modules/openconfig_gnoi/metadata.json

Add BCR package for github.com/openconfig/gnoi.

Add openconfig_gnoi@0.6.2

---

modules/aspect_rules_py/1.6.0-rc0/MODULE.bazel
modules/aspect_rules_py/1.6.0-rc0/attestations.json
modules/aspect_rules_py/1.6.0-rc0/patches/module_dot_bazel_version.patch
modules/aspect_rules_py/1.6.0-rc0/patches/rust_dev_dep.patch
modules/aspect_rules_py/1.6.0-rc0/presubmit.yml
modules/aspect_rules_py/1.6.0-rc0/source.json
modules/aspect_rules_py/metadata.json

Release: https://github.com/aspect-build/rules_py/releases/tag/v1.6.0-rc0

Publish aspect_rules_py@1.6.0-rc0

---

modules/rules_vulkan/0.2.0/MODULE.bazel
modules/rules_vulkan/0.2.0/attestations.json
modules/rules_vulkan/0.2.0/patches/module_dot_bazel_version.patch
modules/rules_vulkan/0.2.0/presubmit.yml
modules/rules_vulkan/0.2.0/source.json
modules/rules_vulkan/metadata.json

Release: https://github.com/mxpv/rules_vulkan/releases/tag/v0.2.0

Publish rules_vulkan@0.2.0

---

modules/aspect_bazel_lib/2.19.2/MODULE.bazel
modules/aspect_bazel_lib/2.19.2/attestations.json
modules/aspect_bazel_lib/2.19.2/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.19.2/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.19.2/presubmit.yml
modules/aspect_bazel_lib/2.19.2/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.19.2

Publish aspect_bazel_lib@2.19.2

---

modules/aexml/4.7.0.1/MODULE.bazel
modules/aexml/4.7.0.1/patches/add_build_file.patch
modules/aexml/4.7.0.1/patches/module_dot_bazel.patch
modules/aexml/4.7.0.1/presubmit.yml
modules/aexml/4.7.0.1/source.json
modules/aexml/metadata.json

Required for rules_swift 3 support

Patch aexml 4.7.0 for rules_swift 3 support

---

modules/libgpiod/1.6.3/MODULE.bazel
modules/libgpiod/1.6.3/overlay/BUILD.bazel
modules/libgpiod/1.6.3/overlay/MODULE.bazel
modules/libgpiod/1.6.3/overlay/lib/misc.c
modules/libgpiod/1.6.3/presubmit.yml
modules/libgpiod/1.6.3/source.json
modules/libgpiod/metadata.json

Adding the tests depends on bazelifying libkmod

Add libgpiod 1.6.3

---

tools/README.md
tools/bcr_validation.py

This fixes #4854 and updates the README.md with the latest --help output.

fix #4854 by adding support for skipping attestations and presubmit_task

---

modules/aspect_bazel_lib/2.19.4/MODULE.bazel
modules/aspect_bazel_lib/2.19.4/attestations.json
modules/aspect_bazel_lib/2.19.4/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.19.4/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.19.4/presubmit.yml
modules/aspect_bazel_lib/2.19.4/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.19.4

Publish aspect_bazel_lib@2.19.4

---

modules/wolfd_bazel_compile_commands/0.5.2/MODULE.bazel
modules/wolfd_bazel_compile_commands/0.5.2/presubmit.yml
modules/wolfd_bazel_compile_commands/0.5.2/source.json
modules/wolfd_bazel_compile_commands/metadata.json

wolfd_bazel_compile_commands is a C/C++ compile_commands.json generator

Add wolfd_bazel_compile_commands

---

modules/aspect_rules_js/2.3.8/MODULE.bazel
modules/aspect_rules_js/2.3.8/attestations.json
modules/aspect_rules_js/2.3.8/patches/module_dot_bazel_version.patch
modules/aspect_rules_js/2.3.8/presubmit.yml
modules/aspect_rules_js/2.3.8/source.json
modules/aspect_rules_js/metadata.json

Release: https://github.com/aspect-build/rules_js/releases/tag/v2.3.8

Publish aspect_rules_js@2.3.8

---

MODULE.bazel

Bump rules_shell to 0.5.0

---

MODULE.bazel

Bump rules_python to 1.5.0

---

modules/boost.geometry/1.87.0/MODULE.bazel
modules/boost.geometry/1.87.0/overlay/BUILD.bazel
modules/boost.geometry/1.87.0/overlay/MODULE.bazel
modules/boost.geometry/1.87.0/presubmit.yml
modules/boost.geometry/1.87.0/source.json
modules/boost.geometry/metadata.json
modules/boost.scope_exit/1.87.0/MODULE.bazel
modules/boost.scope_exit/1.87.0/overlay/BUILD.bazel
modules/boost.scope_exit/1.87.0/overlay/MODULE.bazel
modules/boost.scope_exit/1.87.0/presubmit.yml
modules/boost.scope_exit/1.87.0/source.json
modules/boost.scope_exit/metadata.json

fix https://github.com/bazelbuild/bazel-central-registry/pull/5048

feat: upgrade boost scope_exit and geometry to 1.87.0

---

modules/aspect_rules_ts/3.6.3/MODULE.bazel
modules/aspect_rules_ts/3.6.3/attestations.json
modules/aspect_rules_ts/3.6.3/patches/module_dot_bazel_version.patch
modules/aspect_rules_ts/3.6.3/presubmit.yml
modules/aspect_rules_ts/3.6.3/source.json
modules/aspect_rules_ts/metadata.json

Release: https://github.com/aspect-build/rules_ts/releases/tag/v3.6.3

Publish aspect_rules_ts@3.6.3

---

modules/aspect_tools_telemetry/0.1.0/MODULE.bazel
modules/aspect_tools_telemetry/0.1.0/attestations.json
modules/aspect_tools_telemetry/0.1.0/patches/module_dot_bazel_version.patch
modules/aspect_tools_telemetry/0.1.0/presubmit.yml
modules/aspect_tools_telemetry/0.1.0/source.json
modules/aspect_tools_telemetry/metadata.json

Release: https://github.com/aspect-build/tools_telemetry/releases/tag/v0.1.0

Publish aspect_tools_telemetry@0.1.0

---

modules/package_metadata/0.0.4/MODULE.bazel
modules/package_metadata/0.0.4/attestations.json
modules/package_metadata/0.0.4/presubmit.yml
modules/package_metadata/0.0.4/source.json
modules/supply-chain-go/0.0.4/MODULE.bazel
modules/supply-chain-go/0.0.4/attestations.json
modules/supply-chain-go/0.0.4/presubmit.yml
modules/supply-chain-go/0.0.4/source.json
modules/supply-chain-go/metadata.json

Release: https://github.com/bazel-contrib/supply-chain/releases/tag/v0.0.4

Publish {supply-chain-go,package_metadata}@0.0.4

---

tools/bcr_validation.py

This caused all BCR pipelines to fail.

Fix incorrect variable reference introduced in #5165

---

modules/re2/metadata.json

Address https://github.com/bazelbuild/bazel-central-registry/pull/5092#issuecomment-3074315416

Update maintainer info for re2

---

modules/fcl/0.7.0.bcr.1/MODULE.bazel
modules/fcl/0.7.0.bcr.1/patches/add_assert_include.patch
modules/fcl/0.7.0.bcr.1/patches/add_build_file.patch
modules/fcl/0.7.0.bcr.1/patches/add_export_header.patch
modules/fcl/0.7.0.bcr.1/patches/module_dot_bazel.patch
modules/fcl/0.7.0.bcr.1/presubmit.yml
modules/fcl/0.7.0.bcr.1/source.json
modules/fcl/metadata.json

Add `add_assert_include.patch` to fix issue with assert not being declared found on certain compilers / flags

fcl@0.7.0.bcr.1

---

modules/gz-physics/8.2.0.bcr.2/MODULE.bazel
modules/gz-physics/8.2.0.bcr.2/patches/fix_build_bazel.patch
modules/gz-physics/8.2.0.bcr.2/patches/module_dot_bazel.patch
modules/gz-physics/8.2.0.bcr.2/presubmit.yml
modules/gz-physics/8.2.0.bcr.2/source.json
modules/gz-physics/metadata.json

Bump dartsim dependency from `6.13.2` to `6.13.2.bcr.1`

gz-physics@8.2.0.bcr.2

---

modules/boost.describe/1.88.0.bcr.1/MODULE.bazel
modules/boost.describe/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.describe/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.describe/1.88.0.bcr.1/presubmit.yml
modules/boost.describe/1.88.0.bcr.1/source.json
modules/boost.describe/metadata.json

boost.describe@1.88.0.bcr.1

---

modules/boost.assert/1.88.0.bcr.1/MODULE.bazel
modules/boost.assert/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.assert/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.assert/1.88.0.bcr.1/presubmit.yml
modules/boost.assert/1.88.0.bcr.1/source.json
modules/boost.assert/metadata.json

boost.assert@1.88.0.bcr.1

---

modules/boost.move/1.88.0.bcr.1/MODULE.bazel
modules/boost.move/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.move/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.move/1.88.0.bcr.1/presubmit.yml
modules/boost.move/1.88.0.bcr.1/source.json
modules/boost.move/metadata.json

boost.move@1.88.0.bcr.1

---

modules/boost.container_hash/1.88.0.bcr.1/MODULE.bazel
modules/boost.container_hash/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.container_hash/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.container_hash/1.88.0.bcr.1/presubmit.yml
modules/boost.container_hash/1.88.0.bcr.1/source.json
modules/boost.container_hash/metadata.json

boost.container_hash@1.88.0.bcr.1

boost.container_hash@1.88.0.bcr.1

---

modules/boost.variant2/1.88.0.bcr.1/MODULE.bazel
modules/boost.variant2/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.variant2/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.variant2/1.88.0.bcr.1/presubmit.yml
modules/boost.variant2/1.88.0.bcr.1/source.json
modules/boost.variant2/metadata.json

boost.variant2@1.88.0.bcr.1

---

modules/rules_cc/0.1.4/MODULE.bazel
modules/rules_cc/0.1.4/attestations.json
modules/rules_cc/0.1.4/patches/module_dot_bazel_version.patch
modules/rules_cc/0.1.4/presubmit.yml
modules/rules_cc/0.1.4/source.json
modules/rules_cc/metadata.json

Release: https://github.com/bazelbuild/rules_cc/releases/tag/0.1.4

Publish rules_cc@0.1.4

---

modules/boost.ratio/1.88.0.bcr.1/MODULE.bazel
modules/boost.ratio/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.ratio/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.ratio/1.88.0.bcr.1/presubmit.yml
modules/boost.ratio/1.88.0.bcr.1/source.json
modules/boost.ratio/metadata.json

boost.ratio@1.88.0.bcr.1

---

modules/libxau/1.0.12.bcr.1/MODULE.bazel
modules/libxau/1.0.12.bcr.1/overlay/BUILD.bazel
modules/libxau/1.0.12.bcr.1/overlay/MODULE.bazel
modules/libxau/1.0.12.bcr.1/presubmit.yml
modules/libxau/1.0.12.bcr.1/source.json
modules/libxau/metadata.json
modules/libxcb/1.17.0.bcr.1/MODULE.bazel
modules/libxcb/1.17.0.bcr.1/overlay/BUILD.bazel
modules/libxcb/1.17.0.bcr.1/overlay/MODULE.bazel
modules/libxcb/1.17.0.bcr.1/overlay/src/config.h.in
modules/libxcb/1.17.0.bcr.1/presubmit.yml
modules/libxcb/1.17.0.bcr.1/source.json
modules/libxcb/metadata.json
modules/xorgproto/2024.1.bcr.1/MODULE.bazel
modules/xorgproto/2024.1.bcr.1/overlay/BUILD.bazel
modules/xorgproto/2024.1.bcr.1/overlay/MODULE.bazel
modules/xorgproto/2024.1.bcr.1/presubmit.yml
modules/xorgproto/2024.1.bcr.1/source.json
modules/xorgproto/metadata.json

closes https://github.com/bazelbuild/bazel-central-registry/issues/4991

feat: update libxcb

---

modules/boost.array/1.88.0.bcr.1/MODULE.bazel
modules/boost.array/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.array/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.array/1.88.0.bcr.1/presubmit.yml
modules/boost.array/1.88.0.bcr.1/source.json
modules/boost.array/metadata.json
modules/boost.compat/1.88.0.bcr.1/MODULE.bazel
modules/boost.compat/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.compat/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.compat/1.88.0.bcr.1/presubmit.yml
modules/boost.compat/1.88.0.bcr.1/source.json
modules/boost.compat/metadata.json
modules/boost.concept_check/1.88.0.bcr.1/MODULE.bazel
modules/boost.concept_check/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.concept_check/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.concept_check/1.88.0.bcr.1/presubmit.yml
modules/boost.concept_check/1.88.0.bcr.1/source.json
modules/boost.concept_check/metadata.json
modules/boost.core/1.88.0.bcr.1/MODULE.bazel
modules/boost.core/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.core/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.core/1.88.0.bcr.1/presubmit.yml
modules/boost.core/1.88.0.bcr.1/source.json
modules/boost.core/metadata.json

Add Boost 1.88.0 Level 3 deps in particular:
- array
- compat
- concept_check
- core

Add Boost 1.88.0 Level 3 deps

---

modules/double-conversion/3.3.1/MODULE.bazel
modules/double-conversion/3.3.1/overlay/MODULE.bazel
modules/double-conversion/3.3.1/presubmit.yml
modules/double-conversion/3.3.1/source.json
modules/double-conversion/metadata.json

double-conversion@3.3.1

---

modules/boost.leaf/1.88.0.bcr.1/MODULE.bazel
modules/boost.leaf/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.leaf/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.leaf/1.88.0.bcr.1/presubmit.yml
modules/boost.leaf/1.88.0.bcr.1/source.json
modules/boost.leaf/metadata.json

boost.leaf@1.88.0.bcr.1

---

modules/boost.assign/metadata.json
modules/boost.charconv/metadata.json
modules/boost.compat/metadata.json
modules/boost.crc/metadata.json
modules/boost.lockfree/metadata.json
modules/boost.mysql/metadata.json
modules/boost.timer/metadata.json

Add myelf to all BCR Boost modules as a maintainer

Add BCR Boost modules maintainer

---

modules/rules_spring_aot/0.1.0/MODULE.bazel
modules/rules_spring_aot/0.1.0/attestations.json
modules/rules_spring_aot/0.1.0/patches/module_dot_bazel_version.patch
modules/rules_spring_aot/0.1.0/presubmit.yml
modules/rules_spring_aot/0.1.0/source.json
modules/rules_spring_aot/metadata.json

Release: https://github.com/tharakadesilva/rules_spring_aot/releases/tag/v0.1.0

Publish rules_spring_aot@0.1.0

---

modules/aspect_rules_js/2.4.1/MODULE.bazel
modules/aspect_rules_js/2.4.1/attestations.json
modules/aspect_rules_js/2.4.1/patches/module_dot_bazel_version.patch
modules/aspect_rules_js/2.4.1/presubmit.yml
modules/aspect_rules_js/2.4.1/source.json
modules/aspect_rules_js/metadata.json

Release: https://github.com/aspect-build/rules_js/releases/tag/v2.4.1

Publish aspect_rules_js@2.4.1

---

modules/boost.static_string/1.88.0.bcr.1/MODULE.bazel
modules/boost.static_string/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.static_string/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.static_string/1.88.0.bcr.1/presubmit.yml
modules/boost.static_string/1.88.0.bcr.1/source.json
modules/boost.static_string/metadata.json

boost.static_string@1.88.0.bcr.1

boost.static_string@1.88.0.bcr.1

---

modules/boost.random/1.88.0.bcr.1/MODULE.bazel
modules/boost.random/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.random/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.random/1.88.0.bcr.1/presubmit.yml
modules/boost.random/1.88.0.bcr.1/source.json
modules/boost.random/metadata.json

boost.random@1.88.0.bcr.1

---

modules/boost.property_map/1.88.0.bcr.1/MODULE.bazel
modules/boost.property_map/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.property_map/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.property_map/1.88.0.bcr.1/presubmit.yml
modules/boost.property_map/1.88.0.bcr.1/source.json
modules/boost.property_map/metadata.json

boost.property_map@1.88.0.bcr.1

boost.property_map@1.88.0.bcr.1

---

modules/boost.lambda/1.88.0.bcr.1/MODULE.bazel
modules/boost.lambda/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.lambda/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.lambda/1.88.0.bcr.1/presubmit.yml
modules/boost.lambda/1.88.0.bcr.1/source.json
modules/boost.lambda/metadata.json

boost.lambda@1.88.0.bcr.1

---

modules/boost.polygon/1.88.0.bcr.1/MODULE.bazel
modules/boost.polygon/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.polygon/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.polygon/1.88.0.bcr.1/overlay/test/BUILD.bazel
modules/boost.polygon/1.88.0.bcr.1/overlay/test/MODULE.bazel
modules/boost.polygon/1.88.0.bcr.1/presubmit.yml
modules/boost.polygon/1.88.0.bcr.1/source.json
modules/boost.polygon/metadata.json

boost.boost.polygon@1.88.0.bcr.1

---

modules/boost.json/1.88.0.bcr.1/MODULE.bazel
modules/boost.json/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.json/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.json/1.88.0.bcr.1/overlay/boost.json.cpp
modules/boost.json/1.88.0.bcr.1/presubmit.yml
modules/boost.json/1.88.0.bcr.1/source.json
modules/boost.json/metadata.json

boost.json@1.88.0.bcr.1

---

modules/rules_cc/0.2.0/MODULE.bazel
modules/rules_cc/0.2.0/attestations.json
modules/rules_cc/0.2.0/patches/module_dot_bazel_version.patch
modules/rules_cc/0.2.0/presubmit.yml
modules/rules_cc/0.2.0/source.json
modules/rules_cc/metadata.json

Release: https://github.com/bazelbuild/rules_cc/releases/tag/0.2.0

Publish rules_cc@0.2.0

---

modules/boost.algorithm/1.88.0.bcr.1/MODULE.bazel
modules/boost.algorithm/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.algorithm/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.algorithm/1.88.0.bcr.1/presubmit.yml
modules/boost.algorithm/1.88.0.bcr.1/source.json
modules/boost.algorithm/metadata.json

boost.algorithm@1.88.0.bcr.1

---

modules/boost.bimap/1.88.0.bcr.1/MODULE.bazel
modules/boost.bimap/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.bimap/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.bimap/1.88.0.bcr.1/presubmit.yml
modules/boost.bimap/1.88.0.bcr.1/source.json
modules/boost.bimap/metadata.json

boost.bimap@1.88.0.bcr.1

---

modules/boost.units/1.88.0.bcr.1/MODULE.bazel
modules/boost.units/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.units/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.units/1.88.0.bcr.1/presubmit.yml
modules/boost.units/1.88.0.bcr.1/source.json
modules/boost.units/metadata.json

boost.units@1.88.0.bcr.1

---

modules/imath/3.2.0/MODULE.bazel
modules/imath/3.2.0/overlay/BUILD.bazel
modules/imath/3.2.0/overlay/MODULE.bazel
modules/imath/3.2.0/presubmit.yml
modules/imath/3.2.0/source.json
modules/imath/metadata.json

imath@3.2.0

---

MODULE.bazel

Bump rules_python to 1.5.2

---

modules/boost.proto/1.88.0.bcr.1/MODULE.bazel
modules/boost.proto/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.proto/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.proto/1.88.0.bcr.1/presubmit.yml
modules/boost.proto/1.88.0.bcr.1/source.json
modules/boost.proto/metadata.json

boost.proto@1.88.0.bcr.1

---

modules/boost.ptr_container/1.88.0.bcr.1/MODULE.bazel
modules/boost.ptr_container/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.ptr_container/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.ptr_container/1.88.0.bcr.1/presubmit.yml
modules/boost.ptr_container/1.88.0.bcr.1/source.json
modules/boost.ptr_container/metadata.json

boost.ptr_container@1.88.0.bcr.1

boost.ptr_container@1.88.0.bcr.1

---

MODULE.bazel

Update rules_python to 1.5.3

---

modules/lz4/1.9.4.bcr.2/MODULE.bazel
modules/lz4/1.9.4.bcr.2/patches/add_build_file.patch
modules/lz4/1.9.4.bcr.2/patches/add_programs_build_file.patch
modules/lz4/1.9.4.bcr.2/patches/module_dot_bazel.patch
modules/lz4/1.9.4.bcr.2/presubmit.yml
modules/lz4/1.9.4.bcr.2/source.json
modules/lz4/metadata.json

Expose programs:lz4 to public.

Add lz4@1.9.4.bcr.2.

---

modules/nanopb/0.4.9.1.bcr.1/MODULE.bazel
modules/nanopb/0.4.9.1.bcr.1/patches/bazel.patch
modules/nanopb/0.4.9.1.bcr.1/presubmit.yml
modules/nanopb/0.4.9.1.bcr.1/source.json
modules/nanopb/metadata.json

Fixes https://github.com/nanopb/nanopb/issues/1111

nanopb@0.4.9.1.bcr.1

---

modules/aspect_rules_py/1.6.2/MODULE.bazel
modules/aspect_rules_py/1.6.2/attestations.json
modules/aspect_rules_py/1.6.2/patches/module_dot_bazel_version.patch
modules/aspect_rules_py/1.6.2/patches/rust_dev_dep.patch
modules/aspect_rules_py/1.6.2/presubmit.yml
modules/aspect_rules_py/1.6.2/source.json
modules/aspect_rules_py/metadata.json

Release: https://github.com/aspect-build/rules_py/releases/tag/v1.6.2

Publish aspect_rules_py@1.6.2

---

modules/aspect_rules_terser/2.0.1/MODULE.bazel
modules/aspect_rules_terser/2.0.1/attestations.json
modules/aspect_rules_terser/2.0.1/patches/module_dot_bazel_version.patch
modules/aspect_rules_terser/2.0.1/presubmit.yml
modules/aspect_rules_terser/2.0.1/source.json
modules/aspect_rules_terser/metadata.json

Release: https://github.com/aspect-build/rules_terser/releases/tag/v2.0.1

Publish aspect_rules_terser@2.0.1

---

modules/aspect_rules_py/1.6.3/MODULE.bazel
modules/aspect_rules_py/1.6.3/attestations.json
modules/aspect_rules_py/1.6.3/patches/module_dot_bazel_version.patch
modules/aspect_rules_py/1.6.3/patches/rust_dev_dep.patch
modules/aspect_rules_py/1.6.3/presubmit.yml
modules/aspect_rules_py/1.6.3/source.json
modules/aspect_rules_py/metadata.json

Release: https://github.com/aspect-build/rules_py/releases/tag/v1.6.3

Publish aspect_rules_py@1.6.3

---

modules/postgres/14.18.bcr.2/MODULE.bazel
modules/postgres/14.18.bcr.2/overlay/BUILD.bazel
modules/postgres/14.18.bcr.2/overlay/MODULE.bazel
modules/postgres/14.18.bcr.2/presubmit.yml
modules/postgres/14.18.bcr.2/source.json
modules/postgres/metadata.json

Validations:
Ran `bazel run -- //tools:bcr_validation --check=postgres@14.18.bcr.1`

Add missing headers in libpq in module postgres

---

modules/awk.bzl/0.2.2/MODULE.bazel
modules/awk.bzl/0.2.2/attestations.json
modules/awk.bzl/0.2.2/patches/module_dot_bazel_version.patch
modules/awk.bzl/0.2.2/presubmit.yml
modules/awk.bzl/0.2.2/source.json
modules/awk.bzl/metadata.json

Release: https://github.com/alexeagle/awk.bzl/releases/tag/v0.2.2

Publish awk.bzl@0.2.2

---

modules/aspect_bazel_lib/2.21.1/MODULE.bazel
modules/aspect_bazel_lib/2.21.1/attestations.json
modules/aspect_bazel_lib/2.21.1/patches/go_dev_dep.patch
modules/aspect_bazel_lib/2.21.1/patches/module_dot_bazel_version.patch
modules/aspect_bazel_lib/2.21.1/presubmit.yml
modules/aspect_bazel_lib/2.21.1/source.json
modules/aspect_bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.21.1

Publish aspect_bazel_lib@2.21.1

---

modules/aspect_rules_js/2.5.0/MODULE.bazel
modules/aspect_rules_js/2.5.0/attestations.json
modules/aspect_rules_js/2.5.0/patches/module_dot_bazel_version.patch
modules/aspect_rules_js/2.5.0/presubmit.yml
modules/aspect_rules_js/2.5.0/source.json
modules/aspect_rules_js/metadata.json

Release: https://github.com/aspect-build/rules_js/releases/tag/v2.5.0

Publish aspect_rules_js@2.5.0

---

modules/abseil-py/metadata.json
modules/com_github_mvukov_rules_ros2/metadata.json
modules/cython/metadata.json
modules/envoy_api/metadata.json
modules/flatbuffers/metadata.json
modules/glpk/metadata.json
modules/grpc_ecosystem_grpc_gateway/metadata.json
modules/opencensus-cpp/metadata.json
modules/opencensus-proto/metadata.json
modules/protoc-gen-validate/metadata.json
modules/tinygltf/metadata.json

This allows me to upload new versions faster and reduces effort required by BCR maintainers.

Add myself as maintainer for packages I previously uploaded

---

tools/bcr_validation.py

fix regression added at 6c0c0299edcbcf9ace3c92d366a61b2361a05a09
/viz @alexeagle

fix: apply_patch TypeError: expected str

---

modules/grpc_kotlin/1.5.0-rc.1/MODULE.bazel
modules/grpc_kotlin/1.5.0-rc.1/patches/version.patch
modules/grpc_kotlin/1.5.0-rc.1/presubmit.yml
modules/grpc_kotlin/1.5.0-rc.1/source.json
modules/grpc_kotlin/metadata.json

Hi
We are from https://github.com/grpc/grpc-kotlin. We would like to publish it to BCR.
I followed the guidelines and create this PR. Please let us know if there is any more details we need to complete. Also would be great if you can let us know if there is something we need to do about `grpc_kotlin.20250824-191240.json` which fails the tests since it's outside `modules/` but it's generated by the tool
Thanks a lot
Thuan

[New-Module] Publish grpc_kotlin v1.5.0-rc.1 to BCR.

---

modules/boost.url/1.88.0.bcr.1/MODULE.bazel
modules/boost.url/1.88.0.bcr.1/overlay/BUILD.bazel
modules/boost.url/1.88.0.bcr.1/overlay/MODULE.bazel
modules/boost.url/1.88.0.bcr.1/presubmit.yml
modules/boost.url/1.88.0.bcr.1/source.json
modules/boost.url/metadata.json

boost.url@1.88.0.bcr.1

---

modules/boost.hash2/1.89.0/MODULE.bazel
modules/boost.hash2/1.89.0/overlay/BUILD.bazel
modules/boost.hash2/1.89.0/overlay/MODULE.bazel
modules/boost.hash2/1.89.0/overlay/test/BUILD.bazel
modules/boost.hash2/1.89.0/overlay/test/MODULE.bazel
modules/boost.hash2/1.89.0/presubmit.yml
modules/boost.hash2/1.89.0/source.json
modules/boost.hash2/metadata.json

boost.hash2@1.89.0

---

modules/boost.tokenizer/1.89.0/MODULE.bazel
modules/boost.tokenizer/1.89.0/overlay/BUILD.bazel
modules/boost.tokenizer/1.89.0/overlay/MODULE.bazel
modules/boost.tokenizer/1.89.0/presubmit.yml
modules/boost.tokenizer/1.89.0/source.json
modules/boost.tokenizer/metadata.json

boost.tokenizer@1.89.0

---

modules/rules_cc/0.2.4/MODULE.bazel
modules/rules_cc/0.2.4/attestations.json
modules/rules_cc/0.2.4/patches/module_dot_bazel_version.patch
modules/rules_cc/0.2.4/presubmit.yml
modules/rules_cc/0.2.4/source.json
modules/rules_cc/metadata.json

Release: https://github.com/bazelbuild/rules_cc/releases/tag/0.2.4

rules_cc@0.2.4

---

modules/boost.coroutine2/1.89.0/MODULE.bazel
modules/boost.coroutine2/1.89.0/overlay/BUILD.bazel
modules/boost.coroutine2/1.89.0/overlay/MODULE.bazel
modules/boost.coroutine2/1.89.0/presubmit.yml
modules/boost.coroutine2/1.89.0/source.json
modules/boost.coroutine2/metadata.json

boost.coroutine2@1.89.0

---

tools/bcr-mirror/README.md
tools/bcr-mirror/bcr-mirror.js
tools/bcr-mirror/wrangler.jsonc

The worker uploads the source archives of requested modules to a configured R2 bucket.

Add a Cloudflare Worker that maintains a module mirror

---

modules/nonstd-span/0.11.0/MODULE.bazel
modules/nonstd-span/0.11.0/overlay/BUILD.bazel
modules/nonstd-span/0.11.0/overlay/MODULE.bazel
modules/nonstd-span/0.11.0/presubmit.yml
modules/nonstd-span/0.11.0/source.json
modules/nonstd-span/metadata.json

A C++20 `std::span` implementation for C++98, etc.

feat: add `nonstd-span`

---

modules/grpc_kotlin/1.5.0-rc.5/MODULE.bazel
modules/grpc_kotlin/1.5.0-rc.5/patches/module_dot_bazel_version.patch
modules/grpc_kotlin/1.5.0-rc.5/presubmit.yml
modules/grpc_kotlin/1.5.0-rc.5/source.json
modules/grpc_kotlin/metadata.json

Release: https://github.com/grpc/grpc-kotlin/releases/tag/v1.5.0-rc.5

grpc_kotlin@1.5.0-rc.5

---

modules/bazel_bats/0.36.4/MODULE.bazel
modules/bazel_bats/0.36.4/presubmit.yml
modules/bazel_bats/0.36.4/source.json
modules/bazel_bats/metadata.json

Release: https://github.com/filmil/bazel-bats/releases/tag/v0.36.4

Publish bazel_bats@0.36.4

---

tools/code-agent/README.md
tools/code-agent/setup_bzlmod_migration.py

Some success with this:
- https://github.com/google-ml-infra/rules_ml_toolchain/pull/80
- https://github.com/openxla/xla/pull/31477

Add instructions for setting up AI powered bzlmod migration

---

tools/code-agent/setup_bzlmod_migration.py

Obviously this is written by gemini

Improve readability of terminal messages for code agent setup script

---

modules/gotopt2/2.2.0/MODULE.bazel
modules/gotopt2/2.2.0/patches/module_dot_bazel_version.patch
modules/gotopt2/2.2.0/presubmit.yml
modules/gotopt2/2.2.0/source.json
modules/gotopt2/metadata.json

Release: https://github.com/filmil/gotopt2/releases/tag/v2.2.0

Publish gotopt2@2.2.0

---

modules/protovalidate-cc/metadata.json

As per https://github.com/bufbuild/protovalidate-cc/blob/main/.bcr/metadata.template.json

Update maintainers for protovalidate-cc

---

modules/boost.foreach/1.89.0/MODULE.bazel
modules/boost.foreach/1.89.0/overlay/BUILD.bazel
modules/boost.foreach/1.89.0/overlay/MODULE.bazel
modules/boost.foreach/1.89.0/overlay/gen_test_targets.bzl
modules/boost.foreach/1.89.0/presubmit.yml
modules/boost.foreach/1.89.0/source.json
modules/boost.foreach/metadata.json

boost.foreach@1.89.0

---

modules/download_archives/0.1.0/MODULE.bazel
modules/download_archives/0.1.0/attestations.json
modules/download_archives/0.1.0/patches/module_dot_bazel_version.patch
modules/download_archives/0.1.0/presubmit.yml
modules/download_archives/0.1.0/source.json
modules/download_archives/metadata.json

Release: https://github.com/jjmaestro/bazel_download_archives/releases/tag/v0.1.0

Publish download_archives@0.1.0

---

modules/or-tools/9.13/MODULE.bazel
modules/or-tools/9.13/patches/bazel.patch
modules/or-tools/9.13/presubmit.yml
modules/or-tools/9.13/source.json
modules/or-tools/9.14/MODULE.bazel
modules/or-tools/9.14/patches/bazel.patch
modules/or-tools/9.14/presubmit.yml
modules/or-tools/9.14/source.json
modules/or-tools/metadata.json

Add artifact for:
* https://github.com/google/or-tools/releases/tag/v9.13 and
* https://github.com/google/or-tools/releases/tag/v9.14

or-tools: add 9.13 and 9.14

---

modules/xtensor/0.27.1/MODULE.bazel
modules/xtensor/0.27.1/overlay/BUILD.bazel
modules/xtensor/0.27.1/overlay/MODULE.bazel
modules/xtensor/0.27.1/presubmit.yml
modules/xtensor/0.27.1/source.json
modules/xtensor/metadata.json

xtensor@0.27.1

---

modules/bazel_lib/3.0.0-rc.0/MODULE.bazel
modules/bazel_lib/3.0.0-rc.0/attestations.json
modules/bazel_lib/3.0.0-rc.0/patches/go_dev_dep.patch
modules/bazel_lib/3.0.0-rc.0/patches/module_dot_bazel_version.patch
modules/bazel_lib/3.0.0-rc.0/presubmit.yml
modules/bazel_lib/3.0.0-rc.0/source.json
modules/bazel_lib/metadata.json

Release: https://github.com/bazel-contrib/bazel-lib/releases/tag/v3.0.0-rc.0

bazel_lib@3.0.0-rc.0

---

modules/rules_ispc/0.0.6/MODULE.bazel
modules/rules_ispc/0.0.6/presubmit.yml
modules/rules_ispc/0.0.6/source.json
modules/rules_ispc/metadata.json

rules_ispc@0.0.6
